load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "internalcontractapi",
    srcs = ["governance_internal_contract.gen.go"],
    importpath = "github.com/verself/governance-service/internal/internalcontractapi",
    visibility = ["//src/services/governance-service:__subpackages__"],
)

alias(
    name = "go_default_library",
    actual = ":internalcontractapi",
    visibility = ["//src/services/governance-service:__subpackages__"],
)
