haproxy_public_routes:
  - host: '{{ mailbox_service_domain }}'
    backend: be_route_product_mail_api_mailbox_service_public_api
haproxy_public_apis:
  - key: mailbox
    host: '{{ mailbox_service_domain }}'
    path_prefix: /api/v1
