package openbaoruntime

import (
	"os"
	"path/filepath"
	"testing"
)

func TestLoadPlanMapsOwnerLocalSecretsToNomadRoles(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "src/services/billing-service/nomad.hcl", `job "billing" {}`)
	writeFile(t, root, "src/services/billing-service/deploy/runtime-secrets.yml", `
openbao_runtime_secret_seed_declarations:
  - name: billing-service.stripe.secret_key
    site_secret: stripe_secret_key
  - name: billing-service.stripe.webhook_secret
    site_secret: stripe_webhook_secret
`)

	plan, err := LoadPlan(root, "gamma", []Component{{
		Component: "billing",
		JobID:     "billing",
		JobSpec:   "src/services/billing-service/nomad.hcl",
	}})
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Secrets) != 2 {
		t.Fatalf("len(secrets) = %d, want 2", len(plan.Secrets))
	}
	if len(plan.NomadRoles) != 1 {
		t.Fatalf("len(roles) = %d, want 1", len(plan.NomadRoles))
	}
	role := plan.NomadRoles[0]
	if role.Name != "billing-runtime" {
		t.Fatalf("role name = %q", role.Name)
	}
	if role.Policy != "nomad-runtime-billing" {
		t.Fatalf("policy name = %q", role.Policy)
	}
	if role.Secrets[0] != "billing-service.stripe.secret_key" || role.Secrets[1] != "billing-service.stripe.webhook_secret" {
		t.Fatalf("role secrets = %#v", role.Secrets)
	}
}

func TestLoadPlanRejectsRuntimeSecretsWithoutNomadOwner(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "src/services/billing-service/deploy/runtime-secrets.yml", `
openbao_runtime_secret_seed_declarations:
  - name: billing-service.stripe.secret_key
    site_secret: stripe_secret_key
`)

	if _, err := LoadPlan(root, "gamma", nil); err == nil {
		t.Fatal("LoadPlan succeeded, want error")
	}
}

func TestLoadPlanAllowsMultipleJobsForOwnersWithoutRuntimeSecrets(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "src/infrastructure-components/clickhouse/host-install.nomad.hcl", `job "clickhouse-host-install" {}`)
	writeFile(t, root, "src/infrastructure-components/clickhouse/migrations.nomad.hcl", `job "clickhouse-migrations" {}`)

	plan, err := LoadPlan(root, "gamma", []Component{
		{
			Component: "clickhouse-host-install",
			JobID:     "clickhouse-host-install",
			JobSpec:   "src/infrastructure-components/clickhouse/host-install.nomad.hcl",
		},
		{
			Component: "clickhouse-migrations",
			JobID:     "clickhouse-migrations",
			JobSpec:   "src/infrastructure-components/clickhouse/migrations.nomad.hcl",
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Secrets) != 0 {
		t.Fatalf("len(secrets) = %d, want 0", len(plan.Secrets))
	}
	if len(plan.NomadRoles) != 0 {
		t.Fatalf("len(roles) = %d, want 0", len(plan.NomadRoles))
	}
}

func TestLoadPlanRejectsRuntimeSecretsForAmbiguousNomadOwner(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "src/services/billing-service/api.nomad.hcl", `job "billing-api" {}`)
	writeFile(t, root, "src/services/billing-service/worker.nomad.hcl", `job "billing-worker" {}`)
	writeFile(t, root, "src/services/billing-service/deploy/runtime-secrets.yml", `
openbao_runtime_secret_seed_declarations:
  - name: billing-service.stripe.secret_key
    site_secret: stripe_secret_key
`)

	if _, err := LoadPlan(root, "gamma", []Component{
		{
			Component: "billing-api",
			JobID:     "billing-api",
			JobSpec:   "src/services/billing-service/api.nomad.hcl",
		},
		{
			Component: "billing-worker",
			JobID:     "billing-worker",
			JobSpec:   "src/services/billing-service/worker.nomad.hcl",
		},
	}); err == nil {
		t.Fatal("LoadPlan succeeded, want error")
	}
}

func TestLoadPlanMapsAmbiguousOwnerRuntimeSecretWithExplicitJobID(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "src/infrastructure-components/electric/containerd.nomad.hcl", `job "electric-containerd" {}`)
	writeFile(t, root, "src/infrastructure-components/electric/nomad.hcl", `job "electric" {}`)
	writeFile(t, root, "src/infrastructure-components/electric/deploy/runtime-secrets.yml", `
openbao_runtime_secret_seed_declarations:
  - name: electric.pg.password
    job_id: electric
    generated:
      bytes: 32
`)

	plan, err := LoadPlan(root, "gamma", []Component{
		{
			Component: "electric",
			JobID:     "electric-containerd",
			JobSpec:   "src/infrastructure-components/electric/containerd.nomad.hcl",
		},
		{
			Component: "electric",
			JobID:     "electric",
			JobSpec:   "src/infrastructure-components/electric/nomad.hcl",
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Secrets) != 1 {
		t.Fatalf("len(secrets) = %d, want 1", len(plan.Secrets))
	}
	if plan.Secrets[0].JobID != "electric" {
		t.Fatalf("secret JobID = %q, want electric", plan.Secrets[0].JobID)
	}
	if plan.Secrets[0].Generated.Bytes != 32 {
		t.Fatalf("generated bytes = %d, want 32", plan.Secrets[0].Generated.Bytes)
	}
}

func writeFile(t *testing.T, root, rel, body string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}
