agent_address = "/run/spire-agent/sockets/agent.sock"
cert_dir = "/var/lib/otelcol/clickhouse-spiffe"
daemon_mode = true
svid_file_name = "svid.pem"
svid_key_file_name = "svid_key.pem"
svid_bundle_file_name = "bundle.pem"
cert_file_mode = 0640
key_file_mode = 0600
