// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://sandbox.api.verself.sh" | (string & {});
};

export type BillingCancelContractResponse = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  contract: BillingContract;
};

export type BillingContract = {
  cadence_kind: string;
  contract_id: string;
  ends_at?: string;
  entitlement_state: string;
  payment_state: string;
  pending_change_effective_at?: string;
  pending_change_id?: string;
  pending_change_target_plan_id?: string;
  pending_change_type?: string;
  phase_end?: string;
  phase_id: string;
  phase_start?: string;
  plan_id: string;
  product_id: string;
  starts_at: string;
  status: string;
};

export type BillingContracts = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  contracts: Array<BillingContract> | null;
};

export type BillingEntitlementBucketSection = {
  bucket_id: string;
  bucket_slot?: BillingEntitlementSlot;
  display_name: string;
  sku_slots: Array<BillingEntitlementSlot> | null;
};

export type BillingEntitlementProductSection = {
  buckets: Array<BillingEntitlementBucketSection> | null;
  display_name: string;
  product_id: string;
  product_slot?: BillingEntitlementSlot;
};

export type BillingEntitlementSlot = {
  available_units: string;
  bucket_display: string;
  bucket_id: string;
  coverage_label: string;
  pending_units: string;
  period_start_units: string;
  product_display: string;
  product_id: string;
  scope_type: "account" | "product" | "bucket" | "sku";
  sku_display: string;
  sku_id: string;
  sources: Array<BillingEntitlementSourceTotal> | null;
  spent_units: string;
};

export type BillingEntitlementSourceTotal = {
  available_units: string;
  inline_expires_at?: string;
  label: string;
  pending_units: string;
  period_start_units: string;
  plan_id: string;
  source: "free_tier" | "contract" | "purchase" | "promo" | "refund" | "receivable";
};

export type BillingEntitlementsView = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  org_id: string;
  products: Array<BillingEntitlementProductSection> | null;
  universal: BillingEntitlementSlot;
};

export type BillingPlan = {
  active: boolean;
  annual_amount_cents: string;
  billing_mode: string;
  currency: string;
  display_name: string;
  is_default: boolean;
  monthly_amount_cents: string;
  plan_id: string;
  product_id: string;
  tier: string;
};

export type BillingPlans = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  plans: Array<BillingPlan> | null;
};

export type BillingStatement = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  currency: string;
  generated_at: string;
  grant_summaries: Array<BillingStatementGrantSummary> | null;
  line_items: Array<BillingStatementLineItem> | null;
  org_id: string;
  period_end: string;
  period_source: string;
  period_start: string;
  product_id: string;
  totals: BillingStatementTotals;
  unit_label: string;
};

export type BillingStatementGrantSummary = {
  available: string;
  pending: string;
  scope_bucket_id: string;
  scope_product_id: string;
  scope_type: string;
  source: string;
};

export type BillingStatementLineItem = {
  bucket_display_name: string;
  bucket_id: string;
  charge_units: string;
  contract_units: string;
  free_tier_units: string;
  plan_id: string;
  pricing_phase: string;
  product_id: string;
  promo_units: string;
  purchase_units: string;
  quantity: number;
  quantity_unit: string;
  receivable_units: string;
  refund_units: string;
  reserved_units: string;
  sku_display_name: string;
  sku_id: string;
  unit_rate: string;
};

export type BillingStatementTotals = {
  charge_units: string;
  contract_units: string;
  free_tier_units: string;
  promo_units: string;
  purchase_units: string;
  receivable_units: string;
  refund_units: string;
  reserved_units: string;
  total_due_units: string;
};

export type BillingUrlResponse = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  url: string;
};

export type ErrorDetail = {
  /**
   * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
   */
  location?: string;
  /**
   * Error message text
   */
  message?: string;
  /**
   * The value at the given location
   */
  value?: unknown;
};

export type ErrorModel = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * HTTP status code
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
};

export type SandboxAnalyticsBucket = {
  billed_charge_units?: string;
  count: string;
  key: string;
  reserved_charge_units?: string;
  writeoff_charge_units?: string;
};

export type SandboxAttemptRecord = {
  attempt_id: string;
  attempt_seq: number;
  billing_job_id?: number;
  block_read_bytes?: number;
  block_write_bytes?: number;
  boot_time_us?: number;
  completed_at?: string;
  created_at: string;
  duration_ms?: number;
  exec_id?: string;
  exit_code?: number;
  failure_reason?: string;
  lease_id?: string;
  net_rx_bytes?: number;
  net_tx_bytes?: number;
  rootfs_provisioned_bytes?: number;
  started_at?: string;
  state: string;
  stderr_bytes?: number;
  stdout_bytes?: number;
  trace_id?: string;
  updated_at: string;
  vcpu_exit_count?: number;
  zfs_written?: number;
};

export type SandboxBillingCheckoutRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Amount in cents
   */
  amount_cents: number;
  cancel_url: string;
  /**
   * Product context for checkout display and metadata; purchased top-ups are account-scoped
   */
  product_id: string;
  success_url: string;
};

export type SandboxBillingContractChangeRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  cancel_url: string;
  success_url: string;
  /**
   * Plan to upgrade into immediately
   */
  target_plan_id: string;
};

export type SandboxBillingContractRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Billing cadence (default monthly)
   */
  cadence?: "monthly";
  cancel_url: string;
  /**
   * Plan to activate
   */
  plan_id: string;
  success_url: string;
};

export type SandboxBillingPortalRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  return_url: string;
};

export type SandboxBillingWindow = {
  actual_quantity?: number;
  attempt_id: string;
  billed_charge_units: string;
  billing_window_id: string;
  cost_per_unit: string;
  created_at: string;
  pricing_phase?: string;
  reservation_shape: string;
  reserved_charge_units: string;
  reserved_quantity: number;
  settled_at?: string;
  state: string;
  window_seq: number;
  window_start: string;
  writeoff_charge_units: string;
};

export type SandboxCachesAnalytics = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  by_repository: Array<SandboxAnalyticsBucket> | null;
  checkout_hits: string;
  checkout_misses: string;
  checkout_requests: string;
  sticky_commits: string;
  sticky_restore_hits: string;
  sticky_restore_misses: string;
  sticky_save_requests: string;
  window_end: string;
  window_start: string;
};

export type SandboxCostsAnalytics = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  billed_charge_units: string;
  by_repository: Array<SandboxAnalyticsBucket> | null;
  by_runner_class: Array<SandboxAnalyticsBucket> | null;
  by_source: Array<SandboxAnalyticsBucket> | null;
  reserved_charge_units: string;
  window_end: string;
  window_start: string;
  writeoff_charge_units: string;
};

export type SandboxExecutionLogs = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  attempt_id: string;
  execution_id: string;
  logs: string;
};

export type SandboxExecutionRecord = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  actor_id: string;
  billing_summary?: SandboxRunBillingSummary;
  billing_windows?: Array<SandboxBillingWindow> | null;
  correlation_id?: string;
  created_at: string;
  execution_id: string;
  external_provider?: string;
  external_task_id?: string;
  idempotency_key?: string;
  kind: string;
  latest_attempt: SandboxAttemptRecord;
  org_id: string;
  product_id: string;
  provider?: string;
  run_command?: string;
  run_id: string;
  runner?: SandboxRunnerRunMetadata;
  runner_class?: string;
  schedule?: SandboxScheduleRunMetadata;
  source_kind?: string;
  source_ref?: string;
  status: string;
  sticky_disk_mounts?: Array<SandboxExecutionStickyDiskMount> | null;
  updated_at: string;
  workload_kind?: string;
};

export type SandboxExecutionScheduleCreateRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  display_name?: string;
  idempotency_key: string;
  inputs?: {
    [key: string]: string;
  };
  interval_seconds: number;
  paused?: boolean;
  project_id: string;
  ref?: string;
  source_repository_id: string;
  workflow_path: string;
};

export type SandboxExecutionScheduleDispatchRecord = {
  created_at: string;
  dispatch_id: string;
  failure_reason?: string;
  schedule_id: string;
  scheduled_at: string;
  source_workflow_run_id?: string;
  state: string;
  submitted_at?: string;
  temporal_run_id: string;
  temporal_workflow_id: string;
  updated_at: string;
  workflow_state?: string;
};

export type SandboxExecutionScheduleRecord = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  actor_id: string;
  created_at: string;
  dispatches?: Array<SandboxExecutionScheduleDispatchRecord> | null;
  display_name?: string;
  idempotency_key?: string;
  inputs?: {
    [key: string]: string;
  };
  interval_seconds: number;
  org_id: string;
  project_id: string;
  ref?: string;
  schedule_id: string;
  source_repository_id: string;
  state: string;
  task_queue: string;
  temporal_namespace: string;
  temporal_schedule_id: string;
  updated_at: string;
  workflow_path: string;
};

export type SandboxExecutionStickyDiskMount = {
  base_generation: string;
  committed_generation: string;
  completed_at?: string;
  failure_reason?: string;
  key_hash: string;
  mount_id: string;
  mount_name: string;
  mount_path: string;
  requested_at?: string;
  save_requested: boolean;
  save_state: string;
};

export type SandboxGitHubInstallationConnectResponse = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * Time after which the setup URL state is no longer accepted.
   */
  expires_at: string;
  /**
   * GitHub App installation URL for the current Verself organization.
   */
  setup_url: string;
  /**
   * Opaque installation state token embedded in the GitHub App setup URL.
   */
  state: string;
};

export type SandboxGitHubInstallationRecord = {
  account_login: string;
  account_type: string;
  active: boolean;
  created_at: string;
  /**
   * GitHub App installation ID encoded as a string for JavaScript-safe transport.
   */
  installation_id: string;
  org_id: string;
  updated_at: string;
};

export type SandboxJobsAnalytics = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  by_runner_class: Array<SandboxAnalyticsBucket> | null;
  by_source: Array<SandboxAnalyticsBucket> | null;
  failed_runs: string;
  p50_duration_ms: string;
  p95_duration_ms: string;
  p99_duration_ms: string;
  slowest_runs: Array<SandboxRunDurationSample> | null;
  succeeded_runs: string;
  total_runs: string;
  window_end: string;
  window_start: string;
};

export type SandboxRunBillingSummary = {
  billed_charge_units: string;
  cost_per_unit: string;
  pricing_phase?: string;
  reserved_charge_units: string;
  window_count: number;
  writeoff_charge_units: string;
};

export type SandboxRunDurationSample = {
  completed_at: string;
  duration_ms: number;
  execution_id: string;
  job_name?: string;
  repository_full_name?: string;
  runner_class?: string;
  status: string;
  workflow_name?: string;
};

export type SandboxRunLogSearchFilters = {
  attempt_id?: string;
  branch?: string;
  query?: string;
  repository?: string;
  run_id?: string;
  runner_class?: string;
  source_kind?: string;
  workflow?: string;
};

export type SandboxRunLogSearchPage = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  filters: SandboxRunLogSearchFilters;
  limit: number;
  next_cursor?: string;
  results: Array<SandboxRunLogSearchResult> | null;
};

export type SandboxRunLogSearchResult = {
  attempt_id: string;
  chunk: string;
  created_at: string;
  execution_id: string;
  head_branch?: string;
  job_name?: string;
  repository_full_name?: string;
  runner_class?: string;
  schedule_id?: string;
  seq: number;
  source_kind?: string;
  stream: string;
  workflow_name?: string;
  workload_kind?: string;
};

export type SandboxRunnerRunMetadata = {
  head_branch?: string;
  head_sha?: string;
  job_name?: string;
  provider_installation_id?: string;
  provider_job_id?: string;
  provider_run_id?: string;
  repository_full_name?: string;
  workflow_name?: string;
};

export type SandboxRunnerSizingAnalytics = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  by_runner_class: Array<SandboxRunnerSizingSample> | null;
  window_end: string;
  window_start: string;
};

export type SandboxRunnerSizingSample = {
  avg_block_write_bytes: string;
  avg_boot_time_us: string;
  avg_net_tx_bytes: string;
  avg_rootfs_provisioned_bytes: string;
  p95_duration_ms: string;
  run_count: string;
  runner_class: string;
};

export type SandboxRunsFilters = {
  branch?: string;
  repository?: string;
  runner_class?: string;
  source_kind?: string;
  status?: string;
  workflow?: string;
};

export type SandboxRunsPage = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  filters: SandboxRunsFilters;
  limit: number;
  next_cursor?: string;
  runs: Array<SandboxExecutionRecord> | null;
};

export type SandboxScheduleRunMetadata = {
  display_name?: string;
  schedule_id?: string;
  temporal_run_id?: string;
  temporal_workflow_id?: string;
};

export type SandboxStickyDiskFilters = {
  repository?: string;
};

export type SandboxStickyDiskRecord = {
  current_generation: string;
  current_source_ref: string;
  installation_id: string;
  key: string;
  key_hash: string;
  last_attempt_id?: string;
  last_completed_at?: string;
  last_execution_id?: string;
  last_job_name?: string;
  last_mount_path?: string;
  last_runner_class?: string;
  last_save_state?: string;
  last_used_at?: string;
  last_workflow_name?: string;
  repository_full_name?: string;
  repository_id: string;
};

export type SandboxStickyDiskResetResult = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  deleted_source_ref?: string;
  installation_id: string;
  key_hash: string;
  repository_id: string;
  reset_at: string;
};

export type SandboxStickyDisksPage = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  disks: Array<SandboxStickyDiskRecord> | null;
  filters: SandboxStickyDiskFilters;
  limit: number;
  next_cursor?: string;
};

export type StickyDiskResetRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * GitHub installation ID encoded as a decimal string.
   */
  installation_id: string;
  /**
   * Sticky disk key hash to reset.
   */
  key_hash: string;
  /**
   * GitHub repository ID encoded as a decimal string.
   */
  repository_id: string;
};

export type BillingCancelContractResponseWritable = {
  contract: BillingContract;
};

export type BillingContractsWritable = {
  contracts: Array<BillingContract> | null;
};

export type BillingEntitlementsViewWritable = {
  org_id: string;
  products: Array<BillingEntitlementProductSection> | null;
  universal: BillingEntitlementSlot;
};

export type BillingPlansWritable = {
  plans: Array<BillingPlan> | null;
};

export type BillingStatementWritable = {
  currency: string;
  generated_at: string;
  grant_summaries: Array<BillingStatementGrantSummary> | null;
  line_items: Array<BillingStatementLineItem> | null;
  org_id: string;
  period_end: string;
  period_source: string;
  period_start: string;
  product_id: string;
  totals: BillingStatementTotals;
  unit_label: string;
};

export type BillingUrlResponseWritable = {
  url: string;
};

export type ErrorModelWritable = {
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * HTTP status code
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
};

export type SandboxBillingCheckoutRequestWritable = {
  /**
   * Amount in cents
   */
  amount_cents: number;
  cancel_url: string;
  /**
   * Product context for checkout display and metadata; purchased top-ups are account-scoped
   */
  product_id: string;
  success_url: string;
};

export type SandboxBillingContractChangeRequestWritable = {
  cancel_url: string;
  success_url: string;
  /**
   * Plan to upgrade into immediately
   */
  target_plan_id: string;
};

export type SandboxBillingContractRequestWritable = {
  /**
   * Billing cadence (default monthly)
   */
  cadence?: "monthly";
  cancel_url: string;
  /**
   * Plan to activate
   */
  plan_id: string;
  success_url: string;
};

export type SandboxBillingPortalRequestWritable = {
  return_url: string;
};

export type SandboxCachesAnalyticsWritable = {
  by_repository: Array<SandboxAnalyticsBucket> | null;
  checkout_hits: string;
  checkout_misses: string;
  checkout_requests: string;
  sticky_commits: string;
  sticky_restore_hits: string;
  sticky_restore_misses: string;
  sticky_save_requests: string;
  window_end: string;
  window_start: string;
};

export type SandboxCostsAnalyticsWritable = {
  billed_charge_units: string;
  by_repository: Array<SandboxAnalyticsBucket> | null;
  by_runner_class: Array<SandboxAnalyticsBucket> | null;
  by_source: Array<SandboxAnalyticsBucket> | null;
  reserved_charge_units: string;
  window_end: string;
  window_start: string;
  writeoff_charge_units: string;
};

export type SandboxExecutionLogsWritable = {
  attempt_id: string;
  execution_id: string;
  logs: string;
};

export type SandboxExecutionRecordWritable = {
  actor_id: string;
  billing_summary?: SandboxRunBillingSummary;
  billing_windows?: Array<SandboxBillingWindow> | null;
  correlation_id?: string;
  created_at: string;
  execution_id: string;
  external_provider?: string;
  external_task_id?: string;
  idempotency_key?: string;
  kind: string;
  latest_attempt: SandboxAttemptRecord;
  org_id: string;
  product_id: string;
  provider?: string;
  run_command?: string;
  run_id: string;
  runner?: SandboxRunnerRunMetadata;
  runner_class?: string;
  schedule?: SandboxScheduleRunMetadata;
  source_kind?: string;
  source_ref?: string;
  status: string;
  sticky_disk_mounts?: Array<SandboxExecutionStickyDiskMount> | null;
  updated_at: string;
  workload_kind?: string;
};

export type SandboxExecutionScheduleCreateRequestWritable = {
  display_name?: string;
  idempotency_key: string;
  inputs?: {
    [key: string]: string;
  };
  interval_seconds: number;
  paused?: boolean;
  project_id: string;
  ref?: string;
  source_repository_id: string;
  workflow_path: string;
};

export type SandboxExecutionScheduleRecordWritable = {
  actor_id: string;
  created_at: string;
  dispatches?: Array<SandboxExecutionScheduleDispatchRecord> | null;
  display_name?: string;
  idempotency_key?: string;
  inputs?: {
    [key: string]: string;
  };
  interval_seconds: number;
  org_id: string;
  project_id: string;
  ref?: string;
  schedule_id: string;
  source_repository_id: string;
  state: string;
  task_queue: string;
  temporal_namespace: string;
  temporal_schedule_id: string;
  updated_at: string;
  workflow_path: string;
};

export type SandboxGitHubInstallationConnectResponseWritable = {
  /**
   * Time after which the setup URL state is no longer accepted.
   */
  expires_at: string;
  /**
   * GitHub App installation URL for the current Verself organization.
   */
  setup_url: string;
  /**
   * Opaque installation state token embedded in the GitHub App setup URL.
   */
  state: string;
};

export type SandboxJobsAnalyticsWritable = {
  by_runner_class: Array<SandboxAnalyticsBucket> | null;
  by_source: Array<SandboxAnalyticsBucket> | null;
  failed_runs: string;
  p50_duration_ms: string;
  p95_duration_ms: string;
  p99_duration_ms: string;
  slowest_runs: Array<SandboxRunDurationSample> | null;
  succeeded_runs: string;
  total_runs: string;
  window_end: string;
  window_start: string;
};

export type SandboxRunLogSearchPageWritable = {
  filters: SandboxRunLogSearchFilters;
  limit: number;
  next_cursor?: string;
  results: Array<SandboxRunLogSearchResult> | null;
};

export type SandboxRunnerSizingAnalyticsWritable = {
  by_runner_class: Array<SandboxRunnerSizingSample> | null;
  window_end: string;
  window_start: string;
};

export type SandboxRunsPageWritable = {
  filters: SandboxRunsFilters;
  limit: number;
  next_cursor?: string;
  runs: Array<SandboxExecutionRecordWritable> | null;
};

export type SandboxStickyDiskResetResultWritable = {
  deleted_source_ref?: string;
  installation_id: string;
  key_hash: string;
  repository_id: string;
  reset_at: string;
};

export type SandboxStickyDisksPageWritable = {
  disks: Array<SandboxStickyDiskRecord> | null;
  filters: SandboxStickyDiskFilters;
  limit: number;
  next_cursor?: string;
};

export type StickyDiskResetRequestWritable = {
  /**
   * GitHub installation ID encoded as a decimal string.
   */
  installation_id: string;
  /**
   * Sticky disk key hash to reset.
   */
  key_hash: string;
  /**
   * GitHub repository ID encoded as a decimal string.
   */
  repository_id: string;
};

export type CreateBillingCheckoutData = {
  body: SandboxBillingCheckoutRequestWritable;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path?: never;
  query?: never;
  url: "/api/v1/billing/checkout";
};

export type CreateBillingCheckoutErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CreateBillingCheckoutError =
  CreateBillingCheckoutErrors[keyof CreateBillingCheckoutErrors];

export type CreateBillingCheckoutResponses = {
  /**
   * OK
   */
  200: BillingUrlResponse;
};

export type CreateBillingCheckoutResponse =
  CreateBillingCheckoutResponses[keyof CreateBillingCheckoutResponses];

export type ListBillingContractsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/billing/contracts";
};

export type ListBillingContractsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ListBillingContractsError =
  ListBillingContractsErrors[keyof ListBillingContractsErrors];

export type ListBillingContractsResponses = {
  /**
   * OK
   */
  200: BillingContracts;
};

export type ListBillingContractsResponse =
  ListBillingContractsResponses[keyof ListBillingContractsResponses];

export type CreateBillingContractData = {
  body: SandboxBillingContractRequestWritable;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path?: never;
  query?: never;
  url: "/api/v1/billing/contracts";
};

export type CreateBillingContractErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CreateBillingContractError =
  CreateBillingContractErrors[keyof CreateBillingContractErrors];

export type CreateBillingContractResponses = {
  /**
   * OK
   */
  200: BillingUrlResponse;
};

export type CreateBillingContractResponse =
  CreateBillingContractResponses[keyof CreateBillingContractResponses];

export type CancelBillingContractData = {
  body?: never;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path: {
    contract_id: string;
  };
  query?: never;
  url: "/api/v1/billing/contracts/{contract_id}/cancel";
};

export type CancelBillingContractErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CancelBillingContractError =
  CancelBillingContractErrors[keyof CancelBillingContractErrors];

export type CancelBillingContractResponses = {
  /**
   * OK
   */
  200: BillingCancelContractResponse;
};

export type CancelBillingContractResponse =
  CancelBillingContractResponses[keyof CancelBillingContractResponses];

export type CreateBillingContractChangeData = {
  body: SandboxBillingContractChangeRequestWritable;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path: {
    contract_id: string;
  };
  query?: never;
  url: "/api/v1/billing/contracts/{contract_id}/changes";
};

export type CreateBillingContractChangeErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CreateBillingContractChangeError =
  CreateBillingContractChangeErrors[keyof CreateBillingContractChangeErrors];

export type CreateBillingContractChangeResponses = {
  /**
   * OK
   */
  200: BillingUrlResponse;
};

export type CreateBillingContractChangeResponse =
  CreateBillingContractChangeResponses[keyof CreateBillingContractChangeResponses];

export type GetBillingEntitlementsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/billing/entitlements";
};

export type GetBillingEntitlementsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetBillingEntitlementsError =
  GetBillingEntitlementsErrors[keyof GetBillingEntitlementsErrors];

export type GetBillingEntitlementsResponses = {
  /**
   * OK
   */
  200: BillingEntitlementsView;
};

export type GetBillingEntitlementsResponse =
  GetBillingEntitlementsResponses[keyof GetBillingEntitlementsResponses];

export type ListBillingPlansData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/billing/plans";
};

export type ListBillingPlansErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ListBillingPlansError = ListBillingPlansErrors[keyof ListBillingPlansErrors];

export type ListBillingPlansResponses = {
  /**
   * OK
   */
  200: BillingPlans;
};

export type ListBillingPlansResponse = ListBillingPlansResponses[keyof ListBillingPlansResponses];

export type CreateBillingPortalData = {
  body: SandboxBillingPortalRequestWritable;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path?: never;
  query?: never;
  url: "/api/v1/billing/portal";
};

export type CreateBillingPortalErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CreateBillingPortalError = CreateBillingPortalErrors[keyof CreateBillingPortalErrors];

export type CreateBillingPortalResponses = {
  /**
   * OK
   */
  200: BillingUrlResponse;
};

export type CreateBillingPortalResponse =
  CreateBillingPortalResponses[keyof CreateBillingPortalResponses];

export type GetBillingStatementData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Product to preview
     */
    product_id: string;
  };
  url: "/api/v1/billing/statement";
};

export type GetBillingStatementErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetBillingStatementError = GetBillingStatementErrors[keyof GetBillingStatementErrors];

export type GetBillingStatementResponses = {
  /**
   * OK
   */
  200: BillingStatement;
};

export type GetBillingStatementResponse =
  GetBillingStatementResponses[keyof GetBillingStatementResponses];

export type ListExecutionSchedulesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/execution-schedules";
};

export type ListExecutionSchedulesErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ListExecutionSchedulesError =
  ListExecutionSchedulesErrors[keyof ListExecutionSchedulesErrors];

export type ListExecutionSchedulesResponses = {
  /**
   * OK
   */
  200: Array<SandboxExecutionScheduleRecord> | null;
};

export type ListExecutionSchedulesResponse =
  ListExecutionSchedulesResponses[keyof ListExecutionSchedulesResponses];

export type CreateExecutionScheduleData = {
  body: SandboxExecutionScheduleCreateRequestWritable;
  path?: never;
  query?: never;
  url: "/api/v1/execution-schedules";
};

export type CreateExecutionScheduleErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CreateExecutionScheduleError =
  CreateExecutionScheduleErrors[keyof CreateExecutionScheduleErrors];

export type CreateExecutionScheduleResponses = {
  /**
   * Created
   */
  201: SandboxExecutionScheduleRecord;
};

export type CreateExecutionScheduleResponse =
  CreateExecutionScheduleResponses[keyof CreateExecutionScheduleResponses];

export type GetExecutionScheduleData = {
  body?: never;
  path: {
    /**
     * Execution schedule UUID
     */
    schedule_id: string;
  };
  query?: never;
  url: "/api/v1/execution-schedules/{schedule_id}";
};

export type GetExecutionScheduleErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetExecutionScheduleError =
  GetExecutionScheduleErrors[keyof GetExecutionScheduleErrors];

export type GetExecutionScheduleResponses = {
  /**
   * OK
   */
  200: SandboxExecutionScheduleRecord;
};

export type GetExecutionScheduleResponse =
  GetExecutionScheduleResponses[keyof GetExecutionScheduleResponses];

export type PauseExecutionScheduleData = {
  body?: never;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path: {
    /**
     * Execution schedule UUID
     */
    schedule_id: string;
  };
  query?: never;
  url: "/api/v1/execution-schedules/{schedule_id}/pause";
};

export type PauseExecutionScheduleErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type PauseExecutionScheduleError =
  PauseExecutionScheduleErrors[keyof PauseExecutionScheduleErrors];

export type PauseExecutionScheduleResponses = {
  /**
   * OK
   */
  200: SandboxExecutionScheduleRecord;
};

export type PauseExecutionScheduleResponse =
  PauseExecutionScheduleResponses[keyof PauseExecutionScheduleResponses];

export type ResumeExecutionScheduleData = {
  body?: never;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path: {
    /**
     * Execution schedule UUID
     */
    schedule_id: string;
  };
  query?: never;
  url: "/api/v1/execution-schedules/{schedule_id}/resume";
};

export type ResumeExecutionScheduleErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ResumeExecutionScheduleError =
  ResumeExecutionScheduleErrors[keyof ResumeExecutionScheduleErrors];

export type ResumeExecutionScheduleResponses = {
  /**
   * OK
   */
  200: SandboxExecutionScheduleRecord;
};

export type ResumeExecutionScheduleResponse =
  ResumeExecutionScheduleResponses[keyof ResumeExecutionScheduleResponses];

export type GetExecutionData = {
  body?: never;
  path: {
    /**
     * Execution UUID
     */
    execution_id: string;
  };
  query?: never;
  url: "/api/v1/executions/{execution_id}";
};

export type GetExecutionErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetExecutionError = GetExecutionErrors[keyof GetExecutionErrors];

export type GetExecutionResponses = {
  /**
   * OK
   */
  200: SandboxExecutionRecord;
};

export type GetExecutionResponse = GetExecutionResponses[keyof GetExecutionResponses];

export type GetExecutionLogsData = {
  body?: never;
  path: {
    /**
     * Execution UUID
     */
    execution_id: string;
  };
  query?: never;
  url: "/api/v1/executions/{execution_id}/logs";
};

export type GetExecutionLogsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetExecutionLogsError = GetExecutionLogsErrors[keyof GetExecutionLogsErrors];

export type GetExecutionLogsResponses = {
  /**
   * OK
   */
  200: SandboxExecutionLogs;
};

export type GetExecutionLogsResponse = GetExecutionLogsResponses[keyof GetExecutionLogsResponses];

export type ListGithubInstallationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/github/installations";
};

export type ListGithubInstallationsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ListGithubInstallationsError =
  ListGithubInstallationsErrors[keyof ListGithubInstallationsErrors];

export type ListGithubInstallationsResponses = {
  /**
   * OK
   */
  200: Array<SandboxGitHubInstallationRecord> | null;
};

export type ListGithubInstallationsResponse =
  ListGithubInstallationsResponses[keyof ListGithubInstallationsResponses];

export type BeginGithubInstallationData = {
  body?: never;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path?: never;
  query?: never;
  url: "/api/v1/github/installations/connect";
};

export type BeginGithubInstallationErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type BeginGithubInstallationError =
  BeginGithubInstallationErrors[keyof BeginGithubInstallationErrors];

export type BeginGithubInstallationResponses = {
  /**
   * Created
   */
  201: SandboxGitHubInstallationConnectResponse;
};

export type BeginGithubInstallationResponse =
  BeginGithubInstallationResponses[keyof BeginGithubInstallationResponses];

export type GetCachesAnalyticsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Inclusive RFC3339 window start.
     */
    start?: string;
    /**
     * Inclusive RFC3339 window end.
     */
    end?: string;
  };
  url: "/api/v1/run-analytics/caches";
};

export type GetCachesAnalyticsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetCachesAnalyticsError = GetCachesAnalyticsErrors[keyof GetCachesAnalyticsErrors];

export type GetCachesAnalyticsResponses = {
  /**
   * OK
   */
  200: SandboxCachesAnalytics;
};

export type GetCachesAnalyticsResponse =
  GetCachesAnalyticsResponses[keyof GetCachesAnalyticsResponses];

export type GetCostsAnalyticsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Inclusive RFC3339 window start.
     */
    start?: string;
    /**
     * Inclusive RFC3339 window end.
     */
    end?: string;
  };
  url: "/api/v1/run-analytics/costs";
};

export type GetCostsAnalyticsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetCostsAnalyticsError = GetCostsAnalyticsErrors[keyof GetCostsAnalyticsErrors];

export type GetCostsAnalyticsResponses = {
  /**
   * OK
   */
  200: SandboxCostsAnalytics;
};

export type GetCostsAnalyticsResponse =
  GetCostsAnalyticsResponses[keyof GetCostsAnalyticsResponses];

export type GetJobsAnalyticsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Inclusive RFC3339 window start.
     */
    start?: string;
    /**
     * Inclusive RFC3339 window end.
     */
    end?: string;
  };
  url: "/api/v1/run-analytics/jobs";
};

export type GetJobsAnalyticsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetJobsAnalyticsError = GetJobsAnalyticsErrors[keyof GetJobsAnalyticsErrors];

export type GetJobsAnalyticsResponses = {
  /**
   * OK
   */
  200: SandboxJobsAnalytics;
};

export type GetJobsAnalyticsResponse = GetJobsAnalyticsResponses[keyof GetJobsAnalyticsResponses];

export type GetRunnerSizingAnalyticsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Inclusive RFC3339 window start.
     */
    start?: string;
    /**
     * Inclusive RFC3339 window end.
     */
    end?: string;
  };
  url: "/api/v1/run-analytics/runner-sizing";
};

export type GetRunnerSizingAnalyticsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetRunnerSizingAnalyticsError =
  GetRunnerSizingAnalyticsErrors[keyof GetRunnerSizingAnalyticsErrors];

export type GetRunnerSizingAnalyticsResponses = {
  /**
   * OK
   */
  200: SandboxRunnerSizingAnalytics;
};

export type GetRunnerSizingAnalyticsResponse =
  GetRunnerSizingAnalyticsResponses[keyof GetRunnerSizingAnalyticsResponses];

export type SearchRunLogsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum log matches to return.
     */
    limit?: number;
    /**
     * Opaque pagination cursor returned by the previous page.
     */
    cursor?: string;
    /**
     * Case-insensitive substring to search for.
     */
    query?: string;
    /**
     * Filter to a specific run UUID.
     */
    run_id?: string;
    /**
     * Filter to a specific attempt UUID.
     */
    attempt_id?: string;
    source_kind?: string;
    repository?: string;
    workflow?: string;
    branch?: string;
    runner_class?: string;
  };
  url: "/api/v1/run-logs/search";
};

export type SearchRunLogsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type SearchRunLogsError = SearchRunLogsErrors[keyof SearchRunLogsErrors];

export type SearchRunLogsResponses = {
  /**
   * OK
   */
  200: SandboxRunLogSearchPage;
};

export type SearchRunLogsResponse = SearchRunLogsResponses[keyof SearchRunLogsResponses];

export type ListRunsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum runs to return.
     */
    limit?: number;
    /**
     * Opaque pagination cursor returned by the previous page.
     */
    cursor?: string;
    source_kind?: string;
    status?: string;
    repository?: string;
    workflow?: string;
    branch?: string;
    runner_class?: string;
  };
  url: "/api/v1/runs";
};

export type ListRunsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ListRunsError = ListRunsErrors[keyof ListRunsErrors];

export type ListRunsResponses = {
  /**
   * OK
   */
  200: SandboxRunsPage;
};

export type ListRunsResponse = ListRunsResponses[keyof ListRunsResponses];

export type GetRunData = {
  body?: never;
  path: {
    /**
     * Run UUID
     */
    run_id: string;
  };
  query?: never;
  url: "/api/v1/runs/{run_id}";
};

export type GetRunErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetRunError = GetRunErrors[keyof GetRunErrors];

export type GetRunResponses = {
  /**
   * OK
   */
  200: SandboxExecutionRecord;
};

export type GetRunResponse = GetRunResponses[keyof GetRunResponses];

export type ListStickyDisksData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Maximum sticky disks to return.
     */
    limit?: number;
    /**
     * Opaque pagination cursor returned by the previous page.
     */
    cursor?: string;
    repository?: string;
  };
  url: "/api/v1/sticky-disks";
};

export type ListStickyDisksErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ListStickyDisksError = ListStickyDisksErrors[keyof ListStickyDisksErrors];

export type ListStickyDisksResponses = {
  /**
   * OK
   */
  200: SandboxStickyDisksPage;
};

export type ListStickyDisksResponse = ListStickyDisksResponses[keyof ListStickyDisksResponses];

export type ResetStickyDiskData = {
  body: StickyDiskResetRequestWritable;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path?: never;
  query?: never;
  url: "/api/v1/sticky-disks/reset";
};

export type ResetStickyDiskErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ResetStickyDiskError = ResetStickyDiskErrors[keyof ResetStickyDiskErrors];

export type ResetStickyDiskResponses = {
  /**
   * OK
   */
  200: SandboxStickyDiskResetResult;
};

export type ResetStickyDiskResponse = ResetStickyDiskResponses[keyof ResetStickyDiskResponses];
