// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

import * as v from "valibot";

export const vErrorDetail = v.strictObject({
  location: v.optional(v.string()),
  message: v.optional(v.string()),
  value: v.optional(v.unknown()),
});

export const vErrorModel = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  detail: v.optional(v.string()),
  errors: v.optional(v.array(vErrorDetail)),
  instance: v.optional(v.pipe(v.string(), v.url())),
  status: v.optional(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(
        BigInt("-9223372036854775808"),
        "Invalid value: Expected int64 to be >= -9223372036854775808",
      ),
      v.maxValue(BigInt(599)),
    ),
  ),
  title: v.optional(v.string()),
  type: v.optional(v.pipe(v.string(), v.url()), "about:blank"),
});

export const vGovernanceAuditEvent = v.strictObject({
  action: v.string(),
  audit_event: v.string(),
  client_ip: v.optional(v.string()),
  content_sha256: v.string(),
  error_code: v.optional(v.string()),
  error_message: v.optional(v.string()),
  event_id: v.string(),
  idempotency_key_hash: v.optional(v.string()),
  operation_id: v.string(),
  org_id: v.string(),
  org_scope: v.string(),
  permission: v.string(),
  prev_hmac: v.string(),
  principal_email: v.optional(v.string()),
  principal_id: v.string(),
  principal_type: v.string(),
  rate_limit_class: v.optional(v.string()),
  recorded_at: v.pipe(v.string(), v.isoTimestamp()),
  request_id: v.optional(v.string()),
  resource_id: v.optional(v.string()),
  resource_kind: v.string(),
  result: v.string(),
  row_hmac: v.string(),
  sequence: v.string(),
  service_name: v.string(),
  trace_id: v.optional(v.string()),
});

export const vGovernanceAuditFilters = v.strictObject({
  operation_id: v.optional(v.string()),
  result: v.optional(v.string()),
  service_name: v.optional(v.string()),
});

export const vGovernanceAuditEvents = v.strictObject({
  $schema: v.optional(v.string()),
  events: v.array(vGovernanceAuditEvent),
  filters: vGovernanceAuditFilters,
  limit: v.pipe(
    v.number(),
    v.integer(),
    v.minValue(-2147483648, "Invalid value: Expected int32 to be >= -2147483648"),
    v.maxValue(2147483647, "Invalid value: Expected int32 to be <= 2147483647"),
  ),
  next_cursor: v.optional(v.string()),
});

export const vGovernanceCreateExportRequest = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  include_logs: v.optional(v.boolean()),
  scopes: v.optional(v.array(v.string())),
});

export const vGovernanceExportFile = v.strictObject({
  bytes: v.string(),
  content_type: v.string(),
  path: v.string(),
  rows: v.string(),
  sha256: v.string(),
});

export const vGovernanceExportJob = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  artifact_bytes: v.string(),
  artifact_sha256: v.optional(v.string()),
  completed_at: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  created_at: v.pipe(v.string(), v.isoTimestamp()),
  download_url: v.optional(v.string()),
  error_code: v.optional(v.string()),
  error_message: v.optional(v.string()),
  expires_at: v.pipe(v.string(), v.isoTimestamp()),
  export_id: v.string(),
  files: v.array(vGovernanceExportFile),
  format: v.string(),
  include_logs: v.boolean(),
  org_id: v.string(),
  requested_by: v.string(),
  scopes: v.array(v.string()),
  state: v.string(),
  updated_at: v.pipe(v.string(), v.isoTimestamp()),
});

export const vGovernanceExportJobs = v.strictObject({
  $schema: v.optional(v.string()),
  exports: v.array(vGovernanceExportJob),
});

export const vErrorModelWritable = v.strictObject({
  detail: v.optional(v.string()),
  errors: v.optional(v.array(vErrorDetail)),
  instance: v.optional(v.pipe(v.string(), v.url())),
  status: v.optional(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(
        BigInt("-9223372036854775808"),
        "Invalid value: Expected int64 to be >= -9223372036854775808",
      ),
      v.maxValue(BigInt(599)),
    ),
  ),
  title: v.optional(v.string()),
  type: v.optional(v.pipe(v.string(), v.url()), "about:blank"),
});

export const vGovernanceCreateExportRequestWritable = v.strictObject({
  include_logs: v.optional(v.boolean()),
  scopes: v.optional(v.array(v.string())),
});

export const vGovernanceExportJobWritable = v.strictObject({
  artifact_bytes: v.string(),
  artifact_sha256: v.optional(v.string()),
  completed_at: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  created_at: v.pipe(v.string(), v.isoTimestamp()),
  download_url: v.optional(v.string()),
  error_code: v.optional(v.string()),
  error_message: v.optional(v.string()),
  expires_at: v.pipe(v.string(), v.isoTimestamp()),
  export_id: v.string(),
  files: v.array(vGovernanceExportFile),
  format: v.string(),
  include_logs: v.boolean(),
  org_id: v.string(),
  requested_by: v.string(),
  scopes: v.array(v.string()),
  state: v.string(),
  updated_at: v.pipe(v.string(), v.isoTimestamp()),
});

export const vGovernanceExportJobsWritable = v.strictObject({
  $schema: v.optional(v.string()),
  exports: v.array(vGovernanceExportJobWritable),
});

export const vListAuditEventsQuery = v.object({
  limit: v.optional(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(BigInt(1)),
      v.maxValue(BigInt(200)),
    ),
  ),
  cursor: v.optional(v.pipe(v.string(), v.maxLength(1024))),
  service_name: v.optional(v.pipe(v.string(), v.maxLength(128))),
  operation_id: v.optional(v.pipe(v.string(), v.maxLength(128))),
  result: v.optional(v.picklist(["allowed", "denied", "error"])),
});

/**
 * OK
 */
export const vListAuditEventsResponse = vGovernanceAuditEvents;

/**
 * OK
 */
export const vListDataExportsResponse = vGovernanceExportJobs;

export const vCreateDataExportBody = vGovernanceCreateExportRequestWritable;

export const vCreateDataExportHeaders = v.object({
  "Idempotency-Key": v.pipe(v.string(), v.minLength(1), v.maxLength(128)),
});

/**
 * Created
 */
export const vCreateDataExportResponse = vGovernanceExportJob;

export const vGetDataExportPath = v.object({
  export_id: v.pipe(v.string(), v.uuid()),
});

/**
 * OK
 */
export const vGetDataExportResponse = vGovernanceExportJob;

export const vDownloadDataExportPath = v.object({
  export_id: v.pipe(v.string(), v.uuid()),
});

/**
 * tar.gz export artifact
 */
export const vDownloadDataExportResponse = v.string();
