// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: src/substrate/vm-orchestrator/proto/v1/vm_service.proto

package vmrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VMService_AcquireLease_FullMethodName          = "/verself.vm_orchestrator.v1.VMService/AcquireLease"
	VMService_RenewLease_FullMethodName            = "/verself.vm_orchestrator.v1.VMService/RenewLease"
	VMService_ReleaseLease_FullMethodName          = "/verself.vm_orchestrator.v1.VMService/ReleaseLease"
	VMService_GetLease_FullMethodName              = "/verself.vm_orchestrator.v1.VMService/GetLease"
	VMService_ListLeases_FullMethodName            = "/verself.vm_orchestrator.v1.VMService/ListLeases"
	VMService_StreamLeaseEvents_FullMethodName     = "/verself.vm_orchestrator.v1.VMService/StreamLeaseEvents"
	VMService_StartExec_FullMethodName             = "/verself.vm_orchestrator.v1.VMService/StartExec"
	VMService_CancelExec_FullMethodName            = "/verself.vm_orchestrator.v1.VMService/CancelExec"
	VMService_GetExec_FullMethodName               = "/verself.vm_orchestrator.v1.VMService/GetExec"
	VMService_WaitExec_FullMethodName              = "/verself.vm_orchestrator.v1.VMService/WaitExec"
	VMService_CommitFilesystemMount_FullMethodName = "/verself.vm_orchestrator.v1.VMService/CommitFilesystemMount"
	VMService_SaveCheckpoint_FullMethodName        = "/verself.vm_orchestrator.v1.VMService/SaveCheckpoint"
	VMService_GetCapacity_FullMethodName           = "/verself.vm_orchestrator.v1.VMService/GetCapacity"
	VMService_SeedImage_FullMethodName             = "/verself.vm_orchestrator.v1.VMService/SeedImage"
)

// VMServiceClient is the client API for VMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VMServiceClient interface {
	AcquireLease(ctx context.Context, in *AcquireLeaseRequest, opts ...grpc.CallOption) (*AcquireLeaseResponse, error)
	RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*RenewLeaseResponse, error)
	ReleaseLease(ctx context.Context, in *ReleaseLeaseRequest, opts ...grpc.CallOption) (*ReleaseLeaseResponse, error)
	GetLease(ctx context.Context, in *GetLeaseRequest, opts ...grpc.CallOption) (*GetLeaseResponse, error)
	ListLeases(ctx context.Context, in *ListLeasesRequest, opts ...grpc.CallOption) (*ListLeasesResponse, error)
	StreamLeaseEvents(ctx context.Context, in *StreamLeaseEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LeaseEvent], error)
	StartExec(ctx context.Context, in *StartExecRequest, opts ...grpc.CallOption) (*StartExecResponse, error)
	CancelExec(ctx context.Context, in *CancelExecRequest, opts ...grpc.CallOption) (*CancelExecResponse, error)
	GetExec(ctx context.Context, in *GetExecRequest, opts ...grpc.CallOption) (*GetExecResponse, error)
	WaitExec(ctx context.Context, in *WaitExecRequest, opts ...grpc.CallOption) (*WaitExecResponse, error)
	CommitFilesystemMount(ctx context.Context, in *CommitFilesystemMountRequest, opts ...grpc.CallOption) (*CommitFilesystemMountResponse, error)
	SaveCheckpoint(ctx context.Context, in *SaveCheckpointRequest, opts ...grpc.CallOption) (*SaveCheckpointResponse, error)
	GetCapacity(ctx context.Context, in *GetCapacityRequest, opts ...grpc.CallOption) (*GetCapacityResponse, error)
	SeedImage(ctx context.Context, in *SeedImageRequest, opts ...grpc.CallOption) (*SeedImageResponse, error)
}

type vMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVMServiceClient(cc grpc.ClientConnInterface) VMServiceClient {
	return &vMServiceClient{cc}
}

func (c *vMServiceClient) AcquireLease(ctx context.Context, in *AcquireLeaseRequest, opts ...grpc.CallOption) (*AcquireLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireLeaseResponse)
	err := c.cc.Invoke(ctx, VMService_AcquireLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) RenewLease(ctx context.Context, in *RenewLeaseRequest, opts ...grpc.CallOption) (*RenewLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewLeaseResponse)
	err := c.cc.Invoke(ctx, VMService_RenewLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) ReleaseLease(ctx context.Context, in *ReleaseLeaseRequest, opts ...grpc.CallOption) (*ReleaseLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseLeaseResponse)
	err := c.cc.Invoke(ctx, VMService_ReleaseLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) GetLease(ctx context.Context, in *GetLeaseRequest, opts ...grpc.CallOption) (*GetLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaseResponse)
	err := c.cc.Invoke(ctx, VMService_GetLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) ListLeases(ctx context.Context, in *ListLeasesRequest, opts ...grpc.CallOption) (*ListLeasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLeasesResponse)
	err := c.cc.Invoke(ctx, VMService_ListLeases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) StreamLeaseEvents(ctx context.Context, in *StreamLeaseEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LeaseEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VMService_ServiceDesc.Streams[0], VMService_StreamLeaseEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLeaseEventsRequest, LeaseEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_StreamLeaseEventsClient = grpc.ServerStreamingClient[LeaseEvent]

func (c *vMServiceClient) StartExec(ctx context.Context, in *StartExecRequest, opts ...grpc.CallOption) (*StartExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartExecResponse)
	err := c.cc.Invoke(ctx, VMService_StartExec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) CancelExec(ctx context.Context, in *CancelExecRequest, opts ...grpc.CallOption) (*CancelExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelExecResponse)
	err := c.cc.Invoke(ctx, VMService_CancelExec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) GetExec(ctx context.Context, in *GetExecRequest, opts ...grpc.CallOption) (*GetExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExecResponse)
	err := c.cc.Invoke(ctx, VMService_GetExec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) WaitExec(ctx context.Context, in *WaitExecRequest, opts ...grpc.CallOption) (*WaitExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitExecResponse)
	err := c.cc.Invoke(ctx, VMService_WaitExec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) CommitFilesystemMount(ctx context.Context, in *CommitFilesystemMountRequest, opts ...grpc.CallOption) (*CommitFilesystemMountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitFilesystemMountResponse)
	err := c.cc.Invoke(ctx, VMService_CommitFilesystemMount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) SaveCheckpoint(ctx context.Context, in *SaveCheckpointRequest, opts ...grpc.CallOption) (*SaveCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCheckpointResponse)
	err := c.cc.Invoke(ctx, VMService_SaveCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) GetCapacity(ctx context.Context, in *GetCapacityRequest, opts ...grpc.CallOption) (*GetCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapacityResponse)
	err := c.cc.Invoke(ctx, VMService_GetCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMServiceClient) SeedImage(ctx context.Context, in *SeedImageRequest, opts ...grpc.CallOption) (*SeedImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeedImageResponse)
	err := c.cc.Invoke(ctx, VMService_SeedImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMServiceServer is the server API for VMService service.
// All implementations should embed UnimplementedVMServiceServer
// for forward compatibility.
type VMServiceServer interface {
	AcquireLease(context.Context, *AcquireLeaseRequest) (*AcquireLeaseResponse, error)
	RenewLease(context.Context, *RenewLeaseRequest) (*RenewLeaseResponse, error)
	ReleaseLease(context.Context, *ReleaseLeaseRequest) (*ReleaseLeaseResponse, error)
	GetLease(context.Context, *GetLeaseRequest) (*GetLeaseResponse, error)
	ListLeases(context.Context, *ListLeasesRequest) (*ListLeasesResponse, error)
	StreamLeaseEvents(*StreamLeaseEventsRequest, grpc.ServerStreamingServer[LeaseEvent]) error
	StartExec(context.Context, *StartExecRequest) (*StartExecResponse, error)
	CancelExec(context.Context, *CancelExecRequest) (*CancelExecResponse, error)
	GetExec(context.Context, *GetExecRequest) (*GetExecResponse, error)
	WaitExec(context.Context, *WaitExecRequest) (*WaitExecResponse, error)
	CommitFilesystemMount(context.Context, *CommitFilesystemMountRequest) (*CommitFilesystemMountResponse, error)
	SaveCheckpoint(context.Context, *SaveCheckpointRequest) (*SaveCheckpointResponse, error)
	GetCapacity(context.Context, *GetCapacityRequest) (*GetCapacityResponse, error)
	SeedImage(context.Context, *SeedImageRequest) (*SeedImageResponse, error)
}

// UnimplementedVMServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVMServiceServer struct{}

func (UnimplementedVMServiceServer) AcquireLease(context.Context, *AcquireLeaseRequest) (*AcquireLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcquireLease not implemented")
}
func (UnimplementedVMServiceServer) RenewLease(context.Context, *RenewLeaseRequest) (*RenewLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewLease not implemented")
}
func (UnimplementedVMServiceServer) ReleaseLease(context.Context, *ReleaseLeaseRequest) (*ReleaseLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseLease not implemented")
}
func (UnimplementedVMServiceServer) GetLease(context.Context, *GetLeaseRequest) (*GetLeaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLease not implemented")
}
func (UnimplementedVMServiceServer) ListLeases(context.Context, *ListLeasesRequest) (*ListLeasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeases not implemented")
}
func (UnimplementedVMServiceServer) StreamLeaseEvents(*StreamLeaseEventsRequest, grpc.ServerStreamingServer[LeaseEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamLeaseEvents not implemented")
}
func (UnimplementedVMServiceServer) StartExec(context.Context, *StartExecRequest) (*StartExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartExec not implemented")
}
func (UnimplementedVMServiceServer) CancelExec(context.Context, *CancelExecRequest) (*CancelExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelExec not implemented")
}
func (UnimplementedVMServiceServer) GetExec(context.Context, *GetExecRequest) (*GetExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExec not implemented")
}
func (UnimplementedVMServiceServer) WaitExec(context.Context, *WaitExecRequest) (*WaitExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitExec not implemented")
}
func (UnimplementedVMServiceServer) CommitFilesystemMount(context.Context, *CommitFilesystemMountRequest) (*CommitFilesystemMountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitFilesystemMount not implemented")
}
func (UnimplementedVMServiceServer) SaveCheckpoint(context.Context, *SaveCheckpointRequest) (*SaveCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCheckpoint not implemented")
}
func (UnimplementedVMServiceServer) GetCapacity(context.Context, *GetCapacityRequest) (*GetCapacityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapacity not implemented")
}
func (UnimplementedVMServiceServer) SeedImage(context.Context, *SeedImageRequest) (*SeedImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SeedImage not implemented")
}
func (UnimplementedVMServiceServer) testEmbeddedByValue() {}

// UnsafeVMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMServiceServer will
// result in compilation errors.
type UnsafeVMServiceServer interface {
	mustEmbedUnimplementedVMServiceServer()
}

func RegisterVMServiceServer(s grpc.ServiceRegistrar, srv VMServiceServer) {
	// If the following call panics, it indicates UnimplementedVMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VMService_ServiceDesc, srv)
}

func _VMService_AcquireLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).AcquireLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_AcquireLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).AcquireLease(ctx, req.(*AcquireLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_RenewLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).RenewLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_RenewLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).RenewLease(ctx, req.(*RenewLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_ReleaseLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).ReleaseLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_ReleaseLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).ReleaseLease(ctx, req.(*ReleaseLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_GetLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).GetLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_GetLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).GetLease(ctx, req.(*GetLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_ListLeases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLeasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).ListLeases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_ListLeases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).ListLeases(ctx, req.(*ListLeasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_StreamLeaseEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLeaseEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VMServiceServer).StreamLeaseEvents(m, &grpc.GenericServerStream[StreamLeaseEventsRequest, LeaseEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VMService_StreamLeaseEventsServer = grpc.ServerStreamingServer[LeaseEvent]

func _VMService_StartExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).StartExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_StartExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).StartExec(ctx, req.(*StartExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_CancelExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).CancelExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_CancelExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).CancelExec(ctx, req.(*CancelExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_GetExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).GetExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_GetExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).GetExec(ctx, req.(*GetExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_WaitExec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).WaitExec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_WaitExec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).WaitExec(ctx, req.(*WaitExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_CommitFilesystemMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitFilesystemMountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).CommitFilesystemMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_CommitFilesystemMount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).CommitFilesystemMount(ctx, req.(*CommitFilesystemMountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_SaveCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).SaveCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_SaveCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).SaveCheckpoint(ctx, req.(*SaveCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_GetCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).GetCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_GetCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).GetCapacity(ctx, req.(*GetCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMService_SeedImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMServiceServer).SeedImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMService_SeedImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMServiceServer).SeedImage(ctx, req.(*SeedImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VMService_ServiceDesc is the grpc.ServiceDesc for VMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "verself.vm_orchestrator.v1.VMService",
	HandlerType: (*VMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireLease",
			Handler:    _VMService_AcquireLease_Handler,
		},
		{
			MethodName: "RenewLease",
			Handler:    _VMService_RenewLease_Handler,
		},
		{
			MethodName: "ReleaseLease",
			Handler:    _VMService_ReleaseLease_Handler,
		},
		{
			MethodName: "GetLease",
			Handler:    _VMService_GetLease_Handler,
		},
		{
			MethodName: "ListLeases",
			Handler:    _VMService_ListLeases_Handler,
		},
		{
			MethodName: "StartExec",
			Handler:    _VMService_StartExec_Handler,
		},
		{
			MethodName: "CancelExec",
			Handler:    _VMService_CancelExec_Handler,
		},
		{
			MethodName: "GetExec",
			Handler:    _VMService_GetExec_Handler,
		},
		{
			MethodName: "WaitExec",
			Handler:    _VMService_WaitExec_Handler,
		},
		{
			MethodName: "CommitFilesystemMount",
			Handler:    _VMService_CommitFilesystemMount_Handler,
		},
		{
			MethodName: "SaveCheckpoint",
			Handler:    _VMService_SaveCheckpoint_Handler,
		},
		{
			MethodName: "GetCapacity",
			Handler:    _VMService_GetCapacity_Handler,
		},
		{
			MethodName: "SeedImage",
			Handler:    _VMService_SeedImage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLeaseEvents",
			Handler:       _VMService_StreamLeaseEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/substrate/vm-orchestrator/proto/v1/vm_service.proto",
}
