---
notifications_service_subdomain: notifications.api
notifications_service_domain: "{{ notifications_service_subdomain }}.{{ forge_metal_domain }}"
notifications_service_auth_issuer_url: "https://auth.{{ forge_metal_domain }}"
notifications_service_identity_project_name: "{{ identity_service_auth_project_name | default('identity-service') }}"
notifications_service_force_schema_reset: false
notifications_service_pg_database: notifications_service
notifications_service_pg_max_conns: 8
notifications_service_pg_min_conns: 1
notifications_service_pg_conn_max_lifetime_seconds: 1800
notifications_service_pg_conn_max_idle_seconds: 300
