load("@rules_java//java:defs.bzl", "java_import", "java_library")

package(default_visibility = ["//visibility:public"])

genrule(
    name = "smithy_model_jar",
    srcs = ["@dev_tool_smithy_cli//file"],
    outs = ["smithy-model-1.70.0.jar"],
    cmd = """
set -euo pipefail
tmp="$$(mktemp -d)"
trap 'rm -rf "$$tmp"' EXIT
unzip -q "$(location @dev_tool_smithy_cli//file:file)" -d "$$tmp"
cp "$$tmp/smithy-cli-linux-x86_64/lib/smithy-model-1.70.0.jar" "$@"
""",
)

genrule(
    name = "smithy_utils_jar",
    srcs = ["@dev_tool_smithy_cli//file"],
    outs = ["smithy-utils-1.70.0.jar"],
    cmd = """
set -euo pipefail
tmp="$$(mktemp -d)"
trap 'rm -rf "$$tmp"' EXIT
unzip -q "$(location @dev_tool_smithy_cli//file:file)" -d "$$tmp"
cp "$$tmp/smithy-cli-linux-x86_64/lib/smithy-utils-1.70.0.jar" "$@"
""",
)

java_import(
    name = "smithy_model",
    jars = [":smithy-model-1.70.0.jar"],
)

java_import(
    name = "smithy_utils",
    jars = [":smithy-utils-1.70.0.jar"],
)

java_library(
    name = "verself_smithy_validators",
    srcs = glob(["java/**/*.java"]),
    resource_strip_prefix = "src/contracts/validators/resources",
    resources = glob(["resources/**"]),
    deps = [
        ":smithy_model",
        ":smithy_utils",
    ],
)
