load("@rules_pkg//pkg:tar.bzl", "pkg_tar")

exports_files(["tools.lock.json"])

pkg_tar(
    name = "runtime_artifact",
    out = "zitadel-runtime.tar",
    files = {
        "@zitadel_tools//tools/zitadel": "bin/zitadel",
    },
    modes = {
        "bin/zitadel": "0755",
    },
    visibility = ["//visibility:public"],
)

filegroup(
    name = "guardian_crd",
    srcs = ["guardian/v1alpha1/schema.cue"],
    visibility = ["//visibility:public"],
)
