http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "guest_image_ubuntu_base",
    downloaded_file_path = "ubuntu-base-24.04.4-base-amd64.tar.gz",
    sha256 = "c1e67ef7b17a6300e136118bd1dc04725009cb376c1aad10abcf8cd453628d58",
    url = "https://cdimages.ubuntu.com/ubuntu-base/releases/24.04/release/ubuntu-base-24.04.4-base-amd64.tar.gz",
)

http_file(
    name = "guest_image_vmlinux",
    downloaded_file_path = "vmlinux-6.1.155",
    sha256 = "e20e46d0c36c55c0d1014eb20576171b3f3d922260d9f792017aeff53af3d4f2",
    url = "https://s3.amazonaws.com/spec.ccfc.min/firecracker-ci/v1.15/x86_64/vmlinux-6.1.155",
)

http_file(
    name = "guest_image_vmlinux_config",
    downloaded_file_path = "vmlinux-6.1.155.config",
    sha256 = "024b2aae62fe7131f9a9ab80f27619c882c0a37265dd105adae01d2867bef7c3",
    url = "https://s3.amazonaws.com/spec.ccfc.min/firecracker-ci/v1.15/x86_64/vmlinux-6.1.155.config",
)

http_file(
    name = "guest_image_firecracker_release",
    downloaded_file_path = "firecracker-v1.15.0-x86_64.tgz",
    sha256 = "00cadf7f21e709e939dc0c8d16e2d2ce7b975a62bec6c50f74b421cc8ab3cab4",
    url = "https://github.com/firecracker-microvm/firecracker/releases/download/v1.15.0/firecracker-v1.15.0-x86_64.tgz",
)

http_file(
    name = "guest_image_github_actions_runner",
    downloaded_file_path = "actions-runner-linux-x64-2.333.1.tar.gz",
    sha256 = "18f8f68ed1892854ff2ab1bab4fcaa2f5abeedc98093b6cb13638991725cab74",
    url = "https://github.com/actions/runner/releases/download/v2.333.1/actions-runner-linux-x64-2.333.1.tar.gz",
)

http_file(
    name = "guest_image_e2fsprogs",
    downloaded_file_path = "e2fsprogs_1.47.0-2.4~exp1ubuntu4.1_amd64.deb",
    sha256 = "1d0fb19dcf14316d04602260871dba3c1441c0ecf3c3bde54eacba35dcc5a40b",
    url = "https://archive.ubuntu.com/ubuntu/pool/main/e/e2fsprogs/e2fsprogs_1.47.0-2.4~exp1ubuntu4.1_amd64.deb",
)

http_file(
    name = "guest_image_e2fsprogs_libblkid",
    downloaded_file_path = "libblkid1_2.39.3-9ubuntu6.5_amd64.deb",
    sha256 = "2307a9ed92642a69de0284ac63e233e45ac5a2c3831f04399f7d212379487e82",
    url = "https://archive.ubuntu.com/ubuntu/pool/main/u/util-linux/libblkid1_2.39.3-9ubuntu6.5_amd64.deb",
)

http_file(
    name = "guest_image_e2fsprogs_libcom_err",
    downloaded_file_path = "libcom-err2_1.47.0-2.4~exp1ubuntu4.1_amd64.deb",
    sha256 = "7ab24d3057dabf86db8f771ad6e43f073ed86b6b950d6e8ba22cb9fe6707bbc9",
    url = "https://archive.ubuntu.com/ubuntu/pool/main/e/e2fsprogs/libcom-err2_1.47.0-2.4~exp1ubuntu4.1_amd64.deb",
)

http_file(
    name = "guest_image_e2fsprogs_libe2fs",
    downloaded_file_path = "libext2fs2t64_1.47.0-2.4~exp1ubuntu4.1_amd64.deb",
    sha256 = "276686704314749497f1530ff9e62fd0280328be786a28db0cfe2aa31c88119e",
    url = "https://archive.ubuntu.com/ubuntu/pool/main/e/e2fsprogs/libext2fs2t64_1.47.0-2.4~exp1ubuntu4.1_amd64.deb",
)

http_file(
    name = "guest_image_e2fsprogs_libss",
    downloaded_file_path = "libss2_1.47.0-2.4~exp1ubuntu4.1_amd64.deb",
    sha256 = "e3b6140b815970461c4312f1dc3d6b1f0d62d99f4ebe2ad087bffa630010035a",
    url = "https://archive.ubuntu.com/ubuntu/pool/main/e/e2fsprogs/libss2_1.47.0-2.4~exp1ubuntu4.1_amd64.deb",
)

http_file(
    name = "guest_image_e2fsprogs_libuuid",
    downloaded_file_path = "libuuid1_2.39.3-9ubuntu6.5_amd64.deb",
    sha256 = "2f801582b5f0e7cb0c2d3d3651193e69f4540ee3b7dcb6079a3562f0880b9edf",
    url = "https://archive.ubuntu.com/ubuntu/pool/main/u/util-linux/libuuid1_2.39.3-9ubuntu6.5_amd64.deb",
)
