---
- name: Restart electric
  ansible.builtin.systemd:
    name: electric
    state: restarted
    daemon_reload: true

- name: Reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: reloaded
