[workers]
vs-gamma-w0 verself_ssh_host=206.223.228.87 verself_recovery_ssh_host=206.223.228.87 verself_recovery_ssh_port=22 verself_recovery_ssh_user=ubuntu

[infra]
vs-gamma-w0 verself_ssh_host=206.223.228.87 verself_recovery_ssh_host=206.223.228.87 verself_recovery_ssh_port=22 verself_recovery_ssh_user=ubuntu

[all:vars]
verself_ssh_user=ubuntu
