# gazelle:prefix github.com/verself/secrets-service

load("//src/infrastructure-components/spire:identity.bzl", "spire_identity")
load("//src/services/deployment-service:declarations.bzl", "deploy_declarations")
load("//src/tools/build:go_module_checks.bzl", "go_module_checks")

deploy_declarations(visibility = ["//visibility:public"])

go_module_checks()

filegroup(
    name = "guardian_crd",
    srcs = ["guardian/v1alpha1/schema.cue"],
    visibility = ["//src/guardian-specification:__pkg__"],
)

spire_identity(
    name = "spiffe_identity",
    component = "secrets_service",
    entry_id = "verself-secrets-service",
    key = "secrets_service.default",
    path = "/svc/secrets-service",
    user = "secrets_service",
    visibility = ["//src/infrastructure-components/spire:__pkg__"],
)
