clickstack_admin_email: ENC[AES256_GCM,data:4UWW8wyygirVQQod1+31hehev69Q930=,iv:w/ww09hLqORu/QOL+fdMjBPf0bFxH5WPETB7u4EHdwQ=,tag:Ht6/2o/LcMMuAwXH1Ya/qA==,type:str]
clickstack_admin_password: ENC[AES256_GCM,data:TikTQGRteN45ZytNZwV7zX4M0zChrdXQ,iv:HA+KOMHrIhmq1TcUJFmAn5/orCr/UOlKBEXhaMlMGfk=,tag:wHxDxK7cDNo6iWLV7qydVQ==,type:str]
#ENC[AES256_GCM,data:QbGasWcPVvlEr1z6CNx68von5CnELpj3d2YdTGEDjPlmqK8+YX1Vn0xnrqdGI9ljs1ZBvl/EYlCQYfMeNHMHNESN,iv:Pis31OX5MPWgsWzM5VaVMNUZUrLNBPJGfmbS+rKNA0g=,tag:A04tFKClpS3TAehaFJnt4Q==,type:comment]
#ENC[AES256_GCM,data:YCkiovVEbTloR3zZ0IX6CqZmcwGMa3qdWFPoSslaNnFeve9BUiVeq3N7hzYGaZi+Cw==,iv:tYHJ+sn4R+vMu9D4m+o515ERVlQ6pIQD3RtEAOJLObI=,tag:u9vRoXxgSzdJTQezUHGCsg==,type:comment]
#ENC[AES256_GCM,data:0F+hnlsqDD4jgIb06jJXSOPp+LyE3YXQUKwr4oC5RV7gDd1iCBDCnyGWoudQfZnz6Q==,iv:7SeCcAsRX8fJyHkJ3k8kIWMWz0Oh6MWfpJPfar9jh2s=,tag:INu+wF2t0zoYk7+rSt0MmA==,type:comment]
#ENC[AES256_GCM,data:UPKjwnZWBfO0sAJezfxNN+2kUdioacT0nxCZhe19vuGHlSemZPnrmuYkytSZNKnNwG6A2N02bA==,iv:KK6nCJ9xZc3G8zz8hnx+FnRpBuJnG6eTDugbpLHSB30=,tag:C+3oxHUDcF97H5lAsJAbtw==,type:comment]
cloudflare_api_token: ENC[AES256_GCM,data:LQ+XA9XXoinzRljjctvGdXlc4am72V4SZhM/if35WHHlNnajjGPCWusWil0rewSgbg7bu48=,iv:bMdNhmzfxP5ffGIuLfaKFhEuXWox/9ezTVXdfKiHrfw=,tag:LHNi7GMHdnRdFtPHsj0/4Q==,type:str]
sops:
    age:
        - recipient: age10qyzk366rw595gfzqrun6dgcjslqcvpn4s6t7ee4l04c8dtdpvxqdkd823
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WW9nRlp2Wm5XRG1NYXVS
            ajE5UktQWk05OUhKby83L0FZVVBoeUR1MW5jClRIZ3NiZVBMbUhpUWtQTjFBTWZm
            S2lXb0tINFZEcHY2T1g3b0tBM0p1ZWMKLS0tIGxnZXlFc1FPUmRvMVk0eFpCTTVN
            RW9IeDVlOHRjcStHN3I1eHhsNWQyZXMKkmeB5qYbFc10OSjDA4b9VTY7aPsVzFiV
            +6WPORxzMwfYuzApMd66HSl1CXAowwMfJtrZqi3UoFfBW63hM6gO2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T07:04:20Z"
    mac: ENC[AES256_GCM,data:q9D2wLGcEdr/kLl8mwEqEgRygY5KDsmiiNKsjh/7TMhNt/88gUq7tYL5rurflPl/WZcbD9itvwu0j1DAK+x+ilaBVFntichX/CvZ43xUMfaKkUv0dw7DEHYaJVfbuXoibI13nCCe0BDZveUx7qHv+TUK3rL+U3nBpZee2W0jZek=,iv:BBGiZ2GzhfuV52W1Kc9uvhhfu1sKHS669XdiRWlNFoA=,tag:zvnQelDbv4fqSh/yYS/4uQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
