cloudflare_api_token: ""
postgresql_admin_password: ENC[AES256_GCM,data:najC4KWkZYisUFRAV+gWI1om9zm6AgBr7bGBGUKh58g=,iv:x56Tt83FO792DbWR9wmOKX16O1pCwaQZ+hPToyIuHSU=,tag:Au5wMymjBEWUHJU1SeCNAQ==,type:str]
postgresql_billing_password: ENC[AES256_GCM,data:pUzC8FSQmgKEtKadYZ87hKnxrnTNM8XfchGKxGzLEFo=,iv:N3s96bt4JSyWTaRw8SfAJdf1RLAzMZbg6pDtA2xGwqM=,tag:7ZCtM/V22hYZGBRjrcv4CA==,type:str]
clickhouse_password: ENC[AES256_GCM,data:OVyLIyLhaD5kQdI7MiU8KXYj2twa+NPdCp79C9ndKdM=,iv:DUT8gUDOY7MAijlJHhGnh1j38irTZTy3gt5F6B0Zfto=,tag:6TYXu7Rsxurzxjh7Ou1cxw==,type:str]
zitadel_db_password: ENC[AES256_GCM,data:KwSyriY1O8XYjOzmUvAOG6mID5gkC1DhvuAkAT22URE=,iv:qtv6W+qjOr8rz/tM/02HDC7ykFPjlIsdWwhUA9IzKzA=,tag:oVOhL1XtCnzU685XiD9eNw==,type:str]
zitadel_masterkey: ENC[AES256_GCM,data:Zzq0zwYLzANIkF01pMKOAmCfG08cjSyal18sqpnCi/g=,iv:NKHDxOlFC5Rlekz9oszKFC/VwKYBhSOjuPiKpYjb3po=,tag:1sWXYVcrHDDIeguuxFioqw==,type:str]
zitadel_admin_password_base: ENC[AES256_GCM,data:J3phWzmjkGXsZJoFd8DYnPee48c40jfHw5hP7ur47t0=,iv:+htSaw5f4uWorn/fwhiF3cOJPhIkPKws15ykk3MdExQ=,tag:o4dHP0EXt82AQQEDQgg0Hg==,type:str]
zitadel_admin_pat: ENC[AES256_GCM,data:nCz1SDOqq0dIOoe1+8Z8aw8duLYPlsI/gl4UA016gCMRfW5wq842X/q5aZVf/c3Cy8A0T2cYZCHflmUeT3HsC+SwbNh5LrM=,iv:9pPRjRygYQKhJkz0QcYEMsUNejwAC/XWMr8g2Zlz4xY=,tag:eUri+nLQs9PB6qnWiHixbQ==,type:str]
forgejo_admin_user_slug: ENC[AES256_GCM,data:nMySCg==,iv:Bl0ytZJBMbPPlbUevzl2ibAEiU2pnNQPMpdTJVaLuCo=,tag:5tCQQ2bEhb/0H3sfESHQbg==,type:str]
forgejo_admin_email_slug: ENC[AES256_GCM,data:69rlwJiq,iv:NufyeKqkFAkgu4rpphy7UcmTlMNd8clrAUi4ogRv1w0=,tag:9035e8GCvlZBCcFzDgH/NQ==,type:str]
forgejo_admin_password_base: ENC[AES256_GCM,data:SWzEJuxlS/JCW0mDH7t/t27eJxy+4Kkb,iv:ph5giy154U0gR+GIhjkFHHP38Tzgs404KK5SIQTF8qY=,tag:bEwJzuqpMoI2ky5CpfazfQ==,type:str]
hyperdx_admin_email_slug: ENC[AES256_GCM,data:IB3wFm3j,iv:/pqA0dxsc1ojGtMKSYApt72vm2rBuJSp3zc3cxoaAZo=,tag:Zw9HfZsy48kX6z/ZVAi0MA==,type:str]
hyperdx_admin_password_base: ENC[AES256_GCM,data:aLTpZlCutQkkhjjttkT0ole0XTV4sh10,iv:o70OxPPzGkODZ26dvX1jXaGrTerSE+pKq9dv27F543A=,tag:F18qbMeVUTTx07sNwGS7Fw==,type:str]
hyperdx_session_secret: ENC[AES256_GCM,data:bESoKvQ5jMdPMiL2L5lhSifLRvGdUuPoDw84R26G0Vb1akLROuSu/i/rV9O1/BmAaHBFu8sl2hH435Vy0Xuzyw==,iv:AweCiuOYPnGWmGPmm9ghS/eFGZiBy3unyG1/5lvBvMk=,tag:o/8s81j4ZdR552GEA0ZTyQ==,type:str]
billing_pg_password: ENC[AES256_GCM,data:cW2cX2P2gJoSqYG4I4pwGpJUqqX8p2+MEATBl0HY5co=,iv:5RuuJcufYDwaCpbBE7kLh6jAPqsQ3EGnXkX2umWZrrw=,tag:RhAR1y9ZMZsxRHUroQsfUg==,type:str]
stripe_secret_key: ENC[AES256_GCM,data:pl6Ky+xKMN89V9pdcD9DIe1nuxO7s5WTL3oHR29MxOM=,iv:7le+v24Sh+KRufkNSv9XPRYxN+hQZn7eA2vIz5YMJ2M=,tag:sCP0mSBPe4OkhHmdBSoq5g==,type:str]
stripe_webhook_secret: ENC[AES256_GCM,data:cwm3IaZLzYai7DRcdGaa0Zwpmbu/b/mFmmQqwBav3us=,iv:XtzLEH2gCrwuKQ6/GSeYaTgL4HYe4aWABMSVk9LyIE0=,tag:bMW6b8MyXExXkWnEpDztOQ==,type:str]
sops:
    age:
        - recipient: age10qyzk366rw595gfzqrun6dgcjslqcvpn4s6t7ee4l04c8dtdpvxqdkd823
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSGlHYlBSc1FxUWZzeGh4
            dkRISVFNSlhBSHJUSC81bE5RMktSTm5SRVRzCjZyOCt4aUowUnNEWVQ1MjJrOWUv
            elZoSitodWtid3ZNOHJuWHhLUmJxbGcKLS0tIG03b0t2dFpUQnF2dFJVMjYrdHVQ
            b2pzMVFzYi9HUDZBbUpHZWhod2J0b3cK4W7c7mLenHzG0dweI/VpKWGtNC2zo4VM
            CUMWhlzfaYiSnYVucv4s05uWbY0/ZQdY3OMXa7I2l+vN1qQR7Rg7iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T04:56:26Z"
    mac: ENC[AES256_GCM,data:VofKBNX0jmrtFlBOtqWpqBqWAIEALylQCtm93LbC+GcbeHafAuyFmOq8GLOx0vh0MBM/sL6PSdoUkx/TDuqzgV5Y46dmyamtz9rNk/GrwnHdUVQczshNow0a5MYsGJcQnlRP3Sh4ioehyJtW82nhoINLCgsYkCoCd4a2dVxndRw=,iv:cpke29nuV4QxCGNwnhG0S5wED2wt5blaO6WB+7dVe2E=,tag:qTXjWCW4+zItTvHF9dpyKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
