load("//src/tools/build:openapi_codegen.bzl", "verself_oapi_go_client")

verself_oapi_go_client(
    name = "client",
    importpath = "github.com/verself/projects-service/client",
    package = "projectsclient",
    response_type_suffix = "HTTPResponse",
    spec = "//src/services/projects-service/openapi:internal-openapi-3.0.yaml",
    visibility = ["//src/services:__subpackages__"],
    deps = [
        "@com_github_oapi_codegen_runtime//:runtime",
        "@com_github_oapi_codegen_runtime//types",
    ],
)

alias(
    name = "go_default_library",
    actual = ":client",
    visibility = ["//src/services:__subpackages__"],
)
