# gazelle:prefix github.com/verself/integrations/cloudflare/control-plane/cmd/cloudflare-control-plane

load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "cloudflare-control-plane_lib",
    srcs = [
        "certificates.go",
        "main.go",
        "site.go",
    ],
    importpath = "github.com/verself/integrations/cloudflare/control-plane/cmd/cloudflare-control-plane",
    visibility = ["//visibility:private"],
    deps = [
        "//src/integrations/cloudflare/control-plane/r2control",
        "@in_gopkg_yaml_v3//:yaml_v3",
        "@org_golang_x_crypto//acme",
    ],
)

go_binary(
    name = "cloudflare-control-plane",
    embed = [":cloudflare-control-plane_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "cloudflare-control-plane_test",
    srcs = ["main_test.go"],
    embed = [":cloudflare-control-plane_lib"],
    deps = ["//src/integrations/cloudflare/control-plane/r2control"],
)
