load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "electric-recover_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/infrastructure-components/electric/cmd/electric-recover",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "electric-recover",
    embed = [":electric-recover_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "electric-recover_test",
    srcs = ["main_test.go"],
    embed = [":electric-recover_lib"],
)
