# gazelle:prefix github.com/verself/tools/controllerstate

load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "controllerstate",
    srcs = ["controllerstate.go"],
    importpath = "github.com/verself/tools/controllerstate",
    visibility = ["//visibility:public"],
)

go_test(
    name = "controllerstate_test",
    srcs = ["controllerstate_test.go"],
    embed = [":controllerstate"],
)
