apiVersion: network.guardian.verself.sh/v1alpha1
kind: DNSResolution
metadata:
  name: gamma-public-dns
spec:
  providerRef: cloudflare-main
  records:
    - domainRef: product
      name: "@"
      type: A
      ttl: 1
      valueFrom: environment.ingress.publicIPv4
