// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

import * as v from "valibot";

export const vBillingBalance = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  credit_available: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  credit_pending: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  free_tier_available: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  free_tier_pending: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  org_id: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  total_available: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
});

export const vBillingGrant = v.strictObject({
  available: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  expires_at: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  grant_id: v.string(),
  pending: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  source: v.string(),
});

export const vBillingGrants = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  grants: v.nullable(v.array(vBillingGrant)),
});

export const vBillingSubscription = v.strictObject({
  cadence: v.string(),
  current_period_end: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  current_period_start: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  plan_id: v.string(),
  product_id: v.string(),
  status: v.string(),
  subscription_id: v.pipe(v.string(), v.regex(/^-?[0-9]+$/)),
});

export const vBillingSubscriptions = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  subscriptions: v.nullable(v.array(vBillingSubscription)),
});

export const vBillingUrlResponse = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  url: v.string(),
});

export const vErrorDetail = v.strictObject({
  location: v.optional(v.string()),
  message: v.optional(v.string()),
  value: v.optional(v.unknown()),
});

export const vErrorModel = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  detail: v.optional(v.string()),
  errors: v.nullish(v.array(vErrorDetail)),
  instance: v.optional(v.pipe(v.string(), v.url())),
  status: v.optional(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(
        BigInt("-9223372036854775808"),
        "Invalid value: Expected int64 to be >= -9223372036854775808",
      ),
      v.maxValue(BigInt(599)),
    ),
  ),
  title: v.optional(v.string()),
  type: v.optional(v.pipe(v.string(), v.url()), "about:blank"),
});

export const vSandboxAttemptRecord = v.strictObject({
  attempt_id: v.string(),
  attempt_seq: v.pipe(
    v.union([v.number(), v.string(), v.bigint()]),
    v.transform((x) => BigInt(x)),
    v.minValue(BigInt(0)),
    v.maxValue(BigInt(9007199254740991)),
  ),
  billing_job_id: v.optional(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(BigInt(0)),
      v.maxValue(BigInt(9007199254740991)),
    ),
  ),
  completed_at: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  created_at: v.pipe(v.string(), v.isoTimestamp()),
  duration_ms: v.optional(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(BigInt(0)),
      v.maxValue(BigInt(9007199254740991)),
    ),
  ),
  exit_code: v.optional(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(BigInt(0)),
      v.maxValue(BigInt(255)),
    ),
  ),
  failure_reason: v.optional(v.string()),
  golden_snapshot: v.optional(v.string()),
  orchestrator_job_id: v.optional(v.string()),
  runner_name: v.optional(v.string()),
  started_at: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  state: v.string(),
  stderr_bytes: v.optional(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(BigInt(0)),
      v.maxValue(BigInt(9007199254740991)),
    ),
  ),
  stdout_bytes: v.optional(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(BigInt(0)),
      v.maxValue(BigInt(9007199254740991)),
    ),
  ),
  trace_id: v.optional(v.string()),
  updated_at: v.pipe(v.string(), v.isoTimestamp()),
  zfs_written: v.optional(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(BigInt(0)),
      v.maxValue(BigInt(9007199254740991)),
    ),
  ),
});

export const vSandboxBillingCheckoutRequest = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  amount_cents: v.pipe(
    v.union([v.number(), v.string(), v.bigint()]),
    v.transform((x) => BigInt(x)),
    v.minValue(BigInt(1)),
    v.maxValue(BigInt(9007199254740991)),
  ),
  cancel_url: v.pipe(v.string(), v.maxLength(2048)),
  product_id: v.pipe(v.string(), v.maxLength(255)),
  success_url: v.pipe(v.string(), v.maxLength(2048)),
});

export const vSandboxBillingSubscriptionRequest = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  cadence: v.optional(v.picklist(["monthly", "annual"])),
  cancel_url: v.pipe(v.string(), v.maxLength(2048)),
  plan_id: v.pipe(v.string(), v.maxLength(255)),
  success_url: v.pipe(v.string(), v.maxLength(2048)),
});

export const vSandboxBillingWindow = v.strictObject({
  actual_quantity: v.optional(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(BigInt(0)),
      v.maxValue(BigInt(9007199254740991)),
    ),
  ),
  attempt_id: v.string(),
  billing_window_id: v.string(),
  created_at: v.pipe(v.string(), v.isoTimestamp()),
  pricing_phase: v.optional(v.string()),
  reservation_shape: v.string(),
  reserved_quantity: v.pipe(
    v.union([v.number(), v.string(), v.bigint()]),
    v.transform((x) => BigInt(x)),
    v.minValue(BigInt(0)),
    v.maxValue(BigInt(9007199254740991)),
  ),
  settled_at: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  state: v.string(),
  window_seq: v.pipe(
    v.union([v.number(), v.string(), v.bigint()]),
    v.transform((x) => BigInt(x)),
    v.minValue(BigInt(0)),
    v.maxValue(BigInt(9007199254740991)),
  ),
  window_start: v.pipe(v.string(), v.isoTimestamp()),
});

export const vSandboxExecutionLogs = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  attempt_id: v.string(),
  execution_id: v.string(),
  logs: v.string(),
});

export const vSandboxExecutionRecord = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  actor_id: v.string(),
  billing_windows: v.nullish(v.array(vSandboxBillingWindow)),
  commit_sha: v.optional(v.string()),
  correlation_id: v.optional(v.string()),
  created_at: v.pipe(v.string(), v.isoTimestamp()),
  default_branch: v.optional(v.string()),
  execution_id: v.string(),
  golden_generation_id: v.optional(v.string()),
  idempotency_key: v.optional(v.string()),
  kind: v.string(),
  latest_attempt: vSandboxAttemptRecord,
  org_id: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  product_id: v.string(),
  provider: v.optional(v.string()),
  provider_job_id: v.optional(v.string()),
  provider_run_id: v.optional(v.string()),
  ref: v.optional(v.string()),
  repo: v.optional(v.string()),
  repo_id: v.optional(v.string()),
  repo_url: v.optional(v.string()),
  run_command: v.optional(v.string()),
  status: v.string(),
  updated_at: v.pipe(v.string(), v.isoTimestamp()),
  workflow_job_name: v.optional(v.string()),
  workflow_path: v.optional(v.string()),
});

export const vSandboxGoldenGenerationRecord = v.strictObject({
  activated_at: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  attempt_id: v.optional(v.string()),
  created_at: v.pipe(v.string(), v.isoTimestamp()),
  execution_id: v.optional(v.string()),
  failure_detail: v.optional(v.string()),
  failure_reason: v.optional(v.string()),
  golden_generation_id: v.string(),
  orchestrator_job_id: v.optional(v.string()),
  repo_id: v.string(),
  runner_profile_slug: v.string(),
  snapshot_ref: v.optional(v.string()),
  source_ref: v.string(),
  source_sha: v.string(),
  state: v.string(),
  superseded_at: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  trigger_reason: v.string(),
  updated_at: v.pipe(v.string(), v.isoTimestamp()),
});

export const vSandboxImportRepoRequest = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  clone_url: v.string(),
  default_branch: v.optional(v.string()),
  full_name: v.optional(v.string()),
  name: v.optional(v.string()),
  owner: v.optional(v.string()),
  provider: v.optional(v.string()),
  provider_repo_id: v.optional(v.string()),
});

export const vSandboxRepoRecord = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  active_golden_generation_id: v.optional(v.string()),
  archived_at: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  clone_url: v.string(),
  compatibility_status: v.string(),
  compatibility_summary: v.optional(v.unknown()),
  created_at: v.pipe(v.string(), v.isoTimestamp()),
  default_branch: v.string(),
  full_name: v.string(),
  last_error: v.optional(v.string()),
  last_ready_sha: v.optional(v.string()),
  last_scanned_sha: v.optional(v.string()),
  name: v.string(),
  org_id: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  owner: v.string(),
  provider: v.string(),
  provider_repo_id: v.string(),
  repo_id: v.string(),
  runner_profile_slug: v.string(),
  state: v.string(),
  updated_at: v.pipe(v.string(), v.isoTimestamp()),
});

export const vSandboxRepoBootstrapRecord = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  attempt_id: v.string(),
  execution_id: v.string(),
  generation: vSandboxGoldenGenerationRecord,
  repo: vSandboxRepoRecord,
  trigger_reason: v.string(),
});

export const vSandboxSubmitExecutionResult = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  attempt_id: v.string(),
  execution_id: v.string(),
  status: v.string(),
});

export const vSandboxSubmitRequest = v.strictObject({
  $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
  default_branch: v.optional(v.string()),
  idempotency_key: v.optional(v.string()),
  kind: v.string(),
  product_id: v.optional(v.string()),
  provider: v.optional(v.string()),
  provider_job_id: v.optional(v.string()),
  provider_run_id: v.optional(v.string()),
  ref: v.optional(v.string()),
  repo: v.optional(v.string()),
  repo_id: v.optional(v.string()),
  repo_url: v.optional(v.string()),
  run_command: v.optional(v.string()),
  workflow_job_name: v.optional(v.string()),
  workflow_path: v.optional(v.string()),
});

export const vBillingBalanceWritable = v.strictObject({
  credit_available: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  credit_pending: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  free_tier_available: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  free_tier_pending: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  org_id: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  total_available: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
});

export const vBillingGrantsWritable = v.strictObject({
  grants: v.nullable(v.array(vBillingGrant)),
});

export const vBillingSubscriptionsWritable = v.strictObject({
  subscriptions: v.nullable(v.array(vBillingSubscription)),
});

export const vBillingUrlResponseWritable = v.strictObject({
  url: v.string(),
});

export const vErrorModelWritable = v.strictObject({
  detail: v.optional(v.string()),
  errors: v.nullish(v.array(vErrorDetail)),
  instance: v.optional(v.pipe(v.string(), v.url())),
  status: v.optional(
    v.pipe(
      v.union([v.number(), v.string(), v.bigint()]),
      v.transform((x) => BigInt(x)),
      v.minValue(
        BigInt("-9223372036854775808"),
        "Invalid value: Expected int64 to be >= -9223372036854775808",
      ),
      v.maxValue(BigInt(599)),
    ),
  ),
  title: v.optional(v.string()),
  type: v.optional(v.pipe(v.string(), v.url()), "about:blank"),
});

export const vSandboxBillingCheckoutRequestWritable = v.strictObject({
  amount_cents: v.pipe(
    v.union([v.number(), v.string(), v.bigint()]),
    v.transform((x) => BigInt(x)),
    v.minValue(BigInt(1)),
    v.maxValue(BigInt(9007199254740991)),
  ),
  cancel_url: v.pipe(v.string(), v.maxLength(2048)),
  product_id: v.pipe(v.string(), v.maxLength(255)),
  success_url: v.pipe(v.string(), v.maxLength(2048)),
});

export const vSandboxBillingSubscriptionRequestWritable = v.strictObject({
  cadence: v.optional(v.picklist(["monthly", "annual"])),
  cancel_url: v.pipe(v.string(), v.maxLength(2048)),
  plan_id: v.pipe(v.string(), v.maxLength(255)),
  success_url: v.pipe(v.string(), v.maxLength(2048)),
});

export const vSandboxExecutionLogsWritable = v.strictObject({
  attempt_id: v.string(),
  execution_id: v.string(),
  logs: v.string(),
});

export const vSandboxExecutionRecordWritable = v.strictObject({
  actor_id: v.string(),
  billing_windows: v.nullish(v.array(vSandboxBillingWindow)),
  commit_sha: v.optional(v.string()),
  correlation_id: v.optional(v.string()),
  created_at: v.pipe(v.string(), v.isoTimestamp()),
  default_branch: v.optional(v.string()),
  execution_id: v.string(),
  golden_generation_id: v.optional(v.string()),
  idempotency_key: v.optional(v.string()),
  kind: v.string(),
  latest_attempt: vSandboxAttemptRecord,
  org_id: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  product_id: v.string(),
  provider: v.optional(v.string()),
  provider_job_id: v.optional(v.string()),
  provider_run_id: v.optional(v.string()),
  ref: v.optional(v.string()),
  repo: v.optional(v.string()),
  repo_id: v.optional(v.string()),
  repo_url: v.optional(v.string()),
  run_command: v.optional(v.string()),
  status: v.string(),
  updated_at: v.pipe(v.string(), v.isoTimestamp()),
  workflow_job_name: v.optional(v.string()),
  workflow_path: v.optional(v.string()),
});

export const vSandboxImportRepoRequestWritable = v.strictObject({
  clone_url: v.string(),
  default_branch: v.optional(v.string()),
  full_name: v.optional(v.string()),
  name: v.optional(v.string()),
  owner: v.optional(v.string()),
  provider: v.optional(v.string()),
  provider_repo_id: v.optional(v.string()),
});

export const vSandboxRepoRecordWritable = v.strictObject({
  active_golden_generation_id: v.optional(v.string()),
  archived_at: v.optional(v.pipe(v.string(), v.isoTimestamp())),
  clone_url: v.string(),
  compatibility_status: v.string(),
  compatibility_summary: v.optional(v.unknown()),
  created_at: v.pipe(v.string(), v.isoTimestamp()),
  default_branch: v.string(),
  full_name: v.string(),
  last_error: v.optional(v.string()),
  last_ready_sha: v.optional(v.string()),
  last_scanned_sha: v.optional(v.string()),
  name: v.string(),
  org_id: v.pipe(v.string(), v.regex(/^[0-9]+$/)),
  owner: v.string(),
  provider: v.string(),
  provider_repo_id: v.string(),
  repo_id: v.string(),
  runner_profile_slug: v.string(),
  state: v.string(),
  updated_at: v.pipe(v.string(), v.isoTimestamp()),
});

export const vSandboxRepoBootstrapRecordWritable = v.strictObject({
  attempt_id: v.string(),
  execution_id: v.string(),
  generation: vSandboxGoldenGenerationRecord,
  repo: vSandboxRepoRecordWritable,
  trigger_reason: v.string(),
});

export const vSandboxSubmitExecutionResultWritable = v.strictObject({
  attempt_id: v.string(),
  execution_id: v.string(),
  status: v.string(),
});

export const vSandboxSubmitRequestWritable = v.strictObject({
  default_branch: v.optional(v.string()),
  idempotency_key: v.optional(v.string()),
  kind: v.string(),
  product_id: v.optional(v.string()),
  provider: v.optional(v.string()),
  provider_job_id: v.optional(v.string()),
  provider_run_id: v.optional(v.string()),
  ref: v.optional(v.string()),
  repo: v.optional(v.string()),
  repo_id: v.optional(v.string()),
  repo_url: v.optional(v.string()),
  run_command: v.optional(v.string()),
  workflow_job_name: v.optional(v.string()),
  workflow_path: v.optional(v.string()),
});

/**
 * OK
 */
export const vGetBillingBalanceResponse = vBillingBalance;

export const vCreateBillingCheckoutBody = vSandboxBillingCheckoutRequestWritable;

/**
 * OK
 */
export const vCreateBillingCheckoutResponse = vBillingUrlResponse;

export const vListBillingGrantsQuery = v.object({
  product_id: v.optional(v.string()),
  active: v.optional(v.boolean()),
});

/**
 * OK
 */
export const vListBillingGrantsResponse = vBillingGrants;

export const vCreateBillingSubscriptionBody = vSandboxBillingSubscriptionRequestWritable;

/**
 * OK
 */
export const vCreateBillingSubscriptionResponse = vBillingUrlResponse;

/**
 * OK
 */
export const vListBillingSubscriptionsResponse = vBillingSubscriptions;

export const vSubmitExecutionBody = vSandboxSubmitRequestWritable;

/**
 * Created
 */
export const vSubmitExecutionResponse = vSandboxSubmitExecutionResult;

export const vGetExecutionPath = v.object({
  execution_id: v.string(),
});

/**
 * OK
 */
export const vGetExecutionResponse = vSandboxExecutionRecord;

export const vGetExecutionLogsPath = v.object({
  execution_id: v.string(),
});

/**
 * OK
 */
export const vGetExecutionLogsResponse = vSandboxExecutionLogs;

/**
 * OK
 */
export const vListReposResponse = v.nullable(v.array(vSandboxRepoRecord));

export const vImportRepoBody = vSandboxImportRepoRequestWritable;

/**
 * Created
 */
export const vImportRepoResponse = vSandboxRepoRecord;

export const vGetRepoPath = v.object({
  repo_id: v.string(),
});

/**
 * OK
 */
export const vGetRepoResponse = vSandboxRepoRecord;

export const vListRepoGenerationsPath = v.object({
  repo_id: v.string(),
});

/**
 * OK
 */
export const vListRepoGenerationsResponse = v.nullable(v.array(vSandboxGoldenGenerationRecord));

export const vRefreshRepoPath = v.object({
  repo_id: v.string(),
});

/**
 * Accepted
 */
export const vRefreshRepoResponse = vSandboxRepoBootstrapRecord;

export const vRescanRepoPath = v.object({
  repo_id: v.string(),
});

/**
 * OK
 */
export const vRescanRepoResponse = vSandboxRepoRecord;
