minimum_pre_commit_version: "4.5.1"
repos:
  - repo: local
    hooks:
      - id: aspect-tidy
        name: aspect tidy
        entry: aspect tidy
        language: system
        pass_filenames: false

      - id: aspect-check
        name: aspect check
        entry: aspect check
        language: system
        pass_filenames: false
