load("@bazel_gazelle//:def.bzl", "gazelle")
load("@bazel_lib//lib:write_source_files.bzl", "write_source_files")

exports_files(["bazel.go.work"])

# gazelle:exclude artifacts
# gazelle:exclude smoke-artifacts
# gazelle:exclude docs/references
# gazelle:exclude src/websites
# gazelle:exclude src/substrate/vm-guest-telemetry

gazelle(
    name = "gazelle",
    args = ["-index=all"],
)

test_suite(
    name = "dev_check",
    tags = ["manual"],
    tests = [
        "//src/websites/apps/company:dev_check",
        "//src/websites/apps/verself-web:dev_check",
    ],
)

write_source_files(
    name = "dev_update",
    additional_update_targets = [
        "//src/websites/apps/company:dev_update",
        "//src/websites/apps/verself-web:dev_update",
        "//src/websites/packages/sdk:dev_update",
    ],
    tags = ["manual"],
)
