// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://127.0.0.1:4248" | (string & {});
};

export type ErrorDetail = {
  /**
   * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
   */
  location?: string;
  /**
   * Error message text
   */
  message?: string;
  /**
   * The value at the given location
   */
  value?: unknown;
};

export type ErrorModel = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * HTTP status code
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
};

export type IdentityApiCredential = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  auth_method: string;
  client_id: string;
  created_at: string;
  created_by: string;
  credential_id: string;
  display_name: string;
  expires_at?: string;
  fingerprint: string;
  last_used_at?: string;
  org_id: string;
  permissions: Array<string> | null;
  policy_version_at_issue: number;
  revoked_at?: string;
  revoked_by?: string;
  status: string;
  subject_id: string;
  updated_at: string;
};

export type IdentityApiCredentialIssuedMaterial = {
  auth_method: string;
  client_id: string;
  client_secret?: string;
  fingerprint: string;
  key_content?: string;
  key_id?: string;
  token_url: string;
};

export type IdentityApiCredentials = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  credentials: Array<IdentityApiCredential> | null;
};

export type IdentityCreateApiCredentialRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  auth_method?: "private_key_jwt" | "client_secret";
  display_name: string;
  expires_at?: string;
  permissions: Array<string> | null;
};

export type IdentityCreateApiCredentialResponse = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  credential: IdentityApiCredential;
  issued_material: IdentityApiCredentialIssuedMaterial;
};

export type IdentityInviteMemberRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  email: string;
  family_name?: string;
  given_name?: string;
  role_keys: Array<string> | null;
};

export type IdentityInviteMemberResponse = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  email: string;
  role_keys: Array<string> | null;
  status: string;
  user_id: string;
};

export type IdentityMember = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  display_name: string;
  email: string;
  login_name: string;
  role_keys: Array<string> | null;
  state: string;
  user_id: string;
};

export type IdentityMemberCapabilities = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  catalog: Array<IdentityMemberCapability> | null;
  document: IdentityMemberCapabilitiesDocument;
};

export type IdentityMemberCapabilitiesDocument = {
  enabled_keys: Array<string> | null;
  org_id: string;
  updated_at: string;
  updated_by: string;
  version: number;
};

export type IdentityMemberCapability = {
  default_enabled: boolean;
  description: string;
  key: string;
  label: string;
  permissions: Array<string> | null;
};

export type IdentityMembers = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  members: Array<IdentityMember> | null;
};

export type IdentityOrganization = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  caller: IdentityMember;
  member_capabilities: IdentityMemberCapabilitiesDocument;
  name: string;
  org_acl_version: number;
  org_id: string;
  permissions: Array<string> | null;
};

export type IdentityPutMemberCapabilitiesRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  enabled_keys: Array<string> | null;
  version: number;
};

export type IdentityRollApiCredentialRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  auth_method?: "private_key_jwt" | "client_secret";
};

export type IdentityRollApiCredentialResponse = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  credential: IdentityApiCredential;
  issued_material: IdentityApiCredentialIssuedMaterial;
};

export type IdentityUpdateMemberRolesRequest = {
  /**
   * A URL to the JSON Schema for this object.
   */
  readonly $schema?: string;
  expected_org_acl_version: number;
  expected_role_keys: Array<string> | null;
  role_keys: Array<string> | null;
};

export type ErrorModelWritable = {
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string;
  /**
   * HTTP status code
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type?: string;
};

export type IdentityApiCredentialWritable = {
  auth_method: string;
  client_id: string;
  created_at: string;
  created_by: string;
  credential_id: string;
  display_name: string;
  expires_at?: string;
  fingerprint: string;
  last_used_at?: string;
  org_id: string;
  permissions: Array<string> | null;
  policy_version_at_issue: number;
  revoked_at?: string;
  revoked_by?: string;
  status: string;
  subject_id: string;
  updated_at: string;
};

export type IdentityApiCredentialsWritable = {
  credentials: Array<IdentityApiCredentialWritable> | null;
};

export type IdentityCreateApiCredentialRequestWritable = {
  auth_method?: "private_key_jwt" | "client_secret";
  display_name: string;
  expires_at?: string;
  permissions: Array<string> | null;
};

export type IdentityCreateApiCredentialResponseWritable = {
  credential: IdentityApiCredentialWritable;
  issued_material: IdentityApiCredentialIssuedMaterial;
};

export type IdentityInviteMemberRequestWritable = {
  email: string;
  family_name?: string;
  given_name?: string;
  role_keys: Array<string> | null;
};

export type IdentityInviteMemberResponseWritable = {
  email: string;
  role_keys: Array<string> | null;
  status: string;
  user_id: string;
};

export type IdentityMemberWritable = {
  display_name: string;
  email: string;
  login_name: string;
  role_keys: Array<string> | null;
  state: string;
  user_id: string;
};

export type IdentityMemberCapabilitiesWritable = {
  catalog: Array<IdentityMemberCapability> | null;
  document: IdentityMemberCapabilitiesDocument;
};

export type IdentityMembersWritable = {
  members: Array<IdentityMemberWritable> | null;
};

export type IdentityOrganizationWritable = {
  caller: IdentityMemberWritable;
  member_capabilities: IdentityMemberCapabilitiesDocument;
  name: string;
  org_acl_version: number;
  org_id: string;
  permissions: Array<string> | null;
};

export type IdentityPutMemberCapabilitiesRequestWritable = {
  enabled_keys: Array<string> | null;
  version: number;
};

export type IdentityRollApiCredentialRequestWritable = {
  auth_method?: "private_key_jwt" | "client_secret";
};

export type IdentityRollApiCredentialResponseWritable = {
  credential: IdentityApiCredentialWritable;
  issued_material: IdentityApiCredentialIssuedMaterial;
};

export type IdentityUpdateMemberRolesRequestWritable = {
  expected_org_acl_version: number;
  expected_role_keys: Array<string> | null;
  role_keys: Array<string> | null;
};

export type GetOrganizationData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/organization";
};

export type GetOrganizationErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetOrganizationError = GetOrganizationErrors[keyof GetOrganizationErrors];

export type GetOrganizationResponses = {
  /**
   * OK
   */
  200: IdentityOrganization;
};

export type GetOrganizationResponse = GetOrganizationResponses[keyof GetOrganizationResponses];

export type ListApiCredentialsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/organization/api-credentials";
};

export type ListApiCredentialsErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ListApiCredentialsError = ListApiCredentialsErrors[keyof ListApiCredentialsErrors];

export type ListApiCredentialsResponses = {
  /**
   * OK
   */
  200: IdentityApiCredentials;
};

export type ListApiCredentialsResponse =
  ListApiCredentialsResponses[keyof ListApiCredentialsResponses];

export type CreateApiCredentialData = {
  body: IdentityCreateApiCredentialRequestWritable;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path?: never;
  query?: never;
  url: "/api/v1/organization/api-credentials";
};

export type CreateApiCredentialErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type CreateApiCredentialError = CreateApiCredentialErrors[keyof CreateApiCredentialErrors];

export type CreateApiCredentialResponses = {
  /**
   * Created
   */
  201: IdentityCreateApiCredentialResponse;
};

export type CreateApiCredentialResponse =
  CreateApiCredentialResponses[keyof CreateApiCredentialResponses];

export type RevokeApiCredentialData = {
  body?: never;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path: {
    /**
     * Forge Metal API credential ID
     */
    credential_id: string;
  };
  query?: never;
  url: "/api/v1/organization/api-credentials/{credential_id}";
};

export type RevokeApiCredentialErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type RevokeApiCredentialError = RevokeApiCredentialErrors[keyof RevokeApiCredentialErrors];

export type RevokeApiCredentialResponses = {
  /**
   * OK
   */
  200: IdentityApiCredential;
};

export type RevokeApiCredentialResponse =
  RevokeApiCredentialResponses[keyof RevokeApiCredentialResponses];

export type GetApiCredentialData = {
  body?: never;
  path: {
    /**
     * Forge Metal API credential ID
     */
    credential_id: string;
  };
  query?: never;
  url: "/api/v1/organization/api-credentials/{credential_id}";
};

export type GetApiCredentialErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetApiCredentialError = GetApiCredentialErrors[keyof GetApiCredentialErrors];

export type GetApiCredentialResponses = {
  /**
   * OK
   */
  200: IdentityApiCredential;
};

export type GetApiCredentialResponse = GetApiCredentialResponses[keyof GetApiCredentialResponses];

export type RollApiCredentialData = {
  body: IdentityRollApiCredentialRequestWritable;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path: {
    /**
     * Forge Metal API credential ID
     */
    credential_id: string;
  };
  query?: never;
  url: "/api/v1/organization/api-credentials/{credential_id}/roll";
};

export type RollApiCredentialErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type RollApiCredentialError = RollApiCredentialErrors[keyof RollApiCredentialErrors];

export type RollApiCredentialResponses = {
  /**
   * OK
   */
  200: IdentityRollApiCredentialResponse;
};

export type RollApiCredentialResponse =
  RollApiCredentialResponses[keyof RollApiCredentialResponses];

export type GetOrganizationMemberCapabilitiesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/organization/member-capabilities";
};

export type GetOrganizationMemberCapabilitiesErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type GetOrganizationMemberCapabilitiesError =
  GetOrganizationMemberCapabilitiesErrors[keyof GetOrganizationMemberCapabilitiesErrors];

export type GetOrganizationMemberCapabilitiesResponses = {
  /**
   * OK
   */
  200: IdentityMemberCapabilities;
};

export type GetOrganizationMemberCapabilitiesResponse =
  GetOrganizationMemberCapabilitiesResponses[keyof GetOrganizationMemberCapabilitiesResponses];

export type PutOrganizationMemberCapabilitiesData = {
  body: IdentityPutMemberCapabilitiesRequestWritable;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path?: never;
  query?: never;
  url: "/api/v1/organization/member-capabilities";
};

export type PutOrganizationMemberCapabilitiesErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type PutOrganizationMemberCapabilitiesError =
  PutOrganizationMemberCapabilitiesErrors[keyof PutOrganizationMemberCapabilitiesErrors];

export type PutOrganizationMemberCapabilitiesResponses = {
  /**
   * OK
   */
  200: IdentityMemberCapabilities;
};

export type PutOrganizationMemberCapabilitiesResponse =
  PutOrganizationMemberCapabilitiesResponses[keyof PutOrganizationMemberCapabilitiesResponses];

export type ListOrganizationMembersData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/organization/members";
};

export type ListOrganizationMembersErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type ListOrganizationMembersError =
  ListOrganizationMembersErrors[keyof ListOrganizationMembersErrors];

export type ListOrganizationMembersResponses = {
  /**
   * OK
   */
  200: IdentityMembers;
};

export type ListOrganizationMembersResponse =
  ListOrganizationMembersResponses[keyof ListOrganizationMembersResponses];

export type InviteOrganizationMemberData = {
  body: IdentityInviteMemberRequestWritable;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path?: never;
  query?: never;
  url: "/api/v1/organization/members";
};

export type InviteOrganizationMemberErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type InviteOrganizationMemberError =
  InviteOrganizationMemberErrors[keyof InviteOrganizationMemberErrors];

export type InviteOrganizationMemberResponses = {
  /**
   * Created
   */
  201: IdentityInviteMemberResponse;
};

export type InviteOrganizationMemberResponse =
  InviteOrganizationMemberResponses[keyof InviteOrganizationMemberResponses];

export type UpdateOrganizationMemberRolesData = {
  body: IdentityUpdateMemberRolesRequestWritable;
  headers: {
    /**
     * Stable caller-provided key used to make this mutation retry-safe.
     */
    "Idempotency-Key": string;
  };
  path: {
    /**
     * Zitadel user ID
     */
    user_id: string;
  };
  query?: never;
  url: "/api/v1/organization/members/{user_id}/roles";
};

export type UpdateOrganizationMemberRolesErrors = {
  /**
   * Error
   */
  default: ErrorModel;
};

export type UpdateOrganizationMemberRolesError =
  UpdateOrganizationMemberRolesErrors[keyof UpdateOrganizationMemberRolesErrors];

export type UpdateOrganizationMemberRolesResponses = {
  /**
   * OK
   */
  200: IdentityMember;
};

export type UpdateOrganizationMemberRolesResponse =
  UpdateOrganizationMemberRolesResponses[keyof UpdateOrganizationMemberRolesResponses];
