load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "verself-deploy_lib",
    srcs = [
        "check.go",
        "main.go",
        "run.go",
        "status.go",
        "validate.go",
    ],
    importpath = "github.com/verself/deployment-tools/cmd/verself-deploy",
    visibility = ["//visibility:private"],
    deps = [
        "//src/services/deployment-service/deploycontract",
        "//src/services/deployment-service/siteconfig",
    ],
)

go_binary(
    name = "verself-deploy",
    embed = [":verself-deploy_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "verself-deploy_test",
    srcs = [
        "check_test.go",
        "run_test.go",
        "status_test.go",
    ],
    data = glob(["*.go"]),
    embed = [":verself-deploy_lib"],
)
