package(default_visibility = ["//visibility:public"])

filegroup(
    name = "role_sources",
    srcs = glob(
        [
            "*/defaults/**",
            "*/deploy/**",
            "*/files/**",
            "*/handlers/**",
            "*/meta/**",
            "*/migrations/**",
            "*/tasks/**",
            "*/templates/**",
            "*/vars/**",
        ],
        allow_empty = True,
    ) + [
        "//src/infrastructure-components/clickhouse:role_sources",
        "//src/infrastructure-components/haproxy:role_sources",
        "//src/infrastructure-components/nats:role_sources",
        "//src/infrastructure-components/nftables:role_sources",
        "//src/infrastructure-components/nomad-observer:role_sources",
        "//src/infrastructure-components/openbao:role_sources",
        "//src/infrastructure-components/otelcol:role_sources",
        "//src/infrastructure-components/pomerium:role_sources",
        "//src/infrastructure-components/postgresql:role_sources",
        "//src/infrastructure-components/stalwart:role_sources",
        "//src/infrastructure-components/tigerbeetle:role_sources",
        "//src/infrastructure-components/zitadel:role_sources",
        "//src/infrastructure-components/zot:role_sources",
    ],
)
