load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "verself_smithy_ir_plugin",
    srcs = glob(["java/**/*.java"]),
    resource_strip_prefix = "src/smithy/plugins/ir/resources",
    resources = glob(["resources/**"]),
    deps = [
        "@maven//:software_amazon_smithy_smithy_build",
        "@maven//:software_amazon_smithy_smithy_model",
        "@maven//:software_amazon_smithy_smithy_utils",
    ],
)
