---
- name: Check if identity-service unit exists
  listen: restart identity-service
  ansible.builtin.stat:
    path: /etc/systemd/system/identity-service.service
  register: identity_service_unit_file

- name: Restart identity-service
  listen: restart identity-service
  ansible.builtin.systemd:
    daemon_reload: true
    name: identity-service
    state: restarted
  when: identity_service_unit_file.stat.exists

- name: Reload nftables for identity-service
  listen: reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: reloaded
