---
secrets_service_auth_issuer_url: "https://auth.{{ forge_metal_domain }}"
secrets_service_auth_jwks_url: "http://{{ services.zitadel.host }}:{{ services.zitadel.port }}/oauth/v2/keys"
secrets_service_auth_project_name: secrets-service
secrets_service_openbao_addr: "https://{{ services.openbao.host }}:{{ services.openbao.port }}"
secrets_service_openbao_kv_prefix: kv
secrets_service_openbao_transit_prefix: transit
secrets_service_openbao_jwt_prefix: jwt
secrets_service_billing_url: "https://{{ services.billing.host }}:{{ services.billing.internal_port }}"
