load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "seed",
    srcs = ["archive.go"],
    importpath = "github.com/verself/guardian-specification/cli/internal/seed",
    visibility = ["//src/guardian-specification/cli:__subpackages__"],
    deps = ["@com_github_klauspost_compress//zstd"],
)

go_test(
    name = "seed_test",
    srcs = ["archive_test.go"],
    embed = [":seed"],
)
