load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "client",
    srcs = [
        "authorization.go",
        "transport.go",
    ],
    importpath = "github.com/verself/iam-service/client",
    visibility = [
        "//src/services:__subpackages__",
        "//src/tools/operator/cmd/discovery-canary:__pkg__",
    ],
    deps = [
        "//src/services/service-runtime/go/auth",
        "//src/services/service-runtime/go/iam",
    ],
)
