load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "distribution-release_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/distribution-service/cmd/distribution-release",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "distribution-release",
    embed = [":distribution-release_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "distribution-release_test",
    srcs = ["main_test.go"],
    embed = [":distribution-release_lib"],
)
