load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "sops-init_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/dev-tools/cmd/sops-init",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "sops-init",
    embed = [":sops-init_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "sops-init_test",
    srcs = ["main_test.go"],
    embed = [":sops-init_lib"],
)
