---
- name: Check if projects-service unit exists
  listen: restart projects-service
  ansible.builtin.stat:
    path: /etc/systemd/system/projects-service.service
  register: projects_service_unit_file

- name: Restart projects-service
  listen: restart projects-service
  ansible.builtin.systemd:
    daemon_reload: true
    name: projects-service
    state: restarted
  when: projects_service_unit_file.stat.exists

- name: Reload nftables for projects-service
  listen: reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: reloaded
