load("//src/smithy/build:ir_go.bzl", "verself_ir_openapi_specs")

verself_ir_openapi_specs(
    name = "billing_openapi",
    internal_ir = "//src/smithy/models/verself:billing_internal_ir",
    internal_server_url = "https://127.0.0.1:4255",
    public_ir = "//src/smithy/models/verself:billing_public_ir",
    public_server_url = "https://billing.api.verself.sh",
)
