---
- name: Restart HyperDX API
  listen: restart hyperdx-api
  ansible.builtin.systemd:
    daemon_reload: true
    name: hyperdx-api
    state: restarted

- name: Restart HyperDX App
  listen: restart hyperdx-app
  ansible.builtin.systemd:
    daemon_reload: true
    name: hyperdx-app
    state: restarted

- name: Restart MongoDB
  listen: restart mongod
  ansible.builtin.systemd:
    daemon_reload: true
    name: mongod
    state: restarted
