---
- name: Reload systemd
  listen: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Caddy
  listen: restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
