// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignProviderDemandToRunnerFromDemand = `-- name: AssignProviderDemandToRunnerFromDemand :execrows
WITH source AS (
    SELECT runner_id, runner_name, jit_config_sha256, sandbox_allocation_id,
           sandbox_execution_id, sandbox_attempt_id
    FROM github_provider_demands
    WHERE github_provider_demands.provider_job_id = $3
)
UPDATE github_provider_demands target
SET runner_id = source.runner_id,
    runner_name = source.runner_name,
    jit_config_sha256 = source.jit_config_sha256,
    sandbox_allocation_id = source.sandbox_allocation_id,
    sandbox_execution_id = source.sandbox_execution_id,
    sandbox_attempt_id = source.sandbox_attempt_id,
    state = 'sandbox_submitted',
    failure_reason = '',
    updated_at = $1
FROM source
WHERE target.provider_job_id = $2
`

type AssignProviderDemandToRunnerFromDemandParams struct {
	UpdatedAt         pgtype.Timestamptz
	ToProviderJobID   int64
	FromProviderJobID int64
}

func (q *Queries) AssignProviderDemandToRunnerFromDemand(ctx context.Context, arg AssignProviderDemandToRunnerFromDemandParams) (int64, error) {
	result, err := q.db.Exec(ctx, assignProviderDemandToRunnerFromDemand, arg.UpdatedAt, arg.ToProviderJobID, arg.FromProviderJobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimProviderDemandForJIT = `-- name: ClaimProviderDemandForJIT :one
UPDATE github_provider_demands
SET state = 'jit_requested',
    failure_reason = '',
    claimed_at = $1,
    updated_at = $1
WHERE github_provider_demands.provider_job_id = $2
  AND github_provider_demands.state IN ('demand_recorded', 'jit_failed', 'sandbox_failed')
  AND (
      SELECT count(*)
      FROM github_runner_registrations active
      WHERE active.provider_repository_id = github_provider_demands.provider_repository_id
        AND active.runner_class = github_provider_demands.runner_class
        AND active.provider_job_id <> github_provider_demands.provider_job_id
        AND active.state IN ('jit_created', 'sandbox_submitted')
        AND NOT EXISTS (
            SELECT 1
            FROM github_workflow_jobs active_job
            WHERE active_job.provider_job_id = active.provider_job_id
              AND active_job.status = 'completed'
        )
  ) < $3
RETURNING demand_id, provider_job_id, provider_installation_id, provider_repository_id,
          repository_full_name, provider_run_id, provider_run_attempt, runner_name,
          runner_class, job_shape_id, trust_class, state
`

type ClaimProviderDemandForJITParams struct {
	ClaimedAt                        pgtype.Timestamptz
	ProviderJobID                    int64
	RepositoryRunnerClassActiveLimit int64
}

type ClaimProviderDemandForJITRow struct {
	DemandID               pgtype.UUID
	ProviderJobID          int64
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	RepositoryFullName     string
	ProviderRunID          int64
	ProviderRunAttempt     int64
	RunnerName             string
	RunnerClass            string
	JobShapeID             string
	TrustClass             string
	State                  string
}

func (q *Queries) ClaimProviderDemandForJIT(ctx context.Context, arg ClaimProviderDemandForJITParams) (ClaimProviderDemandForJITRow, error) {
	row := q.db.QueryRow(ctx, claimProviderDemandForJIT, arg.ClaimedAt, arg.ProviderJobID, arg.RepositoryRunnerClassActiveLimit)
	var i ClaimProviderDemandForJITRow
	err := row.Scan(
		&i.DemandID,
		&i.ProviderJobID,
		&i.ProviderInstallationID,
		&i.ProviderRepositoryID,
		&i.RepositoryFullName,
		&i.ProviderRunID,
		&i.ProviderRunAttempt,
		&i.RunnerName,
		&i.RunnerClass,
		&i.JobShapeID,
		&i.TrustClass,
		&i.State,
	)
	return i, err
}

const countActiveRunnerRegistrationsForRunnerClass = `-- name: CountActiveRunnerRegistrationsForRunnerClass :one
SELECT count(*)::bigint
FROM github_runner_registrations
WHERE github_runner_registrations.provider_repository_id = $1
  AND github_runner_registrations.runner_class = $2
  AND github_runner_registrations.state IN ('jit_created', 'sandbox_submitted')
  AND NOT EXISTS (
      SELECT 1
      FROM github_workflow_jobs active_job
      WHERE active_job.provider_job_id = github_runner_registrations.provider_job_id
        AND active_job.status = 'completed'
  )
`

type CountActiveRunnerRegistrationsForRunnerClassParams struct {
	ProviderRepositoryID int64
	RunnerClass          string
}

func (q *Queries) CountActiveRunnerRegistrationsForRunnerClass(ctx context.Context, arg CountActiveRunnerRegistrationsForRunnerClassParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRunnerRegistrationsForRunnerClass, arg.ProviderRepositoryID, arg.RunnerClass)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const ensureProviderDemand = `-- name: EnsureProviderDemand :one
INSERT INTO github_provider_demands (
    demand_id,
    provider_job_id,
    provider_installation_id,
    provider_repository_id,
    repository_full_name,
    provider_run_id,
    provider_run_attempt,
    job_shape_id,
    trust_class,
    runner_class,
    runner_name,
    state,
    last_delivery_id,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    'demand_recorded',
    $12,
    $13,
    $13
)
ON CONFLICT (provider_job_id) DO UPDATE SET
    provider_installation_id = EXCLUDED.provider_installation_id,
    provider_repository_id = EXCLUDED.provider_repository_id,
    repository_full_name = EXCLUDED.repository_full_name,
    provider_run_id = EXCLUDED.provider_run_id,
    provider_run_attempt = EXCLUDED.provider_run_attempt,
    job_shape_id = COALESCE(NULLIF(EXCLUDED.job_shape_id, ''), github_provider_demands.job_shape_id),
    trust_class = COALESCE(NULLIF(EXCLUDED.trust_class, ''), github_provider_demands.trust_class),
    runner_class = COALESCE(NULLIF(EXCLUDED.runner_class, ''), github_provider_demands.runner_class),
    last_delivery_id = COALESCE(NULLIF(EXCLUDED.last_delivery_id, ''), github_provider_demands.last_delivery_id),
    updated_at = EXCLUDED.updated_at
RETURNING demand_id, provider_job_id, runner_name, runner_id, runner_class, job_shape_id, trust_class,
          state, jit_config_sha256, sandbox_allocation_id, sandbox_execution_id, sandbox_attempt_id
`

type EnsureProviderDemandParams struct {
	DemandID               pgtype.UUID
	ProviderJobID          int64
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	RepositoryFullName     string
	ProviderRunID          int64
	ProviderRunAttempt     int64
	JobShapeID             string
	TrustClass             string
	RunnerClass            string
	RunnerName             string
	LastDeliveryID         string
	UpdatedAt              pgtype.Timestamptz
}

type EnsureProviderDemandRow struct {
	DemandID            pgtype.UUID
	ProviderJobID       int64
	RunnerName          string
	RunnerID            int64
	RunnerClass         string
	JobShapeID          string
	TrustClass          string
	State               string
	JitConfigSha256     string
	SandboxAllocationID pgtype.UUID
	SandboxExecutionID  pgtype.UUID
	SandboxAttemptID    pgtype.UUID
}

func (q *Queries) EnsureProviderDemand(ctx context.Context, arg EnsureProviderDemandParams) (EnsureProviderDemandRow, error) {
	row := q.db.QueryRow(ctx, ensureProviderDemand,
		arg.DemandID,
		arg.ProviderJobID,
		arg.ProviderInstallationID,
		arg.ProviderRepositoryID,
		arg.RepositoryFullName,
		arg.ProviderRunID,
		arg.ProviderRunAttempt,
		arg.JobShapeID,
		arg.TrustClass,
		arg.RunnerClass,
		arg.RunnerName,
		arg.LastDeliveryID,
		arg.UpdatedAt,
	)
	var i EnsureProviderDemandRow
	err := row.Scan(
		&i.DemandID,
		&i.ProviderJobID,
		&i.RunnerName,
		&i.RunnerID,
		&i.RunnerClass,
		&i.JobShapeID,
		&i.TrustClass,
		&i.State,
		&i.JitConfigSha256,
		&i.SandboxAllocationID,
		&i.SandboxExecutionID,
		&i.SandboxAttemptID,
	)
	return i, err
}

const getProviderDemandForJob = `-- name: GetProviderDemandForJob :one
SELECT demand_id, provider_job_id, provider_installation_id, provider_repository_id,
       repository_full_name, provider_run_id, provider_run_attempt, runner_name,
       runner_id, runner_class, job_shape_id, trust_class, state, sandbox_allocation_id,
       sandbox_execution_id, sandbox_attempt_id
FROM github_provider_demands
WHERE provider_job_id = $1
`

type GetProviderDemandForJobParams struct {
	ProviderJobID int64
}

type GetProviderDemandForJobRow struct {
	DemandID               pgtype.UUID
	ProviderJobID          int64
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	RepositoryFullName     string
	ProviderRunID          int64
	ProviderRunAttempt     int64
	RunnerName             string
	RunnerID               int64
	RunnerClass            string
	JobShapeID             string
	TrustClass             string
	State                  string
	SandboxAllocationID    pgtype.UUID
	SandboxExecutionID     pgtype.UUID
	SandboxAttemptID       pgtype.UUID
}

func (q *Queries) GetProviderDemandForJob(ctx context.Context, arg GetProviderDemandForJobParams) (GetProviderDemandForJobRow, error) {
	row := q.db.QueryRow(ctx, getProviderDemandForJob, arg.ProviderJobID)
	var i GetProviderDemandForJobRow
	err := row.Scan(
		&i.DemandID,
		&i.ProviderJobID,
		&i.ProviderInstallationID,
		&i.ProviderRepositoryID,
		&i.RepositoryFullName,
		&i.ProviderRunID,
		&i.ProviderRunAttempt,
		&i.RunnerName,
		&i.RunnerID,
		&i.RunnerClass,
		&i.JobShapeID,
		&i.TrustClass,
		&i.State,
		&i.SandboxAllocationID,
		&i.SandboxExecutionID,
		&i.SandboxAttemptID,
	)
	return i, err
}

const getRunnerRegistrationByRunnerName = `-- name: GetRunnerRegistrationByRunnerName :one
SELECT provider_job_id, provider_installation_id, provider_repository_id, runner_id,
       runner_name, runner_class, sandbox_allocation_id, sandbox_execution_id,
       sandbox_attempt_id, state
FROM github_runner_registrations
WHERE runner_name = $1
`

type GetRunnerRegistrationByRunnerNameParams struct {
	RunnerName string
}

type GetRunnerRegistrationByRunnerNameRow struct {
	ProviderJobID          int64
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	RunnerID               int64
	RunnerName             string
	RunnerClass            string
	SandboxAllocationID    pgtype.UUID
	SandboxExecutionID     pgtype.UUID
	SandboxAttemptID       pgtype.UUID
	State                  string
}

func (q *Queries) GetRunnerRegistrationByRunnerName(ctx context.Context, arg GetRunnerRegistrationByRunnerNameParams) (GetRunnerRegistrationByRunnerNameRow, error) {
	row := q.db.QueryRow(ctx, getRunnerRegistrationByRunnerName, arg.RunnerName)
	var i GetRunnerRegistrationByRunnerNameRow
	err := row.Scan(
		&i.ProviderJobID,
		&i.ProviderInstallationID,
		&i.ProviderRepositoryID,
		&i.RunnerID,
		&i.RunnerName,
		&i.RunnerClass,
		&i.SandboxAllocationID,
		&i.SandboxExecutionID,
		&i.SandboxAttemptID,
		&i.State,
	)
	return i, err
}

const getRunnerRegistrationForJob = `-- name: GetRunnerRegistrationForJob :one
SELECT provider_job_id, provider_installation_id, provider_repository_id, runner_id,
       runner_name, runner_class, sandbox_allocation_id, sandbox_execution_id,
       sandbox_attempt_id, state
FROM github_runner_registrations
WHERE provider_job_id = $1
`

type GetRunnerRegistrationForJobParams struct {
	ProviderJobID int64
}

type GetRunnerRegistrationForJobRow struct {
	ProviderJobID          int64
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	RunnerID               int64
	RunnerName             string
	RunnerClass            string
	SandboxAllocationID    pgtype.UUID
	SandboxExecutionID     pgtype.UUID
	SandboxAttemptID       pgtype.UUID
	State                  string
}

func (q *Queries) GetRunnerRegistrationForJob(ctx context.Context, arg GetRunnerRegistrationForJobParams) (GetRunnerRegistrationForJobRow, error) {
	row := q.db.QueryRow(ctx, getRunnerRegistrationForJob, arg.ProviderJobID)
	var i GetRunnerRegistrationForJobRow
	err := row.Scan(
		&i.ProviderJobID,
		&i.ProviderInstallationID,
		&i.ProviderRepositoryID,
		&i.RunnerID,
		&i.RunnerName,
		&i.RunnerClass,
		&i.SandboxAllocationID,
		&i.SandboxExecutionID,
		&i.SandboxAttemptID,
		&i.State,
	)
	return i, err
}

const insertTerminalJobEvidence = `-- name: InsertTerminalJobEvidence :one
INSERT INTO github_terminal_job_evidence (
    terminal_evidence_id,
    provider_job_id,
    provider_installation_id,
    provider_repository_id,
    provider_run_id,
    provider_run_attempt,
    sandbox_allocation_id,
    sandbox_execution_id,
    sandbox_attempt_id,
    runner_id,
    runner_name,
    job_shape_id,
    trust_class,
    status,
    conclusion,
    source,
    delivery_id,
    observed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18
)
ON CONFLICT (provider_job_id) DO UPDATE SET
    provider_installation_id = EXCLUDED.provider_installation_id,
    provider_repository_id = EXCLUDED.provider_repository_id,
    status = EXCLUDED.status,
    conclusion = EXCLUDED.conclusion,
    sandbox_allocation_id = EXCLUDED.sandbox_allocation_id,
    sandbox_execution_id = EXCLUDED.sandbox_execution_id,
    sandbox_attempt_id = EXCLUDED.sandbox_attempt_id,
    runner_id = EXCLUDED.runner_id,
    runner_name = EXCLUDED.runner_name,
    job_shape_id = EXCLUDED.job_shape_id,
    trust_class = EXCLUDED.trust_class,
    source = EXCLUDED.source,
    delivery_id = EXCLUDED.delivery_id,
    observed_at = EXCLUDED.observed_at
RETURNING terminal_evidence_id
`

type InsertTerminalJobEvidenceParams struct {
	TerminalEvidenceID     pgtype.UUID
	ProviderJobID          int64
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	ProviderRunID          int64
	ProviderRunAttempt     int64
	SandboxAllocationID    pgtype.UUID
	SandboxExecutionID     pgtype.UUID
	SandboxAttemptID       pgtype.UUID
	RunnerID               int64
	RunnerName             string
	JobShapeID             string
	TrustClass             string
	Status                 string
	Conclusion             string
	Source                 string
	DeliveryID             string
	ObservedAt             pgtype.Timestamptz
}

func (q *Queries) InsertTerminalJobEvidence(ctx context.Context, arg InsertTerminalJobEvidenceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertTerminalJobEvidence,
		arg.TerminalEvidenceID,
		arg.ProviderJobID,
		arg.ProviderInstallationID,
		arg.ProviderRepositoryID,
		arg.ProviderRunID,
		arg.ProviderRunAttempt,
		arg.SandboxAllocationID,
		arg.SandboxExecutionID,
		arg.SandboxAttemptID,
		arg.RunnerID,
		arg.RunnerName,
		arg.JobShapeID,
		arg.TrustClass,
		arg.Status,
		arg.Conclusion,
		arg.Source,
		arg.DeliveryID,
		arg.ObservedAt,
	)
	var terminal_evidence_id pgtype.UUID
	err := row.Scan(&terminal_evidence_id)
	return terminal_evidence_id, err
}

const listQueuedWorkflowJobsForRunnerSubmission = `-- name: ListQueuedWorkflowJobsForRunnerSubmission :many
WITH candidates AS (
    SELECT
        j.provider_job_id,
        j.provider_installation_id,
        j.provider_repository_id,
        j.repository_full_name,
        j.provider_run_id,
        j.provider_run_attempt,
        j.job_name,
        j.head_sha,
        j.head_branch,
        j.workflow_name,
        j.status,
        j.conclusion,
        j.labels_json,
        j.started_at,
        j.completed_at,
        COALESCE(d.state, '')::text AS registration_state,
        d.updated_at AS registration_updated_at,
        COALESCE((
            SELECT label
            FROM jsonb_array_elements_text(j.labels_json) AS label
            WHERE label LIKE $2 || '%'
            ORDER BY label
            LIMIT 1
        ), '')::text AS runner_class
    FROM github_workflow_jobs j
    LEFT JOIN github_provider_demands d ON d.provider_job_id = j.provider_job_id
    WHERE j.status = 'queued'
      AND (
            d.provider_job_id IS NULL
         OR d.state IN ('demand_recorded', 'jit_failed', 'sandbox_failed')
      )
)
SELECT DISTINCT ON (provider_repository_id, runner_class)
    provider_job_id,
    provider_installation_id,
    provider_repository_id,
    repository_full_name,
    provider_run_id,
    provider_run_attempt,
    job_name,
    head_sha,
    head_branch,
    workflow_name,
    status,
    conclusion,
    labels_json,
    started_at,
    completed_at,
    registration_state,
    registration_updated_at
FROM candidates
WHERE runner_class <> ''
ORDER BY provider_repository_id ASC, runner_class ASC, provider_job_id ASC
LIMIT $1
`

type ListQueuedWorkflowJobsForRunnerSubmissionParams struct {
	LimitCount        int32
	RunnerClassPrefix pgtype.Text
}

type ListQueuedWorkflowJobsForRunnerSubmissionRow struct {
	ProviderJobID          int64
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	RepositoryFullName     string
	ProviderRunID          int64
	ProviderRunAttempt     int64
	JobName                string
	HeadSha                string
	HeadBranch             string
	WorkflowName           string
	Status                 string
	Conclusion             string
	LabelsJson             []byte
	StartedAt              pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	RegistrationState      string
	RegistrationUpdatedAt  pgtype.Timestamptz
}

func (q *Queries) ListQueuedWorkflowJobsForRunnerSubmission(ctx context.Context, arg ListQueuedWorkflowJobsForRunnerSubmissionParams) ([]ListQueuedWorkflowJobsForRunnerSubmissionRow, error) {
	rows, err := q.db.Query(ctx, listQueuedWorkflowJobsForRunnerSubmission, arg.LimitCount, arg.RunnerClassPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueuedWorkflowJobsForRunnerSubmissionRow{}
	for rows.Next() {
		var i ListQueuedWorkflowJobsForRunnerSubmissionRow
		if err := rows.Scan(
			&i.ProviderJobID,
			&i.ProviderInstallationID,
			&i.ProviderRepositoryID,
			&i.RepositoryFullName,
			&i.ProviderRunID,
			&i.ProviderRunAttempt,
			&i.JobName,
			&i.HeadSha,
			&i.HeadBranch,
			&i.WorkflowName,
			&i.Status,
			&i.Conclusion,
			&i.LabelsJson,
			&i.StartedAt,
			&i.CompletedAt,
			&i.RegistrationState,
			&i.RegistrationUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReadyDeliveries = `-- name: LockReadyDeliveries :many
UPDATE github_webhook_deliveries AS d
SET
    state = 'processing',
    attempt_count = d.attempt_count + 1,
    processing_started_at = $1,
    updated_at = $1
FROM (
    SELECT delivery_id
    FROM github_webhook_deliveries
    WHERE state IN ('verified', 'retryable')
      AND (next_attempt_at IS NULL OR next_attempt_at <= $1)
    ORDER BY received_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
) AS ready
WHERE d.delivery_id = ready.delivery_id
RETURNING d.delivery_id, d.event_name, d.action, d.payload_json, d.provider_installation_id,
          d.provider_repository_id, d.repository_full_name, d.provider_run_id,
          d.provider_run_attempt, d.provider_job_id, d.attempt_count
`

type LockReadyDeliveriesParams struct {
	LockedAt   pgtype.Timestamptz
	LimitCount int32
}

type LockReadyDeliveriesRow struct {
	DeliveryID             string
	EventName              string
	Action                 string
	PayloadJson            []byte
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	RepositoryFullName     string
	ProviderRunID          int64
	ProviderRunAttempt     int64
	ProviderJobID          int64
	AttemptCount           int32
}

func (q *Queries) LockReadyDeliveries(ctx context.Context, arg LockReadyDeliveriesParams) ([]LockReadyDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, lockReadyDeliveries, arg.LockedAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockReadyDeliveriesRow{}
	for rows.Next() {
		var i LockReadyDeliveriesRow
		if err := rows.Scan(
			&i.DeliveryID,
			&i.EventName,
			&i.Action,
			&i.PayloadJson,
			&i.ProviderInstallationID,
			&i.ProviderRepositoryID,
			&i.RepositoryFullName,
			&i.ProviderRunID,
			&i.ProviderRunAttempt,
			&i.ProviderJobID,
			&i.AttemptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :exec
UPDATE github_webhook_deliveries
SET state = 'failed',
    failure_reason = $1,
    processed_at = $2,
    updated_at = $2
WHERE delivery_id = $3
`

type MarkDeliveryFailedParams struct {
	FailureReason string
	FailedAt      pgtype.Timestamptz
	DeliveryID    string
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryFailed, arg.FailureReason, arg.FailedAt, arg.DeliveryID)
	return err
}

const markDeliveryIgnored = `-- name: MarkDeliveryIgnored :exec
UPDATE github_webhook_deliveries
SET state = 'ignored',
    failure_reason = $1,
    processed_at = $2,
    updated_at = $2
WHERE delivery_id = $3
`

type MarkDeliveryIgnoredParams struct {
	FailureReason string
	ProcessedAt   pgtype.Timestamptz
	DeliveryID    string
}

func (q *Queries) MarkDeliveryIgnored(ctx context.Context, arg MarkDeliveryIgnoredParams) error {
	_, err := q.db.Exec(ctx, markDeliveryIgnored, arg.FailureReason, arg.ProcessedAt, arg.DeliveryID)
	return err
}

const markDeliveryProcessed = `-- name: MarkDeliveryProcessed :exec
UPDATE github_webhook_deliveries
SET state = 'processed',
    failure_reason = '',
    processed_at = $1,
    updated_at = $1
WHERE delivery_id = $2
`

type MarkDeliveryProcessedParams struct {
	ProcessedAt pgtype.Timestamptz
	DeliveryID  string
}

func (q *Queries) MarkDeliveryProcessed(ctx context.Context, arg MarkDeliveryProcessedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryProcessed, arg.ProcessedAt, arg.DeliveryID)
	return err
}

const markDeliveryRejected = `-- name: MarkDeliveryRejected :exec
INSERT INTO github_webhook_deliveries (
    delivery_id,
    event_name,
    action,
    state,
    failure_reason,
    payload_sha256,
    payload_json,
    received_at,
    verified_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    'rejected',
    $4,
    $5,
    $6,
    $7,
    $7,
    $7
)
ON CONFLICT (delivery_id) DO UPDATE SET
    state = 'rejected',
    failure_reason = EXCLUDED.failure_reason,
    updated_at = EXCLUDED.updated_at
WHERE github_webhook_deliveries.state = 'rejected'
  AND github_webhook_deliveries.payload_sha256 = EXCLUDED.payload_sha256
`

type MarkDeliveryRejectedParams struct {
	DeliveryID    string
	EventName     string
	Action        string
	FailureReason string
	PayloadSha256 string
	PayloadJson   []byte
	ReceivedAt    pgtype.Timestamptz
}

func (q *Queries) MarkDeliveryRejected(ctx context.Context, arg MarkDeliveryRejectedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryRejected,
		arg.DeliveryID,
		arg.EventName,
		arg.Action,
		arg.FailureReason,
		arg.PayloadSha256,
		arg.PayloadJson,
		arg.ReceivedAt,
	)
	return err
}

const markDeliveryRetryable = `-- name: MarkDeliveryRetryable :exec
UPDATE github_webhook_deliveries
SET state = 'retryable',
    failure_reason = $1,
    next_attempt_at = $2,
    updated_at = $3
WHERE delivery_id = $4
`

type MarkDeliveryRetryableParams struct {
	FailureReason string
	NextAttemptAt pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeliveryID    string
}

func (q *Queries) MarkDeliveryRetryable(ctx context.Context, arg MarkDeliveryRetryableParams) error {
	_, err := q.db.Exec(ctx, markDeliveryRetryable,
		arg.FailureReason,
		arg.NextAttemptAt,
		arg.UpdatedAt,
		arg.DeliveryID,
	)
	return err
}

const markProviderDemandFailed = `-- name: MarkProviderDemandFailed :exec
UPDATE github_provider_demands
SET state = $1,
    failure_reason = $2,
    updated_at = $3
WHERE provider_job_id = $4
`

type MarkProviderDemandFailedParams struct {
	State         string
	FailureReason string
	UpdatedAt     pgtype.Timestamptz
	ProviderJobID int64
}

func (q *Queries) MarkProviderDemandFailed(ctx context.Context, arg MarkProviderDemandFailedParams) error {
	_, err := q.db.Exec(ctx, markProviderDemandFailed,
		arg.State,
		arg.FailureReason,
		arg.UpdatedAt,
		arg.ProviderJobID,
	)
	return err
}

const markProviderDemandJITCreated = `-- name: MarkProviderDemandJITCreated :exec
UPDATE github_provider_demands
SET runner_id = $1,
    runner_name = $2,
    jit_config_sha256 = $3,
    state = 'jit_created',
    failure_reason = '',
    updated_at = $4
WHERE provider_job_id = $5
  AND state = 'jit_requested'
`

type MarkProviderDemandJITCreatedParams struct {
	RunnerID        int64
	RunnerName      string
	JitConfigSha256 string
	UpdatedAt       pgtype.Timestamptz
	ProviderJobID   int64
}

func (q *Queries) MarkProviderDemandJITCreated(ctx context.Context, arg MarkProviderDemandJITCreatedParams) error {
	_, err := q.db.Exec(ctx, markProviderDemandJITCreated,
		arg.RunnerID,
		arg.RunnerName,
		arg.JitConfigSha256,
		arg.UpdatedAt,
		arg.ProviderJobID,
	)
	return err
}

const markProviderDemandSandboxSubmitted = `-- name: MarkProviderDemandSandboxSubmitted :exec
UPDATE github_provider_demands
SET sandbox_allocation_id = $1,
    sandbox_execution_id = $2,
    sandbox_attempt_id = $3,
    runner_id = $4,
    runner_name = $5,
    state = 'sandbox_submitted',
    failure_reason = '',
    updated_at = $6
WHERE provider_job_id = $7
  AND state IN ('jit_created', 'sandbox_submitting', 'sandbox_failed')
`

type MarkProviderDemandSandboxSubmittedParams struct {
	SandboxAllocationID pgtype.UUID
	SandboxExecutionID  pgtype.UUID
	SandboxAttemptID    pgtype.UUID
	RunnerID            int64
	RunnerName          string
	UpdatedAt           pgtype.Timestamptz
	ProviderJobID       int64
}

func (q *Queries) MarkProviderDemandSandboxSubmitted(ctx context.Context, arg MarkProviderDemandSandboxSubmittedParams) error {
	_, err := q.db.Exec(ctx, markProviderDemandSandboxSubmitted,
		arg.SandboxAllocationID,
		arg.SandboxExecutionID,
		arg.SandboxAttemptID,
		arg.RunnerID,
		arg.RunnerName,
		arg.UpdatedAt,
		arg.ProviderJobID,
	)
	return err
}

const markProviderOutboxFailed = `-- name: MarkProviderOutboxFailed :exec
UPDATE github_provider_outbox
SET state = $1,
    failure_reason = $2,
    updated_at = $3
WHERE command_kind = $4
  AND command_sha256 = $5
`

type MarkProviderOutboxFailedParams struct {
	State         string
	FailureReason string
	UpdatedAt     pgtype.Timestamptz
	CommandKind   string
	CommandSha256 string
}

func (q *Queries) MarkProviderOutboxFailed(ctx context.Context, arg MarkProviderOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markProviderOutboxFailed,
		arg.State,
		arg.FailureReason,
		arg.UpdatedAt,
		arg.CommandKind,
		arg.CommandSha256,
	)
	return err
}

const markProviderOutboxProcessed = `-- name: MarkProviderOutboxProcessed :exec
UPDATE github_provider_outbox
SET state = 'processed',
    sandbox_execution_id = $1,
    sandbox_attempt_id = $2,
    processed_at = $3,
    failure_reason = '',
    updated_at = $3
WHERE command_kind = $4
  AND command_sha256 = $5
`

type MarkProviderOutboxProcessedParams struct {
	SandboxExecutionID pgtype.UUID
	SandboxAttemptID   pgtype.UUID
	ProcessedAt        pgtype.Timestamptz
	CommandKind        string
	CommandSha256      string
}

func (q *Queries) MarkProviderOutboxProcessed(ctx context.Context, arg MarkProviderOutboxProcessedParams) error {
	_, err := q.db.Exec(ctx, markProviderOutboxProcessed,
		arg.SandboxExecutionID,
		arg.SandboxAttemptID,
		arg.ProcessedAt,
		arg.CommandKind,
		arg.CommandSha256,
	)
	return err
}

const markRunnerRegistrationCleaned = `-- name: MarkRunnerRegistrationCleaned :exec
UPDATE github_runner_registrations
SET state = 'cleaned',
    updated_at = $1
WHERE provider_job_id = $2
`

type MarkRunnerRegistrationCleanedParams struct {
	UpdatedAt     pgtype.Timestamptz
	ProviderJobID int64
}

func (q *Queries) MarkRunnerRegistrationCleaned(ctx context.Context, arg MarkRunnerRegistrationCleanedParams) error {
	_, err := q.db.Exec(ctx, markRunnerRegistrationCleaned, arg.UpdatedAt, arg.ProviderJobID)
	return err
}

const markRunnerRegistrationFailed = `-- name: MarkRunnerRegistrationFailed :exec
UPDATE github_runner_registrations
SET state = 'failed',
    failure_reason = $1,
    updated_at = $2
WHERE provider_job_id = $3
`

type MarkRunnerRegistrationFailedParams struct {
	FailureReason string
	UpdatedAt     pgtype.Timestamptz
	ProviderJobID int64
}

func (q *Queries) MarkRunnerRegistrationFailed(ctx context.Context, arg MarkRunnerRegistrationFailedParams) error {
	_, err := q.db.Exec(ctx, markRunnerRegistrationFailed, arg.FailureReason, arg.UpdatedAt, arg.ProviderJobID)
	return err
}

const markRunnerRegistrationSubmitted = `-- name: MarkRunnerRegistrationSubmitted :exec
UPDATE github_runner_registrations
SET sandbox_allocation_id = $1,
    sandbox_execution_id = $2,
    sandbox_attempt_id = $3,
    runner_id = $4,
    runner_name = $5,
    state = 'sandbox_submitted',
    failure_reason = '',
    updated_at = $6
WHERE provider_job_id = $7
`

type MarkRunnerRegistrationSubmittedParams struct {
	SandboxAllocationID pgtype.UUID
	SandboxExecutionID  pgtype.UUID
	SandboxAttemptID    pgtype.UUID
	RunnerID            int64
	RunnerName          string
	UpdatedAt           pgtype.Timestamptz
	ProviderJobID       int64
}

func (q *Queries) MarkRunnerRegistrationSubmitted(ctx context.Context, arg MarkRunnerRegistrationSubmittedParams) error {
	_, err := q.db.Exec(ctx, markRunnerRegistrationSubmitted,
		arg.SandboxAllocationID,
		arg.SandboxExecutionID,
		arg.SandboxAttemptID,
		arg.RunnerID,
		arg.RunnerName,
		arg.UpdatedAt,
		arg.ProviderJobID,
	)
	return err
}

const recordWebhookDelivery = `-- name: RecordWebhookDelivery :one
INSERT INTO github_webhook_deliveries (
    delivery_id,
    event_name,
    action,
    state,
    payload_sha256,
    payload_json,
    provider_installation_id,
    provider_repository_id,
    repository_full_name,
    provider_run_id,
    provider_run_attempt,
    provider_job_id,
    received_at,
    verified_at,
    next_attempt_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    'verified',
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $12,
    $12
)
ON CONFLICT (delivery_id) DO UPDATE SET
    state = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN EXCLUDED.state
        ELSE github_webhook_deliveries.state
    END,
    event_name = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN EXCLUDED.event_name
        ELSE github_webhook_deliveries.event_name
    END,
    action = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN EXCLUDED.action
        ELSE github_webhook_deliveries.action
    END,
    failure_reason = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN ''
        ELSE github_webhook_deliveries.failure_reason
    END,
    payload_json = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN EXCLUDED.payload_json
        ELSE github_webhook_deliveries.payload_json
    END,
    provider_installation_id = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN EXCLUDED.provider_installation_id
        ELSE github_webhook_deliveries.provider_installation_id
    END,
    provider_repository_id = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN EXCLUDED.provider_repository_id
        ELSE github_webhook_deliveries.provider_repository_id
    END,
    repository_full_name = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN EXCLUDED.repository_full_name
        ELSE github_webhook_deliveries.repository_full_name
    END,
    provider_run_id = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN EXCLUDED.provider_run_id
        ELSE github_webhook_deliveries.provider_run_id
    END,
    provider_run_attempt = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN EXCLUDED.provider_run_attempt
        ELSE github_webhook_deliveries.provider_run_attempt
    END,
    provider_job_id = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN EXCLUDED.provider_job_id
        ELSE github_webhook_deliveries.provider_job_id
    END,
    verified_at = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN EXCLUDED.verified_at
        ELSE github_webhook_deliveries.verified_at
    END,
    next_attempt_at = CASE
        WHEN github_webhook_deliveries.state = 'rejected' THEN EXCLUDED.next_attempt_at
        ELSE github_webhook_deliveries.next_attempt_at
    END,
    updated_at = EXCLUDED.updated_at
WHERE github_webhook_deliveries.payload_sha256 = EXCLUDED.payload_sha256
RETURNING delivery_id, state, attempt_count, payload_sha256
`

type RecordWebhookDeliveryParams struct {
	DeliveryID             string
	EventName              string
	Action                 string
	PayloadSha256          string
	PayloadJson            []byte
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	RepositoryFullName     string
	ProviderRunID          int64
	ProviderRunAttempt     int64
	ProviderJobID          int64
	ReceivedAt             pgtype.Timestamptz
	VerifiedAt             pgtype.Timestamptz
}

type RecordWebhookDeliveryRow struct {
	DeliveryID    string
	State         string
	AttemptCount  int32
	PayloadSha256 string
}

func (q *Queries) RecordWebhookDelivery(ctx context.Context, arg RecordWebhookDeliveryParams) (RecordWebhookDeliveryRow, error) {
	row := q.db.QueryRow(ctx, recordWebhookDelivery,
		arg.DeliveryID,
		arg.EventName,
		arg.Action,
		arg.PayloadSha256,
		arg.PayloadJson,
		arg.ProviderInstallationID,
		arg.ProviderRepositoryID,
		arg.RepositoryFullName,
		arg.ProviderRunID,
		arg.ProviderRunAttempt,
		arg.ProviderJobID,
		arg.ReceivedAt,
		arg.VerifiedAt,
	)
	var i RecordWebhookDeliveryRow
	err := row.Scan(
		&i.DeliveryID,
		&i.State,
		&i.AttemptCount,
		&i.PayloadSha256,
	)
	return i, err
}

const resetProviderDemandAfterRunnerReassignment = `-- name: ResetProviderDemandAfterRunnerReassignment :execrows
UPDATE github_provider_demands
SET runner_id = 0,
    runner_name = $1,
    jit_config_sha256 = '',
    sandbox_allocation_id = NULL,
    sandbox_execution_id = NULL,
    sandbox_attempt_id = NULL,
    state = 'demand_recorded',
    failure_reason = $2,
    updated_at = $3
WHERE provider_job_id = $4
`

type ResetProviderDemandAfterRunnerReassignmentParams struct {
	RunnerName    string
	FailureReason string
	UpdatedAt     pgtype.Timestamptz
	ProviderJobID int64
}

func (q *Queries) ResetProviderDemandAfterRunnerReassignment(ctx context.Context, arg ResetProviderDemandAfterRunnerReassignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetProviderDemandAfterRunnerReassignment,
		arg.RunnerName,
		arg.FailureReason,
		arg.UpdatedAt,
		arg.ProviderJobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const swapProviderDemandRunnerAssignments = `-- name: SwapProviderDemandRunnerAssignments :execrows
WITH source AS (
    SELECT runner_id, runner_name, jit_config_sha256, sandbox_allocation_id,
           sandbox_execution_id, sandbox_attempt_id, state
    FROM github_provider_demands
    WHERE github_provider_demands.provider_job_id = $2
), target AS (
    SELECT runner_id, runner_name, jit_config_sha256, sandbox_allocation_id,
           sandbox_execution_id, sandbox_attempt_id, state
    FROM github_provider_demands
    WHERE github_provider_demands.provider_job_id = $1
)
UPDATE github_provider_demands demand
SET runner_id = CASE WHEN demand.provider_job_id = $1 THEN source.runner_id ELSE target.runner_id END,
    runner_name = CASE WHEN demand.provider_job_id = $1 THEN source.runner_name ELSE target.runner_name END,
    jit_config_sha256 = CASE WHEN demand.provider_job_id = $1 THEN source.jit_config_sha256 ELSE target.jit_config_sha256 END,
    sandbox_allocation_id = CASE WHEN demand.provider_job_id = $1 THEN source.sandbox_allocation_id ELSE target.sandbox_allocation_id END,
    sandbox_execution_id = CASE WHEN demand.provider_job_id = $1 THEN source.sandbox_execution_id ELSE target.sandbox_execution_id END,
    sandbox_attempt_id = CASE WHEN demand.provider_job_id = $1 THEN source.sandbox_attempt_id ELSE target.sandbox_attempt_id END,
    state = CASE WHEN demand.provider_job_id = $1 THEN 'sandbox_submitted' ELSE target.state END,
    failure_reason = CASE WHEN demand.provider_job_id = $2 THEN $3 ELSE '' END,
    updated_at = $4
FROM source, target
WHERE demand.provider_job_id IN ($2, $1)
`

type SwapProviderDemandRunnerAssignmentsParams struct {
	ToProviderJobID   int64
	FromProviderJobID int64
	FailureReason     string
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) SwapProviderDemandRunnerAssignments(ctx context.Context, arg SwapProviderDemandRunnerAssignmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, swapProviderDemandRunnerAssignments,
		arg.ToProviderJobID,
		arg.FromProviderJobID,
		arg.FailureReason,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const swapRunnerRegistrationJobs = `-- name: SwapRunnerRegistrationJobs :execrows
WITH target AS (
    DELETE FROM github_runner_registrations
    WHERE github_runner_registrations.provider_job_id = $3
      AND github_runner_registrations.runner_name <> $4
      AND github_runner_registrations.state IN ('jit_created', 'sandbox_submitted')
    RETURNING provider_job_id, demand_id, provider_installation_id, provider_repository_id, runner_id, runner_name, runner_class, jit_config_sha256, sandbox_allocation_id, sandbox_execution_id, sandbox_attempt_id, state, failure_reason, created_at, updated_at
), moved_source AS (
    UPDATE github_runner_registrations
    SET provider_job_id = $3,
        demand_id = (
            SELECT demand_id
            FROM github_provider_demands
            WHERE github_provider_demands.provider_job_id = $3
        ),
        state = 'sandbox_submitted',
        failure_reason = '',
        updated_at = $2
    WHERE github_runner_registrations.provider_job_id = $1
      AND github_runner_registrations.runner_name = $4
    RETURNING provider_job_id, demand_id, provider_installation_id, provider_repository_id, runner_id, runner_name, runner_class, jit_config_sha256, sandbox_allocation_id, sandbox_execution_id, sandbox_attempt_id, state, failure_reason, created_at, updated_at
)
INSERT INTO github_runner_registrations (
    provider_job_id,
    demand_id,
    provider_installation_id,
    provider_repository_id,
    runner_id,
    runner_name,
    runner_class,
    jit_config_sha256,
    sandbox_allocation_id,
    sandbox_execution_id,
    sandbox_attempt_id,
    state,
    failure_reason,
    created_at,
    updated_at
)
SELECT
    $1,
    (
        SELECT demand_id
        FROM github_provider_demands
        WHERE github_provider_demands.provider_job_id = $1
    ),
    target.provider_installation_id,
    target.provider_repository_id,
    target.runner_id,
    target.runner_name,
    target.runner_class,
    target.jit_config_sha256,
    target.sandbox_allocation_id,
    target.sandbox_execution_id,
    target.sandbox_attempt_id,
    target.state,
    '',
    target.created_at,
    $2
FROM target
WHERE EXISTS (SELECT 1 FROM moved_source)
`

type SwapRunnerRegistrationJobsParams struct {
	FromProviderJobID int64
	UpdatedAt         pgtype.Timestamptz
	ToProviderJobID   int64
	RunnerName        string
}

func (q *Queries) SwapRunnerRegistrationJobs(ctx context.Context, arg SwapRunnerRegistrationJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, swapRunnerRegistrationJobs,
		arg.FromProviderJobID,
		arg.UpdatedAt,
		arg.ToProviderJobID,
		arg.RunnerName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transferRunnerRegistrationToJob = `-- name: TransferRunnerRegistrationToJob :execrows
WITH stale_target AS (
    DELETE FROM github_runner_registrations
    WHERE github_runner_registrations.provider_job_id = $1
      AND github_runner_registrations.runner_name <> $4
      AND github_runner_registrations.state IN ('cleaned', 'failed')
)
UPDATE github_runner_registrations
SET provider_job_id = $1,
    demand_id = (
        SELECT demand_id
        FROM github_provider_demands
        WHERE github_provider_demands.provider_job_id = $1
    ),
    state = 'sandbox_submitted',
    failure_reason = '',
    updated_at = $2
WHERE github_runner_registrations.provider_job_id = $3
  AND github_runner_registrations.runner_name = $4
`

type TransferRunnerRegistrationToJobParams struct {
	ToProviderJobID   int64
	UpdatedAt         pgtype.Timestamptz
	FromProviderJobID int64
	RunnerName        string
}

func (q *Queries) TransferRunnerRegistrationToJob(ctx context.Context, arg TransferRunnerRegistrationToJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, transferRunnerRegistrationToJob,
		arg.ToProviderJobID,
		arg.UpdatedAt,
		arg.FromProviderJobID,
		arg.RunnerName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertGoldenSnapshotBarrier = `-- name: UpsertGoldenSnapshotBarrier :exec
INSERT INTO github_golden_snapshot_barriers (
    barrier_id,
    terminal_evidence_id,
    provider_job_id,
    provider_run_id,
    provider_run_attempt,
    sandbox_execution_id,
    sandbox_attempt_id,
    job_shape_id,
    trust_class,
    state,
    failure_reason,
    requested_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $12
)
ON CONFLICT (provider_job_id) DO UPDATE SET
    terminal_evidence_id = EXCLUDED.terminal_evidence_id,
    provider_run_id = EXCLUDED.provider_run_id,
    provider_run_attempt = EXCLUDED.provider_run_attempt,
    sandbox_execution_id = EXCLUDED.sandbox_execution_id,
    sandbox_attempt_id = EXCLUDED.sandbox_attempt_id,
    job_shape_id = EXCLUDED.job_shape_id,
    trust_class = EXCLUDED.trust_class,
    state = EXCLUDED.state,
    failure_reason = EXCLUDED.failure_reason,
    requested_at = EXCLUDED.requested_at,
    updated_at = EXCLUDED.requested_at
`

type UpsertGoldenSnapshotBarrierParams struct {
	BarrierID          pgtype.UUID
	TerminalEvidenceID pgtype.UUID
	ProviderJobID      int64
	ProviderRunID      int64
	ProviderRunAttempt int64
	SandboxExecutionID pgtype.UUID
	SandboxAttemptID   pgtype.UUID
	JobShapeID         string
	TrustClass         string
	State              string
	FailureReason      string
	RequestedAt        pgtype.Timestamptz
}

func (q *Queries) UpsertGoldenSnapshotBarrier(ctx context.Context, arg UpsertGoldenSnapshotBarrierParams) error {
	_, err := q.db.Exec(ctx, upsertGoldenSnapshotBarrier,
		arg.BarrierID,
		arg.TerminalEvidenceID,
		arg.ProviderJobID,
		arg.ProviderRunID,
		arg.ProviderRunAttempt,
		arg.SandboxExecutionID,
		arg.SandboxAttemptID,
		arg.JobShapeID,
		arg.TrustClass,
		arg.State,
		arg.FailureReason,
		arg.RequestedAt,
	)
	return err
}

const upsertInstallation = `-- name: UpsertInstallation :exec
INSERT INTO github_installations (
    provider_installation_id,
    state,
    last_event_delivery_id,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (provider_installation_id) DO UPDATE SET
    state = EXCLUDED.state,
    last_event_delivery_id = COALESCE(NULLIF(EXCLUDED.last_event_delivery_id, ''), github_installations.last_event_delivery_id),
    updated_at = EXCLUDED.updated_at
`

type UpsertInstallationParams struct {
	ProviderInstallationID int64
	State                  string
	LastEventDeliveryID    string
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpsertInstallation(ctx context.Context, arg UpsertInstallationParams) error {
	_, err := q.db.Exec(ctx, upsertInstallation,
		arg.ProviderInstallationID,
		arg.State,
		arg.LastEventDeliveryID,
		arg.UpdatedAt,
	)
	return err
}

const upsertJobShape = `-- name: UpsertJobShape :exec
INSERT INTO github_job_shapes (
    job_shape_id,
    provider_installation_id,
    provider_repository_id,
    repository_full_name,
    workflow_path,
    workflow_name,
    job_name,
    matrix_key,
    runner_class,
    runner_labels_json,
    cache_manifest_sha256,
    trust_class,
    canonical_json,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14
)
ON CONFLICT (job_shape_id) DO UPDATE SET
    provider_installation_id = EXCLUDED.provider_installation_id,
    provider_repository_id = EXCLUDED.provider_repository_id,
    repository_full_name = EXCLUDED.repository_full_name,
    workflow_path = EXCLUDED.workflow_path,
    workflow_name = EXCLUDED.workflow_name,
    job_name = EXCLUDED.job_name,
    matrix_key = EXCLUDED.matrix_key,
    runner_class = EXCLUDED.runner_class,
    runner_labels_json = EXCLUDED.runner_labels_json,
    cache_manifest_sha256 = EXCLUDED.cache_manifest_sha256,
    trust_class = EXCLUDED.trust_class,
    canonical_json = EXCLUDED.canonical_json,
    updated_at = EXCLUDED.updated_at
`

type UpsertJobShapeParams struct {
	JobShapeID             string
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	RepositoryFullName     string
	WorkflowPath           string
	WorkflowName           string
	JobName                string
	MatrixKey              string
	RunnerClass            string
	RunnerLabelsJson       []byte
	CacheManifestSha256    string
	TrustClass             string
	CanonicalJson          []byte
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpsertJobShape(ctx context.Context, arg UpsertJobShapeParams) error {
	_, err := q.db.Exec(ctx, upsertJobShape,
		arg.JobShapeID,
		arg.ProviderInstallationID,
		arg.ProviderRepositoryID,
		arg.RepositoryFullName,
		arg.WorkflowPath,
		arg.WorkflowName,
		arg.JobName,
		arg.MatrixKey,
		arg.RunnerClass,
		arg.RunnerLabelsJson,
		arg.CacheManifestSha256,
		arg.TrustClass,
		arg.CanonicalJson,
		arg.UpdatedAt,
	)
	return err
}

const upsertProviderOutboxCommand = `-- name: UpsertProviderOutboxCommand :exec
INSERT INTO github_provider_outbox (
    outbox_id,
    command_kind,
    provider_job_id,
    provider_run_id,
    provider_run_attempt,
    provider_installation_id,
    provider_repository_id,
    state,
    command_sha256,
    payload_json,
    next_attempt_at,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    'pending',
    $8,
    $9,
    $10,
    $11,
    $11
)
ON CONFLICT (command_kind, command_sha256) DO UPDATE SET
    state = CASE
        WHEN github_provider_outbox.state = 'processed' THEN github_provider_outbox.state
        ELSE 'pending'
    END,
    payload_json = EXCLUDED.payload_json,
    next_attempt_at = EXCLUDED.next_attempt_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertProviderOutboxCommandParams struct {
	OutboxID               pgtype.UUID
	CommandKind            string
	ProviderJobID          int64
	ProviderRunID          int64
	ProviderRunAttempt     int64
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	CommandSha256          string
	PayloadJson            []byte
	NextAttemptAt          pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpsertProviderOutboxCommand(ctx context.Context, arg UpsertProviderOutboxCommandParams) error {
	_, err := q.db.Exec(ctx, upsertProviderOutboxCommand,
		arg.OutboxID,
		arg.CommandKind,
		arg.ProviderJobID,
		arg.ProviderRunID,
		arg.ProviderRunAttempt,
		arg.ProviderInstallationID,
		arg.ProviderRepositoryID,
		arg.CommandSha256,
		arg.PayloadJson,
		arg.NextAttemptAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertRepository = `-- name: UpsertRepository :exec
INSERT INTO github_repositories (
    provider_repository_id,
    provider_installation_id,
    owner_login,
    repository_name,
    repository_full_name,
    state,
    last_event_delivery_id,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (provider_repository_id) DO UPDATE SET
    provider_installation_id = CASE WHEN EXCLUDED.provider_installation_id <> 0 THEN EXCLUDED.provider_installation_id ELSE github_repositories.provider_installation_id END,
    owner_login = COALESCE(NULLIF(EXCLUDED.owner_login, ''), github_repositories.owner_login),
    repository_name = COALESCE(NULLIF(EXCLUDED.repository_name, ''), github_repositories.repository_name),
    repository_full_name = COALESCE(NULLIF(EXCLUDED.repository_full_name, ''), github_repositories.repository_full_name),
    state = EXCLUDED.state,
    last_event_delivery_id = COALESCE(NULLIF(EXCLUDED.last_event_delivery_id, ''), github_repositories.last_event_delivery_id),
    updated_at = EXCLUDED.updated_at
`

type UpsertRepositoryParams struct {
	ProviderRepositoryID   int64
	ProviderInstallationID int64
	OwnerLogin             string
	RepositoryName         string
	RepositoryFullName     string
	State                  string
	LastEventDeliveryID    string
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) error {
	_, err := q.db.Exec(ctx, upsertRepository,
		arg.ProviderRepositoryID,
		arg.ProviderInstallationID,
		arg.OwnerLogin,
		arg.RepositoryName,
		arg.RepositoryFullName,
		arg.State,
		arg.LastEventDeliveryID,
		arg.UpdatedAt,
	)
	return err
}

const upsertRunnerRegistration = `-- name: UpsertRunnerRegistration :exec
INSERT INTO github_runner_registrations (
    provider_job_id,
    demand_id,
    provider_installation_id,
    provider_repository_id,
    runner_id,
    runner_name,
    runner_class,
    jit_config_sha256,
    state,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (provider_job_id) DO UPDATE SET
    demand_id = COALESCE(EXCLUDED.demand_id, github_runner_registrations.demand_id),
    runner_id = EXCLUDED.runner_id,
    runner_name = EXCLUDED.runner_name,
    runner_class = EXCLUDED.runner_class,
    jit_config_sha256 = EXCLUDED.jit_config_sha256,
    state = EXCLUDED.state,
    failure_reason = '',
    updated_at = EXCLUDED.updated_at
`

type UpsertRunnerRegistrationParams struct {
	ProviderJobID          int64
	DemandID               pgtype.UUID
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	RunnerID               int64
	RunnerName             string
	RunnerClass            string
	JitConfigSha256        string
	State                  string
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpsertRunnerRegistration(ctx context.Context, arg UpsertRunnerRegistrationParams) error {
	_, err := q.db.Exec(ctx, upsertRunnerRegistration,
		arg.ProviderJobID,
		arg.DemandID,
		arg.ProviderInstallationID,
		arg.ProviderRepositoryID,
		arg.RunnerID,
		arg.RunnerName,
		arg.RunnerClass,
		arg.JitConfigSha256,
		arg.State,
		arg.UpdatedAt,
	)
	return err
}

const upsertWorkflowJob = `-- name: UpsertWorkflowJob :exec
INSERT INTO github_workflow_jobs (
    provider_job_id,
    provider_installation_id,
    provider_repository_id,
    repository_full_name,
    provider_run_id,
    provider_run_attempt,
    job_name,
    head_sha,
    head_branch,
    workflow_name,
    status,
    conclusion,
    labels_json,
    runner_id,
    runner_name,
    started_at,
    completed_at,
    last_delivery_id,
    observed_from_api_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20
)
ON CONFLICT (provider_job_id) DO UPDATE SET
    provider_installation_id = EXCLUDED.provider_installation_id,
    provider_repository_id = EXCLUDED.provider_repository_id,
    repository_full_name = EXCLUDED.repository_full_name,
    provider_run_id = EXCLUDED.provider_run_id,
    provider_run_attempt = EXCLUDED.provider_run_attempt,
    job_name = EXCLUDED.job_name,
    head_sha = EXCLUDED.head_sha,
    head_branch = EXCLUDED.head_branch,
    workflow_name = EXCLUDED.workflow_name,
    status = EXCLUDED.status,
    conclusion = EXCLUDED.conclusion,
    labels_json = EXCLUDED.labels_json,
    runner_id = EXCLUDED.runner_id,
    runner_name = EXCLUDED.runner_name,
    started_at = EXCLUDED.started_at,
    completed_at = EXCLUDED.completed_at,
    last_delivery_id = EXCLUDED.last_delivery_id,
    observed_from_api_at = EXCLUDED.observed_from_api_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertWorkflowJobParams struct {
	ProviderJobID          int64
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	RepositoryFullName     string
	ProviderRunID          int64
	ProviderRunAttempt     int64
	JobName                string
	HeadSha                string
	HeadBranch             string
	WorkflowName           string
	Status                 string
	Conclusion             string
	LabelsJson             []byte
	RunnerID               int64
	RunnerName             string
	StartedAt              pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	LastDeliveryID         string
	ObservedFromApiAt      pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpsertWorkflowJob(ctx context.Context, arg UpsertWorkflowJobParams) error {
	_, err := q.db.Exec(ctx, upsertWorkflowJob,
		arg.ProviderJobID,
		arg.ProviderInstallationID,
		arg.ProviderRepositoryID,
		arg.RepositoryFullName,
		arg.ProviderRunID,
		arg.ProviderRunAttempt,
		arg.JobName,
		arg.HeadSha,
		arg.HeadBranch,
		arg.WorkflowName,
		arg.Status,
		arg.Conclusion,
		arg.LabelsJson,
		arg.RunnerID,
		arg.RunnerName,
		arg.StartedAt,
		arg.CompletedAt,
		arg.LastDeliveryID,
		arg.ObservedFromApiAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertWorkflowRun = `-- name: UpsertWorkflowRun :exec
INSERT INTO github_workflow_runs (
    provider_installation_id,
    provider_repository_id,
    provider_run_id,
    provider_run_attempt,
    repository_full_name,
    event_name,
    head_sha,
    head_branch,
    head_repository_full_name,
    base_sha,
    base_branch,
    workflow_path,
    pull_request_number,
    commit_count,
    last_delivery_id,
    observed_from_api_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
ON CONFLICT (provider_installation_id, provider_repository_id, provider_run_id, provider_run_attempt) DO UPDATE SET
    repository_full_name = EXCLUDED.repository_full_name,
    event_name = EXCLUDED.event_name,
    head_sha = EXCLUDED.head_sha,
    head_branch = EXCLUDED.head_branch,
    head_repository_full_name = EXCLUDED.head_repository_full_name,
    base_sha = EXCLUDED.base_sha,
    base_branch = EXCLUDED.base_branch,
    workflow_path = EXCLUDED.workflow_path,
    pull_request_number = EXCLUDED.pull_request_number,
    commit_count = EXCLUDED.commit_count,
    last_delivery_id = EXCLUDED.last_delivery_id,
    observed_from_api_at = EXCLUDED.observed_from_api_at,
    updated_at = EXCLUDED.updated_at
`

type UpsertWorkflowRunParams struct {
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	ProviderRunID          int64
	ProviderRunAttempt     int64
	RepositoryFullName     string
	EventName              string
	HeadSha                string
	HeadBranch             string
	HeadRepositoryFullName string
	BaseSha                string
	BaseBranch             string
	WorkflowPath           string
	PullRequestNumber      int64
	CommitCount            int64
	LastDeliveryID         string
	ObservedFromApiAt      pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpsertWorkflowRun(ctx context.Context, arg UpsertWorkflowRunParams) error {
	_, err := q.db.Exec(ctx, upsertWorkflowRun,
		arg.ProviderInstallationID,
		arg.ProviderRepositoryID,
		arg.ProviderRunID,
		arg.ProviderRunAttempt,
		arg.RepositoryFullName,
		arg.EventName,
		arg.HeadSha,
		arg.HeadBranch,
		arg.HeadRepositoryFullName,
		arg.BaseSha,
		arg.BaseBranch,
		arg.WorkflowPath,
		arg.PullRequestNumber,
		arg.CommitCount,
		arg.LastDeliveryID,
		arg.ObservedFromApiAt,
		arg.UpdatedAt,
	)
	return err
}
