load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "vm-lease-probe_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/vm-orchestrator/cmd/vm-lease-probe",
    visibility = ["//visibility:private"],
    deps = [
        "//src/substrate/vm-orchestrator",
    ],
)

go_binary(
    name = "vm-lease-probe",
    embed = [":vm-lease-probe_lib"],
    visibility = ["//visibility:public"],
)
