haproxy_public_routes:
  - host: '{{ email_service_domain }}'
    backend: be_route_product_email_api_email_service_public_api
haproxy_public_apis:
  - key: email
    host: '{{ email_service_domain }}'
    path_prefix: /api/v1
