// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package spire

import (
	s "github.com/verself/cue-renderer/schema"
)

// #Config is the per-deployment SPIRE configuration. Computed fields
// (agent_id, bundle_endpoint_url) live alongside the inputs so the
// renderer reads them directly instead of re-deriving in Go.
type Config struct {
	Trust_domain string `json:"trust_domain"`

	Server_bind_address s.Host `json:"server_bind_address"`

	Server_socket_path string `json:"server_socket_path"`

	Agent_socket_path string `json:"agent_socket_path"`

	Workload_group string `json:"workload_group"`

	Agent_id_path string `json:"agent_id_path"`

	// Computed: the agent's SPIFFE ID. The renderer reads this verbatim
	// instead of re-doing the concatenation. Declared as a defaulted
	// string so gengotypes types it cleanly; the default is the only
	// admissible value because the right-hand side is concrete.
	Agent_id string `json:"agent_id"`

	// Bundle endpoint coordinates. The component + endpoint names point
	// at where SPIRE actually listens in topology.cue; the renderer uses
	// them to look up the bound port. Scheme defaults to https; emitted
	// as a field so the renderer doesn't sprintf a literal "https://".
	Bundle_endpoint_bind_address s.Host `json:"bundle_endpoint_bind_address"`

	Bundle_endpoint_scheme string `json:"bundle_endpoint_scheme"`

	Bundle_endpoint_component string `json:"bundle_endpoint_component"`

	Bundle_endpoint_endpoint string `json:"bundle_endpoint_endpoint"`

	// Server endpoint coordinates, same shape as the bundle endpoint.
	Server_component string `json:"server_component"`

	Server_endpoint string `json:"server_endpoint"`
}

// #AuthKind is the per-kind metadata each entry in the spiffe_auth_kinds
// catalog carries. spiffe_bearing flags edges that need a SPIRE
// registration (mTLS using x509-SVIDs); other auth modes (Zitadel JWT,
// shared secrets, operator credentials) do not.
type AuthKind struct {
	Name string `json:"name"`

	Spiffe_bearing bool `json:"spiffe_bearing"`
}
