---
- name: Check if profile-service unit exists
  listen: restart profile-service
  ansible.builtin.stat:
    path: /etc/systemd/system/profile-service.service
  register: profile_service_unit_file

- name: Restart profile-service
  listen: restart profile-service
  ansible.builtin.systemd:
    daemon_reload: true
    name: profile-service
    state: restarted
  when: profile_service_unit_file.stat.exists
