load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "siteinject",
    srcs = ["siteinject.go"],
    importpath = "github.com/verself/deployment-tools/internal/siteinject",
    visibility = ["//src/tools/deployment:__subpackages__"],
    deps = [
        "//src/tools/deployment/internal/siteconfig",
        "@com_github_hashicorp_nomad_api//:api",
    ],
)

go_test(
    name = "siteinject_test",
    srcs = ["siteinject_test.go"],
    embed = [":siteinject"],
    deps = [
        "//src/tools/deployment/internal/siteconfig",
        "@com_github_hashicorp_nomad_api//:api",
    ],
)
