load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "gen-tools-catalog_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/guardian-specification/cmd/gen-tools-catalog",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "gen-tools-catalog",
    embed = [":gen-tools-catalog_lib"],
    visibility = ["//visibility:public"],
)
