http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "postgresql_tool_postgresql_16",
    downloaded_file_path = "postgresql-16_16.14-0ubuntu0.24.04.1_amd64.deb",
    sha256 = "13e35dd2bf70ecbc0bdb699313aaa5fa518b45dd5695111a753a1e6e0274e8fa",
    url = "https://archive.ubuntu.com/ubuntu/pool/main/p/postgresql-16/postgresql-16_16.14-0ubuntu0.24.04.1_amd64.deb",
)

http_file(
    name = "postgresql_tool_postgresql_client_16",
    downloaded_file_path = "postgresql-client-16_16.14-0ubuntu0.24.04.1_amd64.deb",
    sha256 = "8d25751b2b7ff568da1aee1c77880e56559e1f3710dea9f87ae00ec5afea9f39",
    url = "https://archive.ubuntu.com/ubuntu/pool/main/p/postgresql-16/postgresql-client-16_16.14-0ubuntu0.24.04.1_amd64.deb",
)

http_file(
    name = "postgresql_tool_libpq5",
    downloaded_file_path = "libpq5_16.14-0ubuntu0.24.04.1_amd64.deb",
    sha256 = "a7000b8261d2139cb4a34dcb1e5a04e53ccea175e68499088401e40d5ae3c609",
    url = "https://archive.ubuntu.com/ubuntu/pool/main/p/postgresql-16/libpq5_16.14-0ubuntu0.24.04.1_amd64.deb",
)

http_file(
    name = "postgresql_tool_libxml2",
    downloaded_file_path = "libxml2_2.9.14+dfsg-1.3ubuntu3.7_amd64.deb",
    sha256 = "74ab8be7aa487e5cc7d9d228212f538ff96658afcb080335c02fe0f3e384ff7c",
    url = "https://archive.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2_2.9.14+dfsg-1.3ubuntu3.7_amd64.deb",
)

http_file(
    name = "postgresql_tool_libicu74",
    downloaded_file_path = "libicu74_74.2-1ubuntu3.1_amd64.deb",
    sha256 = "c9a70989678660eed9a1e904c74fa043da8bec8e2036856fc16e31ced79b04f8",
    url = "https://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu74_74.2-1ubuntu3.1_amd64.deb",
)

http_file(
    name = "postgresql_tool_pgbackrest",
    downloaded_file_path = "pgbackrest_2.58.0-1.pgdg24.04+1_amd64.deb",
    sha256 = "f2eddd27246e85fb4842a030fee21ebc036ba22a81627e932d2c01796f616546",
    url = "https://apt.postgresql.org/pub/repos/apt/pool/main/p/pgbackrest/pgbackrest_2.58.0-1.pgdg24.04+1_amd64.deb",
)

http_file(
    name = "postgresql_tool_libssh2_1t64",
    downloaded_file_path = "libssh2-1t64_1.11.0-4.1ubuntu0.24.04.1_amd64.deb",
    sha256 = "44754349d71a772416fb134c12dd8c08a2c1785f0344676eb936c89305ca5f26",
    url = "https://archive.ubuntu.com/ubuntu/pool/main/libs/libssh2/libssh2-1t64_1.11.0-4.1ubuntu0.24.04.1_amd64.deb",
)
