load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "contractapi",
    srcs = [
        "auth_contract.go",
        "contract.go",
    ],
    importpath = "github.com/verself/iam-service/internal/contractapi",
    visibility = ["//src/services/iam-service:__subpackages__"],
)
