haproxy_public_routes:
  - host: '{{ iam_service_domain }}'
    backend: be_route_product_iam_api_iam_service_public_api
haproxy_public_apis:
  - key: iam
    host: '{{ iam_service_domain }}'
    path_prefix: /api/v1
