---
- name: Restart OTel Collector
  listen: restart otelcol
  ansible.builtin.systemd:
    daemon_reload: true
    name: otelcol
    state: restarted

- name: Restart OTel Collector ClickHouse SPIFFE helper
  listen: restart otelcol-clickhouse-spiffe-helper
  ansible.builtin.systemd:
    daemon_reload: true
    name: otelcol-clickhouse-spiffe-helper
    state: restarted
