load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "contract",
    srcs = ["contract.go"],
    importpath = "github.com/verself/verself/src/smithy/internal/contract",
    visibility = ["//src/smithy:__subpackages__"],
)

alias(
    name = "go_default_library",
    actual = ":contract",
    visibility = ["//src/smithy:__subpackages__"],
)
