DROP TABLE IF EXISTS forge_metal.metering;

CREATE TABLE forge_metal.metering (
    window_id                 String                               CODEC(ZSTD(3)),
    org_id                    LowCardinality(String)               CODEC(ZSTD(3)),
    actor_id                  String DEFAULT ''                    CODEC(ZSTD(3)),
    product_id                LowCardinality(String)               CODEC(ZSTD(3)),
    source_type               LowCardinality(String)               CODEC(ZSTD(3)),
    source_ref                String                               CODEC(ZSTD(3)),
    window_seq                UInt32                               CODEC(Delta(4), ZSTD(3)),
    reservation_shape         LowCardinality(String)               CODEC(ZSTD(3)),
    started_at                DateTime64(6)                        CODEC(DoubleDelta, ZSTD(3)),
    ended_at                  DateTime64(6)                        CODEC(DoubleDelta, ZSTD(3)),
    reserved_quantity         UInt64                               CODEC(T64, ZSTD(3)),
    actual_quantity           UInt64                               CODEC(T64, ZSTD(3)),
    billable_quantity         UInt64                               CODEC(T64, ZSTD(3)),
    writeoff_quantity         UInt64                               CODEC(T64, ZSTD(3)),
    pricing_phase             LowCardinality(String)               CODEC(ZSTD(3)),
    dimensions                Map(LowCardinality(String), Float64) CODEC(ZSTD(3)),
    component_quantities      Map(LowCardinality(String), Float64) CODEC(ZSTD(3)),
    component_charge_units    Map(LowCardinality(String), UInt64)  CODEC(ZSTD(3)),
    bucket_charge_units       Map(LowCardinality(String), UInt64)  CODEC(ZSTD(3)),
    charge_units              UInt64                               CODEC(T64, ZSTD(3)),
    writeoff_charge_units     UInt64                               CODEC(T64, ZSTD(3)),
    free_tier_units           UInt64                               CODEC(T64, ZSTD(3)),
    subscription_units        UInt64                               CODEC(T64, ZSTD(3)),
    purchase_units            UInt64                               CODEC(T64, ZSTD(3)),
    promo_units               UInt64                               CODEC(T64, ZSTD(3)),
    refund_units              UInt64                               CODEC(T64, ZSTD(3)),
    receivable_units          UInt64                               CODEC(T64, ZSTD(3)),
    component_free_tier_units    Map(LowCardinality(String), UInt64)  CODEC(ZSTD(3)),
    component_subscription_units Map(LowCardinality(String), UInt64)  CODEC(ZSTD(3)),
    component_purchase_units     Map(LowCardinality(String), UInt64)  CODEC(ZSTD(3)),
    component_promo_units        Map(LowCardinality(String), UInt64)  CODEC(ZSTD(3)),
    component_refund_units       Map(LowCardinality(String), UInt64)  CODEC(ZSTD(3)),
    component_receivable_units   Map(LowCardinality(String), UInt64)  CODEC(ZSTD(3)),
    usage_evidence            Map(LowCardinality(String), UInt64)  CODEC(ZSTD(3)),
    plan_id                   LowCardinality(String) DEFAULT ''    CODEC(ZSTD(3)),
    cost_per_unit             UInt64 DEFAULT 0                     CODEC(T64, ZSTD(3)),
    recorded_at               DateTime64(6) DEFAULT now64(6)       CODEC(DoubleDelta, ZSTD(3)),
    trace_id                  String DEFAULT ''                    CODEC(ZSTD(3))
)
ENGINE = MergeTree()
ORDER BY (org_id, product_id, started_at, source_ref, window_seq, window_id);
