CREATE DATABASE IF NOT EXISTS forge_metal;

DROP TABLE IF EXISTS forge_metal.audit_events;

CREATE TABLE forge_metal.audit_events
(
    recorded_at DateTime64(6, 'UTC'),
    event_date Date DEFAULT toDate(recorded_at),
    ingested_at DateTime64(6, 'UTC') DEFAULT now64(6, 'UTC'),

    schema_version LowCardinality(String),
    event_id UUID,
    org_id LowCardinality(String),
    environment LowCardinality(String),
    source_product_area LowCardinality(String),
    service_name LowCardinality(String),
    service_version LowCardinality(String),
    writer_instance_id String,

    request_id String,
    trace_id String,
    span_id String,
    parent_span_id String,
    route_template String,
    http_method LowCardinality(String),
    http_status UInt16,
    duration_ms Float64,
    idempotency_key_hash String,

    actor_type LowCardinality(String),
    actor_id String,
    actor_display String,
    actor_org_id String,
    actor_owner_id String,
    actor_owner_display String,
    credential_id String,
    credential_name String,
    credential_fingerprint String,
    auth_method LowCardinality(String),
    auth_assurance_level LowCardinality(String),
    mfa_present UInt8,
    session_id_hash String,
    delegation_chain String,
    actor_spiffe_id String,

    operation_id LowCardinality(String),
    audit_event LowCardinality(String),
    operation_display String,
    operation_type LowCardinality(String),
    event_category LowCardinality(String),
    risk_level LowCardinality(String),
    data_classification LowCardinality(String),
    rate_limit_class LowCardinality(String),

    target_kind LowCardinality(String),
    target_id String,
    target_display String,
    target_scope LowCardinality(String),
    target_path_hash String,
    resource_owner_org_id String,
    resource_region LowCardinality(String),

    permission LowCardinality(String),
    action LowCardinality(String),
    org_scope LowCardinality(String),
    policy_id String,
    policy_version String,
    policy_hash String,
    matched_rule String,
    decision LowCardinality(String),
    result LowCardinality(String),
    denial_reason LowCardinality(String),
    trust_class LowCardinality(String),

    client_ip String,
    client_ip_version LowCardinality(String),
    client_ip_hash String,
    ip_chain String,
    ip_chain_trusted_hops UInt8,
    user_agent_raw String,
    user_agent_hash String,
    referer_origin String,
    origin String,
    host String,
    tls_subject_hash String,
    mtls_subject_hash String,

    geo_country LowCardinality(String),
    geo_region String,
    geo_city String,
    asn UInt32,
    asn_org String,
    network_type LowCardinality(String),
    geo_source String,
    geo_source_version String,

    changed_fields String,
    before_hash String,
    after_hash String,
    content_sha256 String,
    artifact_sha256 String,
    artifact_bytes UInt64,
    error_code LowCardinality(String),
    error_class LowCardinality(String),
    error_message String,

    secret_mount String,
    secret_path_hash String,
    secret_version UInt64,
    secret_operation LowCardinality(String),
    lease_id_hash String,
    lease_ttl_seconds UInt64,
    key_id String,
    openbao_request_id String,
    openbao_accessor_hash String,

    payload_json String,
    sequence UInt64,
    prev_hmac String,
    row_hmac String,
    hmac_key_id String,
    retention_class LowCardinality(String),
    legal_hold UInt8
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(event_date)
ORDER BY (org_id, event_date, risk_level, operation_type, source_product_area, result, recorded_at, sequence, event_id)
SETTINGS index_granularity = 8192;
