// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sticky_inventory.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStickyDiskGenerationForOrg = `-- name: DeleteStickyDiskGenerationForOrg :one
DELETE FROM runner_sticky_disk_generations g
USING github_installations i,
      runner_provider_repositories p,
      github_installation_connections c
WHERE g.provider = 'github'
  AND g.provider_installation_id = $1
  AND g.provider_repository_id = $2
  AND g.key_hash = $3
  AND i.installation_id = g.provider_installation_id
  AND p.provider = 'github'
  AND p.provider_repository_id = g.provider_repository_id
  AND p.org_id = $4
  AND p.active
  AND c.installation_id = i.installation_id
  AND c.org_id = p.org_id
  AND c.state = 'active'
  AND i.active
RETURNING g.current_source_ref
`

type DeleteStickyDiskGenerationForOrgParams struct {
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	KeyHash                string
	OrgID                  int64
}

func (q *Queries) DeleteStickyDiskGenerationForOrg(ctx context.Context, arg DeleteStickyDiskGenerationForOrgParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteStickyDiskGenerationForOrg,
		arg.ProviderInstallationID,
		arg.ProviderRepositoryID,
		arg.KeyHash,
		arg.OrgID,
	)
	var current_source_ref string
	err := row.Scan(&current_source_ref)
	return current_source_ref, err
}

const listStickyDisks = `-- name: ListStickyDisks :many
SELECT
    g.provider_installation_id,
    g.provider_repository_id,
    p.repository_full_name,
    g.key_hash,
    g.key,
    g.current_generation,
    g.current_source_ref,
    last_mount.last_used_at,
    last_mount.completed_at,
    COALESCE(last_mount.save_state, '')::text AS save_state,
    COALESCE(last_mount.execution_id, '00000000-0000-0000-0000-000000000000'::uuid) AS execution_id,
    COALESCE(last_mount.attempt_id, '00000000-0000-0000-0000-000000000000'::uuid) AS attempt_id,
    COALESCE(last_mount.runner_class, '')::text AS runner_class,
    COALESCE(last_mount.workflow_name, '')::text AS workflow_name,
    COALESCE(last_mount.job_name, '')::text AS job_name,
    COALESCE(last_mount.mount_path, '')::text AS mount_path,
    g.updated_at
FROM runner_sticky_disk_generations g
JOIN github_installations i ON i.installation_id = g.provider_installation_id
JOIN runner_provider_repositories p ON p.provider = 'github' AND p.provider_repository_id = g.provider_repository_id AND p.active
JOIN github_installation_connections c ON c.installation_id = i.installation_id AND c.org_id = p.org_id AND c.state = 'active'
LEFT JOIN LATERAL (
    SELECT
        COALESCE(m.completed_at, m.requested_at, m.updated_at, m.created_at) AS last_used_at,
        m.completed_at,
        m.save_state,
        m.execution_id,
        m.attempt_id,
        a.runner_class,
        COALESCE(j.workflow_name, '') AS workflow_name,
        COALESCE(j.job_name, '') AS job_name,
        m.mount_path
    FROM execution_sticky_disk_mounts m
    JOIN runner_allocations a ON a.allocation_id = m.allocation_id
    LEFT JOIN runner_job_bindings b ON b.allocation_id = a.allocation_id
    LEFT JOIN runner_jobs j ON j.provider = a.provider AND j.provider_job_id = COALESCE(b.provider_job_id, a.requested_for_provider_job_id)
    WHERE a.provider = 'github'
      AND a.provider_installation_id = g.provider_installation_id
      AND a.provider_repository_id = g.provider_repository_id
      AND m.key_hash = g.key_hash
    ORDER BY COALESCE(m.completed_at, m.requested_at, m.updated_at, m.created_at) DESC, m.mount_id DESC
    LIMIT 1
) last_mount ON true
WHERE p.org_id = $1
  AND i.active
  AND ($2::text = '' OR p.repository_full_name = $2)
  AND g.provider = 'github'
  AND ($3::boolean = false OR (g.updated_at, g.provider_installation_id, g.provider_repository_id, g.key_hash) < ($4::timestamptz, $5::bigint, $6::bigint, $7::text))
ORDER BY g.updated_at DESC, g.provider_installation_id DESC, g.provider_repository_id DESC, g.key_hash DESC
LIMIT $8
`

type ListStickyDisksParams struct {
	OrgID                int64
	Repository           string
	CursorEnabled        bool
	CursorUpdatedAt      pgtype.Timestamptz
	CursorInstallationID int64
	CursorRepositoryID   int64
	CursorKeyHash        string
	LimitCount           int32
}

type ListStickyDisksRow struct {
	ProviderInstallationID int64
	ProviderRepositoryID   int64
	RepositoryFullName     string
	KeyHash                string
	Key                    string
	CurrentGeneration      int64
	CurrentSourceRef       string
	LastUsedAt             pgtype.Timestamptz
	CompletedAt            pgtype.Timestamptz
	SaveState              string
	ExecutionID            uuid.UUID
	AttemptID              uuid.UUID
	RunnerClass            string
	WorkflowName           string
	JobName                string
	MountPath              string
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) ListStickyDisks(ctx context.Context, arg ListStickyDisksParams) ([]ListStickyDisksRow, error) {
	rows, err := q.db.Query(ctx, listStickyDisks,
		arg.OrgID,
		arg.Repository,
		arg.CursorEnabled,
		arg.CursorUpdatedAt,
		arg.CursorInstallationID,
		arg.CursorRepositoryID,
		arg.CursorKeyHash,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStickyDisksRow{}
	for rows.Next() {
		var i ListStickyDisksRow
		if err := rows.Scan(
			&i.ProviderInstallationID,
			&i.ProviderRepositoryID,
			&i.RepositoryFullName,
			&i.KeyHash,
			&i.Key,
			&i.CurrentGeneration,
			&i.CurrentSourceRef,
			&i.LastUsedAt,
			&i.CompletedAt,
			&i.SaveState,
			&i.ExecutionID,
			&i.AttemptID,
			&i.RunnerClass,
			&i.WorkflowName,
			&i.JobName,
			&i.MountPath,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
