load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "spicedb-recover_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/infrastructure-components/spicedb/cmd/spicedb-recover",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "spicedb-recover",
    embed = [":spicedb-recover_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "spicedb-recover_test",
    srcs = ["main_test.go"],
    embed = [":spicedb-recover_lib"],
)
