// Package objectstorageclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by oapi-codegen via //bazel:openapi_codegen.bzl; DO NOT EDIT.
package objectstorageclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AliasView defines model for AliasView.
type AliasView struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string `json:"$schema,omitempty"`
	Alias      string  `json:"alias"`
	BucketId   string  `json:"bucket_id"`
	CreatedAt  string  `json:"created_at"`
	Prefix     string  `json:"prefix"`
	ServiceTag string  `json:"service_tag"`
}

// BucketView defines model for BucketView.
type BucketView struct {
	// Schema A URL to the JSON Schema for this object.
	Schema         *string     `json:"$schema,omitempty"`
	BucketId       string      `json:"bucket_id"`
	BucketName     string      `json:"bucket_name"`
	CreatedAt      string      `json:"created_at"`
	GarageBucketId string      `json:"garage_bucket_id"`
	LifecycleRules interface{} `json:"lifecycle_rules"`
	OrgId          string      `json:"org_id"`
	QuotaBytes     *string     `json:"quota_bytes,omitempty"`
	QuotaObjects   *string     `json:"quota_objects,omitempty"`
	UpdatedAt      string      `json:"updated_at"`
}

// CreateAliasInputBody defines model for CreateAliasInputBody.
type CreateAliasInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema     *string `json:"$schema,omitempty"`
	Alias      string  `json:"alias"`
	Prefix     *string `json:"prefix,omitempty"`
	ServiceTag *string `json:"service_tag,omitempty"`
}

// CreateBucketInputBody defines model for CreateBucketInputBody.
type CreateBucketInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema         *string     `json:"$schema,omitempty"`
	BucketName     string      `json:"bucket_name"`
	LifecycleRules interface{} `json:"lifecycle_rules,omitempty"`
	QuotaBytes     *string     `json:"quota_bytes,omitempty"`
	QuotaObjects   *string     `json:"quota_objects,omitempty"`
}

// CreateMTLSCredentialInputBody defines model for CreateMTLSCredentialInputBody.
type CreateMTLSCredentialInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema        *string `json:"$schema,omitempty"`
	DisplayName   string  `json:"display_name"`
	SpiffeSubject string  `json:"spiffe_subject"`
}

// CreateStaticCredentialInputBody defines model for CreateStaticCredentialInputBody.
type CreateStaticCredentialInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema      *string `json:"$schema,omitempty"`
	DisplayName string  `json:"display_name"`
	ExpiresAt   *string `json:"expires_at,omitempty"`
}

// CredentialSecretView defines model for CredentialSecretView.
type CredentialSecretView struct {
	// Schema A URL to the JSON Schema for this object.
	Schema                *string        `json:"$schema,omitempty"`
	AccessKeyId           string         `json:"access_key_id"`
	Credential            CredentialView `json:"credential"`
	CredentialFingerprint string         `json:"credential_fingerprint"`
	SecretAccessKey       string         `json:"secret_access_key"`
}

// CredentialView defines model for CredentialView.
type CredentialView struct {
	AccessKeyId           *string `json:"access_key_id,omitempty"`
	AuthMode              string  `json:"auth_mode"`
	BucketId              string  `json:"bucket_id"`
	CreatedAt             string  `json:"created_at"`
	CredentialFingerprint *string `json:"credential_fingerprint,omitempty"`
	CredentialId          string  `json:"credential_id"`
	DisplayName           string  `json:"display_name"`
	ExpiresAt             *string `json:"expires_at,omitempty"`
	RevokedAt             *string `json:"revoked_at,omitempty"`
	SpiffeSubject         *string `json:"spiffe_subject,omitempty"`
	Status                string  `json:"status"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// UpdateBucketInputBody defines model for UpdateBucketInputBody.
type UpdateBucketInputBody struct {
	// Schema A URL to the JSON Schema for this object.
	Schema         *string     `json:"$schema,omitempty"`
	LifecycleRules interface{} `json:"lifecycle_rules,omitempty"`
	QuotaBytes     *string     `json:"quota_bytes,omitempty"`
	QuotaObjects   *string     `json:"quota_objects,omitempty"`
}

// CreateObjectStorageBucketJSONRequestBody defines body for CreateObjectStorageBucket for application/json ContentType.
type CreateObjectStorageBucketJSONRequestBody = CreateBucketInputBody

// UpdateObjectStorageBucketJSONRequestBody defines body for UpdateObjectStorageBucket for application/json ContentType.
type UpdateObjectStorageBucketJSONRequestBody = UpdateBucketInputBody

// CreateObjectStorageAccessKeyJSONRequestBody defines body for CreateObjectStorageAccessKey for application/json ContentType.
type CreateObjectStorageAccessKeyJSONRequestBody = CreateStaticCredentialInputBody

// CreateObjectStorageBucketAliasJSONRequestBody defines body for CreateObjectStorageBucketAlias for application/json ContentType.
type CreateObjectStorageBucketAliasJSONRequestBody = CreateAliasInputBody

// CreateObjectStorageMtlsPrincipalJSONRequestBody defines body for CreateObjectStorageMtlsPrincipal for application/json ContentType.
type CreateObjectStorageMtlsPrincipalJSONRequestBody = CreateMTLSCredentialInputBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DeleteObjectStorageAccessKey request
	DeleteObjectStorageAccessKey(ctx context.Context, accessKeyId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RollObjectStorageAccessKey request
	RollObjectStorageAccessKey(ctx context.Context, accessKeyId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListObjectStorageBuckets request
	ListObjectStorageBuckets(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateObjectStorageBucketWithBody request with any body
	CreateObjectStorageBucketWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateObjectStorageBucket(ctx context.Context, body CreateObjectStorageBucketJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteObjectStorageBucket request
	DeleteObjectStorageBucket(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetObjectStorageBucket request
	GetObjectStorageBucket(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateObjectStorageBucketWithBody request with any body
	UpdateObjectStorageBucketWithBody(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateObjectStorageBucket(ctx context.Context, bucketId string, body UpdateObjectStorageBucketJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateObjectStorageAccessKeyWithBody request with any body
	CreateObjectStorageAccessKeyWithBody(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateObjectStorageAccessKey(ctx context.Context, bucketId string, body CreateObjectStorageAccessKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListObjectStorageBucketAliases request
	ListObjectStorageBucketAliases(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateObjectStorageBucketAliasWithBody request with any body
	CreateObjectStorageBucketAliasWithBody(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateObjectStorageBucketAlias(ctx context.Context, bucketId string, body CreateObjectStorageBucketAliasJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteObjectStorageBucketAlias request
	DeleteObjectStorageBucketAlias(ctx context.Context, bucketId string, alias string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListObjectStorageCredentials request
	ListObjectStorageCredentials(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateObjectStorageMtlsPrincipalWithBody request with any body
	CreateObjectStorageMtlsPrincipalWithBody(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateObjectStorageMtlsPrincipal(ctx context.Context, bucketId string, body CreateObjectStorageMtlsPrincipalJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteObjectStorageMtlsPrincipal request
	DeleteObjectStorageMtlsPrincipal(ctx context.Context, bucketId string, credentialId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DeleteObjectStorageAccessKey(ctx context.Context, accessKeyId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteObjectStorageAccessKeyRequest(c.Server, accessKeyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RollObjectStorageAccessKey(ctx context.Context, accessKeyId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRollObjectStorageAccessKeyRequest(c.Server, accessKeyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListObjectStorageBuckets(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListObjectStorageBucketsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateObjectStorageBucketWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateObjectStorageBucketRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateObjectStorageBucket(ctx context.Context, body CreateObjectStorageBucketJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateObjectStorageBucketRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteObjectStorageBucket(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteObjectStorageBucketRequest(c.Server, bucketId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetObjectStorageBucket(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetObjectStorageBucketRequest(c.Server, bucketId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateObjectStorageBucketWithBody(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateObjectStorageBucketRequestWithBody(c.Server, bucketId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateObjectStorageBucket(ctx context.Context, bucketId string, body UpdateObjectStorageBucketJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateObjectStorageBucketRequest(c.Server, bucketId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateObjectStorageAccessKeyWithBody(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateObjectStorageAccessKeyRequestWithBody(c.Server, bucketId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateObjectStorageAccessKey(ctx context.Context, bucketId string, body CreateObjectStorageAccessKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateObjectStorageAccessKeyRequest(c.Server, bucketId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListObjectStorageBucketAliases(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListObjectStorageBucketAliasesRequest(c.Server, bucketId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateObjectStorageBucketAliasWithBody(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateObjectStorageBucketAliasRequestWithBody(c.Server, bucketId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateObjectStorageBucketAlias(ctx context.Context, bucketId string, body CreateObjectStorageBucketAliasJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateObjectStorageBucketAliasRequest(c.Server, bucketId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteObjectStorageBucketAlias(ctx context.Context, bucketId string, alias string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteObjectStorageBucketAliasRequest(c.Server, bucketId, alias)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListObjectStorageCredentials(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListObjectStorageCredentialsRequest(c.Server, bucketId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateObjectStorageMtlsPrincipalWithBody(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateObjectStorageMtlsPrincipalRequestWithBody(c.Server, bucketId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateObjectStorageMtlsPrincipal(ctx context.Context, bucketId string, body CreateObjectStorageMtlsPrincipalJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateObjectStorageMtlsPrincipalRequest(c.Server, bucketId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteObjectStorageMtlsPrincipal(ctx context.Context, bucketId string, credentialId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteObjectStorageMtlsPrincipalRequest(c.Server, bucketId, credentialId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDeleteObjectStorageAccessKeyRequest generates requests for DeleteObjectStorageAccessKey
func NewDeleteObjectStorageAccessKeyRequest(server string, accessKeyId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "access_key_id", accessKeyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/access-keys/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRollObjectStorageAccessKeyRequest generates requests for RollObjectStorageAccessKey
func NewRollObjectStorageAccessKeyRequest(server string, accessKeyId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "access_key_id", accessKeyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/access-keys/%s/roll", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListObjectStorageBucketsRequest generates requests for ListObjectStorageBuckets
func NewListObjectStorageBucketsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/buckets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateObjectStorageBucketRequest calls the generic CreateObjectStorageBucket builder with application/json body
func NewCreateObjectStorageBucketRequest(server string, body CreateObjectStorageBucketJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateObjectStorageBucketRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateObjectStorageBucketRequestWithBody generates requests for CreateObjectStorageBucket with any type of body
func NewCreateObjectStorageBucketRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/buckets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteObjectStorageBucketRequest generates requests for DeleteObjectStorageBucket
func NewDeleteObjectStorageBucketRequest(server string, bucketId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucket_id", bucketId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/buckets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetObjectStorageBucketRequest generates requests for GetObjectStorageBucket
func NewGetObjectStorageBucketRequest(server string, bucketId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucket_id", bucketId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/buckets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateObjectStorageBucketRequest calls the generic UpdateObjectStorageBucket builder with application/json body
func NewUpdateObjectStorageBucketRequest(server string, bucketId string, body UpdateObjectStorageBucketJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateObjectStorageBucketRequestWithBody(server, bucketId, "application/json", bodyReader)
}

// NewUpdateObjectStorageBucketRequestWithBody generates requests for UpdateObjectStorageBucket with any type of body
func NewUpdateObjectStorageBucketRequestWithBody(server string, bucketId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucket_id", bucketId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/buckets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateObjectStorageAccessKeyRequest calls the generic CreateObjectStorageAccessKey builder with application/json body
func NewCreateObjectStorageAccessKeyRequest(server string, bucketId string, body CreateObjectStorageAccessKeyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateObjectStorageAccessKeyRequestWithBody(server, bucketId, "application/json", bodyReader)
}

// NewCreateObjectStorageAccessKeyRequestWithBody generates requests for CreateObjectStorageAccessKey with any type of body
func NewCreateObjectStorageAccessKeyRequestWithBody(server string, bucketId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucket_id", bucketId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/buckets/%s/access-keys", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListObjectStorageBucketAliasesRequest generates requests for ListObjectStorageBucketAliases
func NewListObjectStorageBucketAliasesRequest(server string, bucketId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucket_id", bucketId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/buckets/%s/aliases", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateObjectStorageBucketAliasRequest calls the generic CreateObjectStorageBucketAlias builder with application/json body
func NewCreateObjectStorageBucketAliasRequest(server string, bucketId string, body CreateObjectStorageBucketAliasJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateObjectStorageBucketAliasRequestWithBody(server, bucketId, "application/json", bodyReader)
}

// NewCreateObjectStorageBucketAliasRequestWithBody generates requests for CreateObjectStorageBucketAlias with any type of body
func NewCreateObjectStorageBucketAliasRequestWithBody(server string, bucketId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucket_id", bucketId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/buckets/%s/aliases", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteObjectStorageBucketAliasRequest generates requests for DeleteObjectStorageBucketAlias
func NewDeleteObjectStorageBucketAliasRequest(server string, bucketId string, alias string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucket_id", bucketId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "alias", alias, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/buckets/%s/aliases/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListObjectStorageCredentialsRequest generates requests for ListObjectStorageCredentials
func NewListObjectStorageCredentialsRequest(server string, bucketId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucket_id", bucketId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/buckets/%s/credentials", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateObjectStorageMtlsPrincipalRequest calls the generic CreateObjectStorageMtlsPrincipal builder with application/json body
func NewCreateObjectStorageMtlsPrincipalRequest(server string, bucketId string, body CreateObjectStorageMtlsPrincipalJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateObjectStorageMtlsPrincipalRequestWithBody(server, bucketId, "application/json", bodyReader)
}

// NewCreateObjectStorageMtlsPrincipalRequestWithBody generates requests for CreateObjectStorageMtlsPrincipal with any type of body
func NewCreateObjectStorageMtlsPrincipalRequestWithBody(server string, bucketId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucket_id", bucketId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/buckets/%s/mtls-principals", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteObjectStorageMtlsPrincipalRequest generates requests for DeleteObjectStorageMtlsPrincipal
func NewDeleteObjectStorageMtlsPrincipalRequest(server string, bucketId string, credentialId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "bucket_id", bucketId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "credential_id", credentialId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/buckets/%s/mtls-principals/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DeleteObjectStorageAccessKeyWithResponse request
	DeleteObjectStorageAccessKeyWithResponse(ctx context.Context, accessKeyId string, reqEditors ...RequestEditorFn) (*DeleteObjectStorageAccessKeyResponse, error)

	// RollObjectStorageAccessKeyWithResponse request
	RollObjectStorageAccessKeyWithResponse(ctx context.Context, accessKeyId string, reqEditors ...RequestEditorFn) (*RollObjectStorageAccessKeyResponse, error)

	// ListObjectStorageBucketsWithResponse request
	ListObjectStorageBucketsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListObjectStorageBucketsResponse, error)

	// CreateObjectStorageBucketWithBodyWithResponse request with any body
	CreateObjectStorageBucketWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateObjectStorageBucketResponse, error)

	CreateObjectStorageBucketWithResponse(ctx context.Context, body CreateObjectStorageBucketJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateObjectStorageBucketResponse, error)

	// DeleteObjectStorageBucketWithResponse request
	DeleteObjectStorageBucketWithResponse(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*DeleteObjectStorageBucketResponse, error)

	// GetObjectStorageBucketWithResponse request
	GetObjectStorageBucketWithResponse(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*GetObjectStorageBucketResponse, error)

	// UpdateObjectStorageBucketWithBodyWithResponse request with any body
	UpdateObjectStorageBucketWithBodyWithResponse(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateObjectStorageBucketResponse, error)

	UpdateObjectStorageBucketWithResponse(ctx context.Context, bucketId string, body UpdateObjectStorageBucketJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateObjectStorageBucketResponse, error)

	// CreateObjectStorageAccessKeyWithBodyWithResponse request with any body
	CreateObjectStorageAccessKeyWithBodyWithResponse(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateObjectStorageAccessKeyResponse, error)

	CreateObjectStorageAccessKeyWithResponse(ctx context.Context, bucketId string, body CreateObjectStorageAccessKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateObjectStorageAccessKeyResponse, error)

	// ListObjectStorageBucketAliasesWithResponse request
	ListObjectStorageBucketAliasesWithResponse(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*ListObjectStorageBucketAliasesResponse, error)

	// CreateObjectStorageBucketAliasWithBodyWithResponse request with any body
	CreateObjectStorageBucketAliasWithBodyWithResponse(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateObjectStorageBucketAliasResponse, error)

	CreateObjectStorageBucketAliasWithResponse(ctx context.Context, bucketId string, body CreateObjectStorageBucketAliasJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateObjectStorageBucketAliasResponse, error)

	// DeleteObjectStorageBucketAliasWithResponse request
	DeleteObjectStorageBucketAliasWithResponse(ctx context.Context, bucketId string, alias string, reqEditors ...RequestEditorFn) (*DeleteObjectStorageBucketAliasResponse, error)

	// ListObjectStorageCredentialsWithResponse request
	ListObjectStorageCredentialsWithResponse(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*ListObjectStorageCredentialsResponse, error)

	// CreateObjectStorageMtlsPrincipalWithBodyWithResponse request with any body
	CreateObjectStorageMtlsPrincipalWithBodyWithResponse(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateObjectStorageMtlsPrincipalResponse, error)

	CreateObjectStorageMtlsPrincipalWithResponse(ctx context.Context, bucketId string, body CreateObjectStorageMtlsPrincipalJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateObjectStorageMtlsPrincipalResponse, error)

	// DeleteObjectStorageMtlsPrincipalWithResponse request
	DeleteObjectStorageMtlsPrincipalWithResponse(ctx context.Context, bucketId string, credentialId string, reqEditors ...RequestEditorFn) (*DeleteObjectStorageMtlsPrincipalResponse, error)
}

type DeleteObjectStorageAccessKeyResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r DeleteObjectStorageAccessKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteObjectStorageAccessKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RollObjectStorageAccessKeyResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *CredentialSecretView
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r RollObjectStorageAccessKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RollObjectStorageAccessKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListObjectStorageBucketsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *[]BucketView
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r ListObjectStorageBucketsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListObjectStorageBucketsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateObjectStorageBucketResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *BucketView
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r CreateObjectStorageBucketResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateObjectStorageBucketResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteObjectStorageBucketResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r DeleteObjectStorageBucketResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteObjectStorageBucketResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetObjectStorageBucketResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *BucketView
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetObjectStorageBucketResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetObjectStorageBucketResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateObjectStorageBucketResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *BucketView
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r UpdateObjectStorageBucketResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateObjectStorageBucketResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateObjectStorageAccessKeyResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *CredentialSecretView
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r CreateObjectStorageAccessKeyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateObjectStorageAccessKeyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListObjectStorageBucketAliasesResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *[]AliasView
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r ListObjectStorageBucketAliasesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListObjectStorageBucketAliasesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateObjectStorageBucketAliasResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *AliasView
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r CreateObjectStorageBucketAliasResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateObjectStorageBucketAliasResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteObjectStorageBucketAliasResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r DeleteObjectStorageBucketAliasResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteObjectStorageBucketAliasResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListObjectStorageCredentialsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *[]CredentialView
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r ListObjectStorageCredentialsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListObjectStorageCredentialsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateObjectStorageMtlsPrincipalResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *BucketView
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r CreateObjectStorageMtlsPrincipalResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateObjectStorageMtlsPrincipalResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteObjectStorageMtlsPrincipalResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r DeleteObjectStorageMtlsPrincipalResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteObjectStorageMtlsPrincipalResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// DeleteObjectStorageAccessKeyWithResponse request returning *DeleteObjectStorageAccessKeyResponse
func (c *ClientWithResponses) DeleteObjectStorageAccessKeyWithResponse(ctx context.Context, accessKeyId string, reqEditors ...RequestEditorFn) (*DeleteObjectStorageAccessKeyResponse, error) {
	rsp, err := c.DeleteObjectStorageAccessKey(ctx, accessKeyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteObjectStorageAccessKeyResponse(rsp)
}

// RollObjectStorageAccessKeyWithResponse request returning *RollObjectStorageAccessKeyResponse
func (c *ClientWithResponses) RollObjectStorageAccessKeyWithResponse(ctx context.Context, accessKeyId string, reqEditors ...RequestEditorFn) (*RollObjectStorageAccessKeyResponse, error) {
	rsp, err := c.RollObjectStorageAccessKey(ctx, accessKeyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRollObjectStorageAccessKeyResponse(rsp)
}

// ListObjectStorageBucketsWithResponse request returning *ListObjectStorageBucketsResponse
func (c *ClientWithResponses) ListObjectStorageBucketsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListObjectStorageBucketsResponse, error) {
	rsp, err := c.ListObjectStorageBuckets(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListObjectStorageBucketsResponse(rsp)
}

// CreateObjectStorageBucketWithBodyWithResponse request with arbitrary body returning *CreateObjectStorageBucketResponse
func (c *ClientWithResponses) CreateObjectStorageBucketWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateObjectStorageBucketResponse, error) {
	rsp, err := c.CreateObjectStorageBucketWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateObjectStorageBucketResponse(rsp)
}

func (c *ClientWithResponses) CreateObjectStorageBucketWithResponse(ctx context.Context, body CreateObjectStorageBucketJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateObjectStorageBucketResponse, error) {
	rsp, err := c.CreateObjectStorageBucket(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateObjectStorageBucketResponse(rsp)
}

// DeleteObjectStorageBucketWithResponse request returning *DeleteObjectStorageBucketResponse
func (c *ClientWithResponses) DeleteObjectStorageBucketWithResponse(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*DeleteObjectStorageBucketResponse, error) {
	rsp, err := c.DeleteObjectStorageBucket(ctx, bucketId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteObjectStorageBucketResponse(rsp)
}

// GetObjectStorageBucketWithResponse request returning *GetObjectStorageBucketResponse
func (c *ClientWithResponses) GetObjectStorageBucketWithResponse(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*GetObjectStorageBucketResponse, error) {
	rsp, err := c.GetObjectStorageBucket(ctx, bucketId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetObjectStorageBucketResponse(rsp)
}

// UpdateObjectStorageBucketWithBodyWithResponse request with arbitrary body returning *UpdateObjectStorageBucketResponse
func (c *ClientWithResponses) UpdateObjectStorageBucketWithBodyWithResponse(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateObjectStorageBucketResponse, error) {
	rsp, err := c.UpdateObjectStorageBucketWithBody(ctx, bucketId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateObjectStorageBucketResponse(rsp)
}

func (c *ClientWithResponses) UpdateObjectStorageBucketWithResponse(ctx context.Context, bucketId string, body UpdateObjectStorageBucketJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateObjectStorageBucketResponse, error) {
	rsp, err := c.UpdateObjectStorageBucket(ctx, bucketId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateObjectStorageBucketResponse(rsp)
}

// CreateObjectStorageAccessKeyWithBodyWithResponse request with arbitrary body returning *CreateObjectStorageAccessKeyResponse
func (c *ClientWithResponses) CreateObjectStorageAccessKeyWithBodyWithResponse(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateObjectStorageAccessKeyResponse, error) {
	rsp, err := c.CreateObjectStorageAccessKeyWithBody(ctx, bucketId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateObjectStorageAccessKeyResponse(rsp)
}

func (c *ClientWithResponses) CreateObjectStorageAccessKeyWithResponse(ctx context.Context, bucketId string, body CreateObjectStorageAccessKeyJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateObjectStorageAccessKeyResponse, error) {
	rsp, err := c.CreateObjectStorageAccessKey(ctx, bucketId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateObjectStorageAccessKeyResponse(rsp)
}

// ListObjectStorageBucketAliasesWithResponse request returning *ListObjectStorageBucketAliasesResponse
func (c *ClientWithResponses) ListObjectStorageBucketAliasesWithResponse(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*ListObjectStorageBucketAliasesResponse, error) {
	rsp, err := c.ListObjectStorageBucketAliases(ctx, bucketId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListObjectStorageBucketAliasesResponse(rsp)
}

// CreateObjectStorageBucketAliasWithBodyWithResponse request with arbitrary body returning *CreateObjectStorageBucketAliasResponse
func (c *ClientWithResponses) CreateObjectStorageBucketAliasWithBodyWithResponse(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateObjectStorageBucketAliasResponse, error) {
	rsp, err := c.CreateObjectStorageBucketAliasWithBody(ctx, bucketId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateObjectStorageBucketAliasResponse(rsp)
}

func (c *ClientWithResponses) CreateObjectStorageBucketAliasWithResponse(ctx context.Context, bucketId string, body CreateObjectStorageBucketAliasJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateObjectStorageBucketAliasResponse, error) {
	rsp, err := c.CreateObjectStorageBucketAlias(ctx, bucketId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateObjectStorageBucketAliasResponse(rsp)
}

// DeleteObjectStorageBucketAliasWithResponse request returning *DeleteObjectStorageBucketAliasResponse
func (c *ClientWithResponses) DeleteObjectStorageBucketAliasWithResponse(ctx context.Context, bucketId string, alias string, reqEditors ...RequestEditorFn) (*DeleteObjectStorageBucketAliasResponse, error) {
	rsp, err := c.DeleteObjectStorageBucketAlias(ctx, bucketId, alias, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteObjectStorageBucketAliasResponse(rsp)
}

// ListObjectStorageCredentialsWithResponse request returning *ListObjectStorageCredentialsResponse
func (c *ClientWithResponses) ListObjectStorageCredentialsWithResponse(ctx context.Context, bucketId string, reqEditors ...RequestEditorFn) (*ListObjectStorageCredentialsResponse, error) {
	rsp, err := c.ListObjectStorageCredentials(ctx, bucketId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListObjectStorageCredentialsResponse(rsp)
}

// CreateObjectStorageMtlsPrincipalWithBodyWithResponse request with arbitrary body returning *CreateObjectStorageMtlsPrincipalResponse
func (c *ClientWithResponses) CreateObjectStorageMtlsPrincipalWithBodyWithResponse(ctx context.Context, bucketId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateObjectStorageMtlsPrincipalResponse, error) {
	rsp, err := c.CreateObjectStorageMtlsPrincipalWithBody(ctx, bucketId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateObjectStorageMtlsPrincipalResponse(rsp)
}

func (c *ClientWithResponses) CreateObjectStorageMtlsPrincipalWithResponse(ctx context.Context, bucketId string, body CreateObjectStorageMtlsPrincipalJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateObjectStorageMtlsPrincipalResponse, error) {
	rsp, err := c.CreateObjectStorageMtlsPrincipal(ctx, bucketId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateObjectStorageMtlsPrincipalResponse(rsp)
}

// DeleteObjectStorageMtlsPrincipalWithResponse request returning *DeleteObjectStorageMtlsPrincipalResponse
func (c *ClientWithResponses) DeleteObjectStorageMtlsPrincipalWithResponse(ctx context.Context, bucketId string, credentialId string, reqEditors ...RequestEditorFn) (*DeleteObjectStorageMtlsPrincipalResponse, error) {
	rsp, err := c.DeleteObjectStorageMtlsPrincipal(ctx, bucketId, credentialId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteObjectStorageMtlsPrincipalResponse(rsp)
}

// ParseDeleteObjectStorageAccessKeyResponse parses an HTTP response from a DeleteObjectStorageAccessKeyWithResponse call
func ParseDeleteObjectStorageAccessKeyResponse(rsp *http.Response) (*DeleteObjectStorageAccessKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteObjectStorageAccessKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseRollObjectStorageAccessKeyResponse parses an HTTP response from a RollObjectStorageAccessKeyWithResponse call
func ParseRollObjectStorageAccessKeyResponse(rsp *http.Response) (*RollObjectStorageAccessKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RollObjectStorageAccessKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CredentialSecretView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseListObjectStorageBucketsResponse parses an HTTP response from a ListObjectStorageBucketsWithResponse call
func ParseListObjectStorageBucketsResponse(rsp *http.Response) (*ListObjectStorageBucketsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListObjectStorageBucketsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []BucketView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseCreateObjectStorageBucketResponse parses an HTTP response from a CreateObjectStorageBucketWithResponse call
func ParseCreateObjectStorageBucketResponse(rsp *http.Response) (*CreateObjectStorageBucketResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateObjectStorageBucketResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BucketView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteObjectStorageBucketResponse parses an HTTP response from a DeleteObjectStorageBucketWithResponse call
func ParseDeleteObjectStorageBucketResponse(rsp *http.Response) (*DeleteObjectStorageBucketResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteObjectStorageBucketResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetObjectStorageBucketResponse parses an HTTP response from a GetObjectStorageBucketWithResponse call
func ParseGetObjectStorageBucketResponse(rsp *http.Response) (*GetObjectStorageBucketResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetObjectStorageBucketResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BucketView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateObjectStorageBucketResponse parses an HTTP response from a UpdateObjectStorageBucketWithResponse call
func ParseUpdateObjectStorageBucketResponse(rsp *http.Response) (*UpdateObjectStorageBucketResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateObjectStorageBucketResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BucketView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseCreateObjectStorageAccessKeyResponse parses an HTTP response from a CreateObjectStorageAccessKeyWithResponse call
func ParseCreateObjectStorageAccessKeyResponse(rsp *http.Response) (*CreateObjectStorageAccessKeyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateObjectStorageAccessKeyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CredentialSecretView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseListObjectStorageBucketAliasesResponse parses an HTTP response from a ListObjectStorageBucketAliasesWithResponse call
func ParseListObjectStorageBucketAliasesResponse(rsp *http.Response) (*ListObjectStorageBucketAliasesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListObjectStorageBucketAliasesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []AliasView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseCreateObjectStorageBucketAliasResponse parses an HTTP response from a CreateObjectStorageBucketAliasWithResponse call
func ParseCreateObjectStorageBucketAliasResponse(rsp *http.Response) (*CreateObjectStorageBucketAliasResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateObjectStorageBucketAliasResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AliasView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteObjectStorageBucketAliasResponse parses an HTTP response from a DeleteObjectStorageBucketAliasWithResponse call
func ParseDeleteObjectStorageBucketAliasResponse(rsp *http.Response) (*DeleteObjectStorageBucketAliasResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteObjectStorageBucketAliasResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseListObjectStorageCredentialsResponse parses an HTTP response from a ListObjectStorageCredentialsWithResponse call
func ParseListObjectStorageCredentialsResponse(rsp *http.Response) (*ListObjectStorageCredentialsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListObjectStorageCredentialsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []CredentialView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseCreateObjectStorageMtlsPrincipalResponse parses an HTTP response from a CreateObjectStorageMtlsPrincipalWithResponse call
func ParseCreateObjectStorageMtlsPrincipalResponse(rsp *http.Response) (*CreateObjectStorageMtlsPrincipalResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateObjectStorageMtlsPrincipalResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BucketView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteObjectStorageMtlsPrincipalResponse parses an HTTP response from a DeleteObjectStorageMtlsPrincipalWithResponse call
func ParseDeleteObjectStorageMtlsPrincipalResponse(rsp *http.Response) (*DeleteObjectStorageMtlsPrincipalResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteObjectStorageMtlsPrincipalResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
