load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "s3artifact",
    srcs = ["s3artifact.go"],
    importpath = "github.com/verself/deployment-tools/internal/s3artifact",
    visibility = ["//src/tools/deployment:__subpackages__"],
    deps = [
        "//src/tools/deployment/internal/deploymodel",
        "@com_github_aws_aws_sdk_go_v2//aws",
        "@com_github_aws_aws_sdk_go_v2//aws/signer/v4:signer",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//codes",
        "@io_opentelemetry_go_otel_trace//:trace",
    ],
)
