load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "s3artifact",
    srcs = ["s3artifact.go"],
    importpath = "github.com/verself/deployment-tools/internal/s3artifact",
    visibility = ["//src/tools/deployment:__subpackages__"],
    deps = [
        "//src/tools/deployment/internal/deploymodel",
        "@com_github_aws_aws_sdk_go_v2//aws",
        "@com_github_aws_aws_sdk_go_v2//aws/signer/v4:signer",
    ],
)

go_test(
    name = "s3artifact_test",
    srcs = ["s3artifact_test.go"],
    embed = [":s3artifact"],
)
