# gazelle:prefix github.com/verself/billing-service

load("//src/infrastructure-components/spire:identity.bzl", "spire_identity")
load("//src/tools/build:go_module_checks.bzl", "go_module_checks")

go_module_checks()

spire_identity(
    name = "spiffe_identity",
    component = "billing",
    entry_id = "verself-billing-service",
    key = "billing.default",
    path = "/svc/billing-service",
    user = "billing",
    visibility = ["//src/infrastructure-components/spire:__pkg__"],
)
