load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "siteconfig",
    srcs = ["siteconfig.go"],
    importpath = "github.com/verself/deployment-service/siteconfig",
    visibility = ["//visibility:public"],
    deps = [
        "@org_cuelang_go//cue",
        "@org_cuelang_go//cue/cuecontext",
    ],
)
