haproxy_public_routes:
  - host: '{{ distribution_service_domain }}'
    backend: be_route_product_distribution_api_distribution_service_public_api
  - host: '{{ "oci." ~ verself_domain }}'
    backend: be_route_product_distribution_api_distribution_service_public_api
haproxy_public_apis:
  - key: distribution
    host: '{{ distribution_service_domain }}'
    path_prefix: /api/v1
  - key: oci
    host: '{{ "oci." ~ verself_domain }}'
    path_prefix: /v2
