load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "nomad-recover_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/infrastructure-components/nomad/cmd/nomad-recover",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "nomad-recover",
    embed = [":nomad-recover_lib"],
    visibility = ["//visibility:public"],
)
