package(default_visibility = ["//visibility:public"])

filegroup(
    name = "nftables_sources",
    srcs = [
        "ansible/host-files/etc/nftables.conf",
        "ansible/host-files/etc/systemd/system/verself-firewall.target",
        "ansible/playbooks/nftables.yml",
    ] + glob(
        [
            "ansible/host-files/etc/nftables.d/**",
            "ansible/roles/nftables/**",
        ],
        allow_empty = False,
    ),
)
