http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "host_tool_nomad_zip",
    downloaded_file_path = "nomad_1.11.3_linux_amd64.zip",
    sha256 = "19dac5642a2ba5305e6ff8efee06a708d760ebe4d1cd7936bc3dc526f477dc12",
    url = "https://releases.hashicorp.com/nomad/1.11.3/nomad_1.11.3_linux_amd64.zip",
)

http_file(
    name = "host_tool_spire_tgz",
    downloaded_file_path = "spire-1.14.5-linux-amd64-musl.tar.gz",
    sha256 = "cacab9ff32b7a24714edcf4328c4ce27bddd38496b443e8750395883c72a3bfb",
    url = "https://github.com/spiffe/spire/releases/download/v1.14.5/spire-1.14.5-linux-amd64-musl.tar.gz",
)
