load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "bundle",
    srcs = [
        "keyring.go",
        "oci.go",
        "sign.go",
        "verify.go",
    ],
    importpath = "github.com/verself/attestation/bundle",
    visibility = ["//visibility:public"],
    deps = [
        "//src/attestation/go/predicate",
        "@com_github_opencontainers_go_digest//:go-digest",
        "@com_github_opencontainers_image_spec//specs-go/v1:specs-go",
        "@com_github_sigstore_protobuf_specs//gen/pb-go/bundle/v1:bundle",
        "@com_github_sigstore_sigstore//pkg/signature",
        "@com_github_sigstore_sigstore_go//pkg/bundle",
        "@com_github_sigstore_sigstore_go//pkg/root",
        "@com_github_sigstore_sigstore_go//pkg/sign",
        "@com_github_sigstore_sigstore_go//pkg/verify",
        "@land_oras_oras_go_v2//:oras-go",
        "@land_oras_oras_go_v2//content/memory",
        "@org_golang_google_protobuf//encoding/protojson",
    ],
)

go_test(
    name = "bundle_test",
    srcs = ["keyring_test.go"],
    embed = [":bundle"],
)
