load("@io_bazel_rules_go//go:def.bzl", "go_test")

alias(
    name = "hyperfine",
    actual = "@guardian_specification_tools//tools/hyperfine",
    visibility = ["//visibility:public"],
)

go_test(
    name = "board_benchmark",
    timeout = "long",
    srcs = ["board_benchmark_test.go"],
    args = [
        "-test.run=__benchmark_only__",
        "-test.bench=BenchmarkGuardianBoard",
        "-test.benchtime=10x",
        "-test.benchmem",
    ],
    tags = [
        "local",
        "manual",
    ],
)
