load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "uploadbundle",
    srcs = ["archive.go"],
    importpath = "github.com/verself/guardian-specification/cli/internal/uploadbundle",
    visibility = ["//src/guardian-specification/cli:__subpackages__"],
)

go_test(
    name = "uploadbundle_test",
    srcs = ["archive_test.go"],
    embed = [":uploadbundle"],
)
