load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "temporal-recover_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/temporal-platform/cmd/temporal-recover",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "temporal-recover",
    embed = [":temporal-recover_lib"],
    visibility = ["//visibility:public"],
)
