load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "smithy-artifact_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/verself/src/smithy/cmd/smithy-artifact",
    visibility = ["//visibility:private"],
    deps = ["@in_gopkg_yaml_v3//:yaml_v3"],
)

go_binary(
    name = "smithy-artifact",
    embed = [":smithy-artifact_lib"],
    visibility = ["//visibility:public"],
)
