# gazelle:prefix github.com/verself/infrastructure-components/nomad-observer

load("//src/tools/build:go_module_checks.bzl", "go_module_checks")
load("//src/tools/deployment/nomad:component.bzl", "nomad_component")
load("//src/tools/deployment/spire:identity.bzl", "spire_identity")

go_module_checks()

filegroup(
    name = "guardian_crd",
    srcs = glob(["guardian/**/*.cue"]),
    visibility = ["//visibility:public"],
)

spire_identity(
    name = "spiffe_identity",
    component = "nomad_observer",
    entry_id = "verself-nomad-observer",
    key = "nomad_observer.default",
    path = "/svc/nomad-observer",
    user = "nomad_observer",
    visibility = ["//src/infrastructure-components/spire:__pkg__"],
)

nomad_component(
    name = "nomad_component",
    component = "nomad-observer",
    deploy_phase = "platform",
    job_id = "nomad-observer",
    job_spec = "nomad.hcl",
    pre_artifacts = {
        "//src/infrastructure-components/nomad-observer/cmd/nomad-observer:nomad-observer_nomad_artifact": "nomad-observer",
    },
    visibility = ["//src/tools/deployment/nomad:__pkg__"],
)
