---
- name: Restart temporal-server
  listen: restart temporal-server
  ansible.builtin.systemd:
    name: temporal-server
    state: restarted
    daemon_reload: true
  failed_when: false

- name: Restart temporal-proof-worker
  listen: restart temporal-proof-worker
  ansible.builtin.systemd:
    name: temporal-proof-worker
    state: restarted
    daemon_reload: true
  failed_when: false
