# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class AuthListSessionsResponseSessionCreatedDevice(BaseModel):
    label: str
    kind: str
    browser_name: Optional[str] = Field(default=None, alias="browserName")
    os_name: Optional[str] = Field(default=None, alias="osName")


class AuthListSessionsResponseSessionCreatedLocation(BaseModel):
    country_code: Optional[str] = Field(default=None, alias="countryCode")
    region: Optional[str] = None
    city: Optional[str] = None


class AuthListSessionsResponseSessionDevice(BaseModel):
    label: str
    kind: str
    browser_name: Optional[str] = Field(default=None, alias="browserName")
    os_name: Optional[str] = Field(default=None, alias="osName")


class AuthListSessionsResponseSessionLocation(BaseModel):
    country_code: Optional[str] = Field(default=None, alias="countryCode")
    region: Optional[str] = None
    city: Optional[str] = None


class AuthListSessionsResponseSession(BaseModel):
    session_handle: str = Field(alias="sessionHandle")
    is_current: bool = Field(alias="isCurrent")
    created_at: datetime = Field(alias="createdAt")
    last_seen_at: datetime = Field(alias="lastSeenAt")
    expires_at: datetime = Field(alias="expiresAt")
    created_client_ip: Optional[str] = Field(default=None, alias="createdClientIP")
    created_client_ip_trusted: bool = Field(alias="createdClientIPTrusted")
    created_client_ip_source: Optional[str] = Field(default=None, alias="createdClientIPSource")
    created_edge_peer_ip: Optional[str] = Field(default=None, alias="createdEdgePeerIP")
    created_user_agent: Optional[str] = Field(default=None, alias="createdUserAgent")
    created_device: AuthListSessionsResponseSessionCreatedDevice = Field(alias="createdDevice")
    created_location: AuthListSessionsResponseSessionCreatedLocation = Field(alias="createdLocation")
    client_ip: Optional[str] = Field(default=None, alias="clientIP")
    client_ip_trusted: bool = Field(alias="clientIPTrusted")
    client_ip_source: Optional[str] = Field(default=None, alias="clientIPSource")
    edge_peer_ip: Optional[str] = Field(default=None, alias="edgePeerIP")
    user_agent: Optional[str] = Field(default=None, alias="userAgent")
    device: AuthListSessionsResponseSessionDevice
    location: AuthListSessionsResponseSessionLocation


class AuthListSessionsResponse(BaseModel):
    sessions: List[AuthListSessionsResponseSession]
