# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from datetime import date, datetime  # noqa: F401
from decimal import Decimal  # noqa: F401
from typing import (  # noqa: F401
    Annotated, Any, Dict, List, Literal, Optional, TypedDict, Union,
)

from pydantic import Field  # noqa: F401

from .._core._models import BaseModel  # noqa: F401
from .._core._types import FileTypes  # noqa: F401
from .._utils import PropertyInfo  # noqa: F401


class AuthGetSessionResponseSnapshotAuth(BaseModel):
    is_authenticated: bool = Field(alias="isAuthenticated")
    user_id: Optional[str] = Field(default=None, alias="userId")
    org_id: Optional[str] = Field(default=None, alias="orgId")
    selected_org_id: Optional[str] = Field(default=None, alias="selectedOrgId")
    cache_partition: Optional[str] = Field(default=None, alias="cachePartition")


class AuthGetSessionResponseSnapshotUserAvailableOrganization(BaseModel):
    org_id: str = Field(alias="orgId")
    identity_provider_org_id: str = Field(alias="identityProviderOrgId")


class AuthGetSessionResponseSnapshotUser(BaseModel):
    sub: str
    email: Optional[str] = None
    name: Optional[str] = None
    preferred_username: Optional[str] = Field(default=None, alias="preferredUsername")
    home_org_id: Optional[str] = Field(default=None, alias="homeOrgId")
    selected_org_id: Optional[str] = Field(default=None, alias="selectedOrgId")
    org_id: Optional[str] = Field(default=None, alias="orgId")
    available_organizations: List[AuthGetSessionResponseSnapshotUserAvailableOrganization] = Field(alias="availableOrganizations")


class AuthGetSessionResponseSnapshotSessionDevice(BaseModel):
    label: str
    kind: str
    browser_name: Optional[str] = Field(default=None, alias="browserName")
    os_name: Optional[str] = Field(default=None, alias="osName")


class AuthGetSessionResponseSnapshotSessionLocation(BaseModel):
    country_code: Optional[str] = Field(default=None, alias="countryCode")
    region: Optional[str] = None
    city: Optional[str] = None


class AuthGetSessionResponseSnapshotSession(BaseModel):
    session_handle: str = Field(alias="sessionHandle")
    created_at: datetime = Field(alias="createdAt")
    last_seen_at: datetime = Field(alias="lastSeenAt")
    expires_at: datetime = Field(alias="expiresAt")
    auth_methods: List[str] = Field(alias="authMethods")
    client_ip: Optional[str] = Field(default=None, alias="clientIP")
    client_ip_trusted: bool = Field(alias="clientIPTrusted")
    client_ip_source: Optional[str] = Field(default=None, alias="clientIPSource")
    edge_peer_ip: Optional[str] = Field(default=None, alias="edgePeerIP")
    user_agent: Optional[str] = Field(default=None, alias="userAgent")
    device: AuthGetSessionResponseSnapshotSessionDevice
    location: AuthGetSessionResponseSnapshotSessionLocation


class AuthGetSessionResponseSnapshot(BaseModel):
    is_signed_in: bool = Field(alias="isSignedIn")
    auth: AuthGetSessionResponseSnapshotAuth
    user: Optional[AuthGetSessionResponseSnapshotUser] = None
    session: Optional[AuthGetSessionResponseSnapshotSession] = None


class AuthGetSessionResponse(BaseModel):
    snapshot: AuthGetSessionResponseSnapshot
