http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_archive(
    name = "chrome_headless_shell_linux64",
    build_file_content = """
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all",
    srcs = glob(["chrome-headless-shell-linux64/**"]),
)

filegroup(
    name = "chrome_headless_shell",
    srcs = ["chrome-headless-shell-linux64/chrome-headless-shell"],
)
""",
    sha256 = "6d7aa97cd3bbef45a7fc033cd78f3c8112b44312ea11e7f410375604f8b9287e",
    type = "zip",
    url = "https://storage.googleapis.com/chrome-for-testing-public/149.0.7827.22/linux64/chrome-headless-shell-linux64.zip",
)

http_file(
    name = "website_tool_nodejs",
    downloaded_file_path = "node-v22.22.2-linux-x64.tar.xz",
    sha256 = "88fd1ce767091fd8d4a99fdb2356e98c819f93f3b1f8663853a2dee9b438068a",
    url = "https://nodejs.org/dist/v22.22.2/node-v22.22.2-linux-x64.tar.xz",
)
