load("@rules_pkg//pkg:tar.bzl", "pkg_tar")

# gazelle:prefix github.com/verself/make-skill/release

alias(
    name = "mksk-release",
    actual = "//src/make-skill/release/cmd/mksk-release:mksk-release",
    visibility = ["//visibility:public"],
)

exports_files(["tools.lock.json"])

pkg_tar(
    name = "release_tools_artifact",
    out = "mksk-release-tools.tar",
    files = {
        "@mksk_release_tools//tools/bazel": "bin/bazel",
        "@mksk_release_tools//tools/cargo-about": "bin/cargo-about",
        "@mksk_release_tools//tools/syft": "bin/syft",
    },
    modes = {
        "bin/bazel": "0755",
        "bin/cargo-about": "0755",
        "bin/syft": "0755",
    },
    visibility = ["//visibility:public"],
)
