[workers]
vs-prod-w0 ansible_host=206.223.228.99

[infra]
vs-prod-w0 ansible_host=206.223.228.99

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args=-o IdentitiesOnly=yes
