[workers]
vs-dev-w0 ansible_host=access.verself.sh

[infra]
vs-dev-w0 ansible_host=access.verself.sh

[all:vars]
ansible_user=ubuntu@prod
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args=-o IdentitiesOnly=yes
