load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "verself_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/verself-cli/cmd/verself",
    visibility = ["//visibility:private"],
    deps = ["//src/verself-cli/internal/app"],
)

go_binary(
    name = "verself",
    embed = [":verself_lib"],
    visibility = ["//visibility:public"],
)
