---
- name: Reload systemd
  listen: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart ClickHouse
  listen: restart clickhouse
  ansible.builtin.systemd:
    name: clickhouse-server
    state: restarted

- name: Restart OTel Collector
  listen: restart otelcol
  ansible.builtin.systemd:
    name: otelcol
    state: restarted

- name: Restart HyperDX API
  listen: restart hyperdx-api
  ansible.builtin.systemd:
    name: hyperdx-api
    state: restarted

- name: Restart HyperDX App
  listen: restart hyperdx-app
  ansible.builtin.systemd:
    name: hyperdx-app
    state: restarted

- name: Restart Caddy
  listen: restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
