---
# monorepo_root points to the top-level repo.
guest_rootfs_monorepo_root: "{{ playbook_dir }}/../../../.."
guest_rootfs_bazel_bundle_label: //src/platform/guest:guest_artifacts_bundle
guest_rootfs_bazel_bundle_path: "{{ guest_rootfs_monorepo_root }}/bazel-bin/src/platform/guest/guest_artifacts_bundle.tar"
guest_rootfs_remote_tmp: /tmp
guest_rootfs_remote_bundle: "{{ guest_rootfs_remote_tmp }}/guest-artifacts-bundle.tar"
guest_rootfs_remote_path: "{{ verself_bin }}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
