---
- name: Create credstore directory for secrets-service
  ansible.builtin.file:
    path: /etc/credstore/secrets-service
    state: directory
    owner: root
    group: secrets_service
    mode: "0750"
