load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "openbao-recover_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/infrastructure-components/openbao/cmd/openbao-recover",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_protonmail_go_crypto//openpgp",
        "@org_golang_x_crypto//ripemd160",
    ],
)

go_binary(
    name = "openbao-recover",
    embed = [":openbao-recover_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "openbao-recover_test",
    srcs = ["main_test.go"],
    embed = [":openbao-recover_lib"],
    deps = ["@com_github_protonmail_go_crypto//openpgp"],
)
