load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "contractapi",
    srcs = ["contract.go"],
    importpath = "github.com/verself/object-storage-service/internal/contractapi",
    visibility = ["//src/services/object-storage-service:__subpackages__"],
)

alias(
    name = "go_default_library",
    actual = ":contractapi",
    visibility = ["//src/services/object-storage-service:__subpackages__"],
)
