haproxy_public_routes:
  - host: '{{ profile_service_domain }}'
    backend: be_route_product_profile_api_profile_service_public_api
haproxy_public_apis:
  - key: profile
    host: '{{ profile_service_domain }}'
    path_prefix: /api/v1
