load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")
load("//src/tools/deployment/nomad:artifact.bzl", "nomad_binary_artifact")

go_library(
    name = "zitadel-setup-apply_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/infrastructure-components/zitadel/cmd/zitadel-setup-apply",
    visibility = ["//visibility:private"],
    deps = [
        "//src/tools/observability/go/otel",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//codes",
    ],
)

go_binary(
    name = "zitadel-setup-apply",
    embed = [":lib"],
    visibility = ["//visibility:public"],
)

nomad_binary_artifact(
    name = "zitadel-setup-apply_nomad_artifact",
    binary = ":zitadel-setup-apply",
    output = "zitadel-setup-apply",
)

go_test(
    name = "zitadel-setup-apply_test",
    srcs = ["main_test.go"],
    embed = [":zitadel-setup-apply_lib"],
)

go_library(
    name = "lib",
    srcs = ["main.go"],
    importpath = "",
    visibility = ["//visibility:private"],
    deps = [
        "//src/tools/observability/go/otel",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//codes",
    ],
)

go_test(
    name = "lib_test",
    srcs = ["main_test.go"],
    embed = [":lib"],
)
