load("//src/tools/build:openapi_codegen.bzl", "verself_oapi_go_client")

verself_oapi_go_client(
    name = "internalclient",
    importpath = "github.com/verself/notifications-service/internalclient",
    package = "notificationsinternalclient",
    spec = "//src/services/notifications-service/openapi:internal-openapi-3.0.yaml",
    deps = [
        "@com_github_oapi_codegen_runtime//:runtime",
        "@com_github_oapi_codegen_runtime//types",
    ],
)

alias(
    name = "go_default_library",
    actual = ":internalclient",
    visibility = ["//visibility:public"],
)
