load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "grafana_node_runner_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/infrastructure-components/grafana/cmd/grafana-node-runner",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "grafana-node-runner",
    embed = [":grafana_node_runner_lib"],
    visibility = ["//visibility:public"],
)
