// Package identityinternalclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package identityinternalclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	MutualTLSScopes  = "mutualTLS.Scopes"
)

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Location Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
	Location *string `json:"location,omitempty"`

	// Message Error message text
	Message *string `json:"message,omitempty"`

	// Value The value at the given location
	Value interface{} `json:"value,omitempty"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Schema A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail *string `json:"detail,omitempty"`

	// Errors Optional list of individual error details
	Errors *[]ErrorDetail `json:"errors,omitempty"`

	// Instance A URI reference that identifies the specific occurrence of the problem.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int64 `json:"status,omitempty"`

	// Title A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
	Title *string `json:"title,omitempty"`

	// Type A URI reference to human-readable documentation for the error.
	Type *string `json:"type,omitempty"`
}

// IdentityOrganizationProfile defines model for IdentityOrganizationProfile.
type IdentityOrganizationProfile struct {
	DisplayName    string    `json:"display_name"`
	OrgId          string    `json:"org_id"`
	RedirectedFrom *string   `json:"redirected_from,omitempty"`
	Slug           string    `json:"slug"`
	State          string    `json:"state"`
	UpdatedAt      time.Time `json:"updated_at"`
	Version        int32     `json:"version"`
}

// IdentityResolveOrganizationRequest defines model for IdentityResolveOrganizationRequest.
type IdentityResolveOrganizationRequest struct {
	// Schema A URL to the JSON Schema for this object.
	Schema        *string `json:"$schema,omitempty"`
	OrgId         *string `json:"org_id,omitempty"`
	RequireActive bool    `json:"require_active"`
	Slug          *string `json:"slug,omitempty"`
}

// IdentityResolveOrganizationResponse defines model for IdentityResolveOrganizationResponse.
type IdentityResolveOrganizationResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema       *string                     `json:"$schema,omitempty"`
	Organization IdentityOrganizationProfile `json:"organization"`
}

// IdentityUpdateHumanProfileRequest defines model for IdentityUpdateHumanProfileRequest.
type IdentityUpdateHumanProfileRequest struct {
	// Schema A URL to the JSON Schema for this object.
	Schema      *string `json:"$schema,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	FamilyName  string  `json:"family_name"`
	GivenName   string  `json:"given_name"`
}

// IdentityUpdateHumanProfileResponse defines model for IdentityUpdateHumanProfileResponse.
type IdentityUpdateHumanProfileResponse struct {
	// Schema A URL to the JSON Schema for this object.
	Schema      *string   `json:"$schema,omitempty"`
	DisplayName string    `json:"display_name"`
	Email       string    `json:"email"`
	FamilyName  string    `json:"family_name"`
	GivenName   string    `json:"given_name"`
	SubjectId   string    `json:"subject_id"`
	SyncedAt    time.Time `json:"synced_at"`
}

// ResolveOrganizationJSONRequestBody defines body for ResolveOrganization for application/json ContentType.
type ResolveOrganizationJSONRequestBody = IdentityResolveOrganizationRequest

// UpdateHumanProfileJSONRequestBody defines body for UpdateHumanProfile for application/json ContentType.
type UpdateHumanProfileJSONRequestBody = IdentityUpdateHumanProfileRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ResolveOrganizationWithBody request with any body
	ResolveOrganizationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ResolveOrganization(ctx context.Context, body ResolveOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateHumanProfileWithBody request with any body
	UpdateHumanProfileWithBody(ctx context.Context, subjectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateHumanProfile(ctx context.Context, subjectId string, body UpdateHumanProfileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ResolveOrganizationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResolveOrganizationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResolveOrganization(ctx context.Context, body ResolveOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResolveOrganizationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateHumanProfileWithBody(ctx context.Context, subjectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateHumanProfileRequestWithBody(c.Server, subjectId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateHumanProfile(ctx context.Context, subjectId string, body UpdateHumanProfileJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateHumanProfileRequest(c.Server, subjectId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewResolveOrganizationRequest calls the generic ResolveOrganization builder with application/json body
func NewResolveOrganizationRequest(server string, body ResolveOrganizationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewResolveOrganizationRequestWithBody(server, "application/json", bodyReader)
}

// NewResolveOrganizationRequestWithBody generates requests for ResolveOrganization with any type of body
func NewResolveOrganizationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/organizations/resolve")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpdateHumanProfileRequest calls the generic UpdateHumanProfile builder with application/json body
func NewUpdateHumanProfileRequest(server string, subjectId string, body UpdateHumanProfileJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateHumanProfileRequestWithBody(server, subjectId, "application/json", bodyReader)
}

// NewUpdateHumanProfileRequestWithBody generates requests for UpdateHumanProfile with any type of body
func NewUpdateHumanProfileRequestWithBody(server string, subjectId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "subject_id", subjectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/subjects/%s/human-profile", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ResolveOrganizationWithBodyWithResponse request with any body
	ResolveOrganizationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ResolveOrganizationHTTPResponse, error)

	ResolveOrganizationWithResponse(ctx context.Context, body ResolveOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*ResolveOrganizationHTTPResponse, error)

	// UpdateHumanProfileWithBodyWithResponse request with any body
	UpdateHumanProfileWithBodyWithResponse(ctx context.Context, subjectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateHumanProfileHTTPResponse, error)

	UpdateHumanProfileWithResponse(ctx context.Context, subjectId string, body UpdateHumanProfileJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateHumanProfileHTTPResponse, error)
}

type ResolveOrganizationHTTPResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *IdentityResolveOrganizationResponse
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r ResolveOrganizationHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResolveOrganizationHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateHumanProfileHTTPResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *IdentityUpdateHumanProfileResponse
	ApplicationproblemJSONDefault *ErrorModel
}

// Status returns HTTPResponse.Status
func (r UpdateHumanProfileHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateHumanProfileHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ResolveOrganizationWithBodyWithResponse request with arbitrary body returning *ResolveOrganizationHTTPResponse
func (c *ClientWithResponses) ResolveOrganizationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ResolveOrganizationHTTPResponse, error) {
	rsp, err := c.ResolveOrganizationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResolveOrganizationHTTPResponse(rsp)
}

func (c *ClientWithResponses) ResolveOrganizationWithResponse(ctx context.Context, body ResolveOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*ResolveOrganizationHTTPResponse, error) {
	rsp, err := c.ResolveOrganization(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResolveOrganizationHTTPResponse(rsp)
}

// UpdateHumanProfileWithBodyWithResponse request with arbitrary body returning *UpdateHumanProfileHTTPResponse
func (c *ClientWithResponses) UpdateHumanProfileWithBodyWithResponse(ctx context.Context, subjectId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateHumanProfileHTTPResponse, error) {
	rsp, err := c.UpdateHumanProfileWithBody(ctx, subjectId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateHumanProfileHTTPResponse(rsp)
}

func (c *ClientWithResponses) UpdateHumanProfileWithResponse(ctx context.Context, subjectId string, body UpdateHumanProfileJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateHumanProfileHTTPResponse, error) {
	rsp, err := c.UpdateHumanProfile(ctx, subjectId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateHumanProfileHTTPResponse(rsp)
}

// ParseResolveOrganizationHTTPResponse parses an HTTP response from a ResolveOrganizationWithResponse call
func ParseResolveOrganizationHTTPResponse(rsp *http.Response) (*ResolveOrganizationHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResolveOrganizationHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest IdentityResolveOrganizationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateHumanProfileHTTPResponse parses an HTTP response from a UpdateHumanProfileWithResponse call
func ParseUpdateHumanProfileHTTPResponse(rsp *http.Response) (*UpdateHumanProfileHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateHumanProfileHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest IdentityUpdateHumanProfileResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
