haproxy_public_routes:
  - host: '{{ "analytics.api." ~ verself_domain }}'
    backend: be_route_product_analytics_api_analytics_service_otlp_http
haproxy_public_apis:
  - key: analytics
    host: '{{ "analytics.api." ~ verself_domain }}'
    path_prefix: /v1/logs
