// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: export.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeExportJob = `-- name: CompleteExportJob :exec
UPDATE governance_export_jobs
SET state = 'completed',
    artifact_path = $1,
    artifact_sha256 = $2,
    artifact_bytes = $3,
    manifest = $4,
    updated_at = now(),
    completed_at = now()
WHERE export_id = $5
`

type CompleteExportJobParams struct {
	ArtifactPath   string
	ArtifactSha256 string
	ArtifactBytes  int64
	Manifest       []byte
	ExportID       uuid.UUID
}

func (q *Queries) CompleteExportJob(ctx context.Context, arg CompleteExportJobParams) error {
	_, err := q.db.Exec(ctx, completeExportJob,
		arg.ArtifactPath,
		arg.ArtifactSha256,
		arg.ArtifactBytes,
		arg.Manifest,
		arg.ExportID,
	)
	return err
}

const deleteExportFiles = `-- name: DeleteExportFiles :exec
DELETE FROM governance_export_files
WHERE export_id = $1
`

type DeleteExportFilesParams struct {
	ExportID uuid.UUID
}

func (q *Queries) DeleteExportFiles(ctx context.Context, arg DeleteExportFilesParams) error {
	_, err := q.db.Exec(ctx, deleteExportFiles, arg.ExportID)
	return err
}

const getExportByIDAndOrg = `-- name: GetExportByIDAndOrg :one
SELECT export_id, org_id, requested_by, scopes, include_logs, format, state,
       artifact_path, artifact_sha256, artifact_bytes, manifest, error_code, error_message,
       created_at, updated_at, completed_at, expires_at
FROM governance_export_jobs
WHERE export_id = $1
  AND org_id = $2
`

type GetExportByIDAndOrgParams struct {
	ExportID uuid.UUID
	OrgID    string
}

type GetExportByIDAndOrgRow struct {
	ExportID       uuid.UUID
	OrgID          string
	RequestedBy    string
	Scopes         []string
	IncludeLogs    bool
	Format         string
	State          string
	ArtifactPath   string
	ArtifactSha256 string
	ArtifactBytes  int64
	Manifest       []byte
	ErrorCode      string
	ErrorMessage   string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) GetExportByIDAndOrg(ctx context.Context, arg GetExportByIDAndOrgParams) (GetExportByIDAndOrgRow, error) {
	row := q.db.QueryRow(ctx, getExportByIDAndOrg, arg.ExportID, arg.OrgID)
	var i GetExportByIDAndOrgRow
	err := row.Scan(
		&i.ExportID,
		&i.OrgID,
		&i.RequestedBy,
		&i.Scopes,
		&i.IncludeLogs,
		&i.Format,
		&i.State,
		&i.ArtifactPath,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
		&i.Manifest,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getExportByIdempotency = `-- name: GetExportByIdempotency :one
SELECT export_id, org_id, requested_by, scopes, include_logs, format, state,
       artifact_path, artifact_sha256, artifact_bytes, manifest, error_code, error_message,
       created_at, updated_at, completed_at, expires_at
FROM governance_export_jobs
WHERE org_id = $1
  AND idempotency_key_hash = $2
`

type GetExportByIdempotencyParams struct {
	OrgID              string
	IdempotencyKeyHash string
}

type GetExportByIdempotencyRow struct {
	ExportID       uuid.UUID
	OrgID          string
	RequestedBy    string
	Scopes         []string
	IncludeLogs    bool
	Format         string
	State          string
	ArtifactPath   string
	ArtifactSha256 string
	ArtifactBytes  int64
	Manifest       []byte
	ErrorCode      string
	ErrorMessage   string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) GetExportByIdempotency(ctx context.Context, arg GetExportByIdempotencyParams) (GetExportByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getExportByIdempotency, arg.OrgID, arg.IdempotencyKeyHash)
	var i GetExportByIdempotencyRow
	err := row.Scan(
		&i.ExportID,
		&i.OrgID,
		&i.RequestedBy,
		&i.Scopes,
		&i.IncludeLogs,
		&i.Format,
		&i.State,
		&i.ArtifactPath,
		&i.ArtifactSha256,
		&i.ArtifactBytes,
		&i.Manifest,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertExportFile = `-- name: InsertExportFile :exec
INSERT INTO governance_export_files (export_id, path, content_type, row_count, bytes, sha256)
VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type InsertExportFileParams struct {
	ExportID    uuid.UUID
	Path        string
	ContentType string
	RowCount    int64
	Bytes       int64
	Sha256      string
}

func (q *Queries) InsertExportFile(ctx context.Context, arg InsertExportFileParams) error {
	_, err := q.db.Exec(ctx, insertExportFile,
		arg.ExportID,
		arg.Path,
		arg.ContentType,
		arg.RowCount,
		arg.Bytes,
		arg.Sha256,
	)
	return err
}

const insertExportJob = `-- name: InsertExportJob :exec
INSERT INTO governance_export_jobs (
    export_id, org_id, requested_by, idempotency_key_hash, scopes, include_logs,
    format, state, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    'tar.gz', 'running', $7
)
`

type InsertExportJobParams struct {
	ExportID           uuid.UUID
	OrgID              string
	RequestedBy        string
	IdempotencyKeyHash string
	Scopes             []string
	IncludeLogs        bool
	ExpiresAt          pgtype.Timestamptz
}

func (q *Queries) InsertExportJob(ctx context.Context, arg InsertExportJobParams) error {
	_, err := q.db.Exec(ctx, insertExportJob,
		arg.ExportID,
		arg.OrgID,
		arg.RequestedBy,
		arg.IdempotencyKeyHash,
		arg.Scopes,
		arg.IncludeLogs,
		arg.ExpiresAt,
	)
	return err
}

const listExportFiles = `-- name: ListExportFiles :many
SELECT path, content_type, row_count, bytes, sha256
FROM governance_export_files
WHERE export_id = $1
ORDER BY path
`

type ListExportFilesParams struct {
	ExportID uuid.UUID
}

type ListExportFilesRow struct {
	Path        string
	ContentType string
	RowCount    int64
	Bytes       int64
	Sha256      string
}

func (q *Queries) ListExportFiles(ctx context.Context, arg ListExportFilesParams) ([]ListExportFilesRow, error) {
	rows, err := q.db.Query(ctx, listExportFiles, arg.ExportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExportFilesRow{}
	for rows.Next() {
		var i ListExportFilesRow
		if err := rows.Scan(
			&i.Path,
			&i.ContentType,
			&i.RowCount,
			&i.Bytes,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExportsForOrg = `-- name: ListExportsForOrg :many
SELECT export_id, org_id, requested_by, scopes, include_logs, format, state,
       artifact_path, artifact_sha256, artifact_bytes, manifest, error_code, error_message,
       created_at, updated_at, completed_at, expires_at
FROM governance_export_jobs
WHERE org_id = $1
ORDER BY created_at DESC, export_id DESC
LIMIT 25
`

type ListExportsForOrgParams struct {
	OrgID string
}

type ListExportsForOrgRow struct {
	ExportID       uuid.UUID
	OrgID          string
	RequestedBy    string
	Scopes         []string
	IncludeLogs    bool
	Format         string
	State          string
	ArtifactPath   string
	ArtifactSha256 string
	ArtifactBytes  int64
	Manifest       []byte
	ErrorCode      string
	ErrorMessage   string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) ListExportsForOrg(ctx context.Context, arg ListExportsForOrgParams) ([]ListExportsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listExportsForOrg, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExportsForOrgRow{}
	for rows.Next() {
		var i ListExportsForOrgRow
		if err := rows.Scan(
			&i.ExportID,
			&i.OrgID,
			&i.RequestedBy,
			&i.Scopes,
			&i.IncludeLogs,
			&i.Format,
			&i.State,
			&i.ArtifactPath,
			&i.ArtifactSha256,
			&i.ArtifactBytes,
			&i.Manifest,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExportDownloaded = `-- name: MarkExportDownloaded :exec
UPDATE governance_export_jobs
SET downloaded_at = now(), updated_at = now()
WHERE export_id = $1
  AND org_id = $2
`

type MarkExportDownloadedParams struct {
	ExportID uuid.UUID
	OrgID    string
}

func (q *Queries) MarkExportDownloaded(ctx context.Context, arg MarkExportDownloadedParams) error {
	_, err := q.db.Exec(ctx, markExportDownloaded, arg.ExportID, arg.OrgID)
	return err
}

const markExportFailed = `-- name: MarkExportFailed :exec
UPDATE governance_export_jobs
SET state = 'failed',
    error_code = 'export-build-failed',
    error_message = $1,
    updated_at = now()
WHERE export_id = $2
`

type MarkExportFailedParams struct {
	ErrorMessage string
	ExportID     uuid.UUID
}

func (q *Queries) MarkExportFailed(ctx context.Context, arg MarkExportFailedParams) error {
	_, err := q.db.Exec(ctx, markExportFailed, arg.ErrorMessage, arg.ExportID)
	return err
}
