//! Golden test vector generator for the homestead-smelter binary protocol.
//!
//! Encodes canonical frame instances using the Zig reference encoder and
//! outputs JSON with hex-encoded wire bytes and expected field values.
//! Other language implementations (TypeScript, Go) validate their decoders
//! against the same checked-in file.
//!
//! Regenerate:
//!   cd homestead-smelter && zig build run-generate-vectors > protocol/vectors.json
//!
//! The staleness test (`zig build test`) asserts that the checked-in
//! vectors.json matches the output of this generator.

const std = @import("std");
const hs = @import("homestead_smelter");
const hostp = @import("host_proto.zig");
const hostc = @import("host_core.zig");

const Writer = std.Io.Writer;

// ---------------------------------------------------------------------------
// Canonical test values
// ---------------------------------------------------------------------------

const hello_boot_id_str = "5691d566-f1a6-4342-8604-205e83785b21";
const job_id_str = "4ea0c4ce-4ca7-4389-9c89-612578239c8d";

fn canonicalHello() hs.HelloFrame {
    return .{
        .seq = 0,
        .flags = 0,
        .mono_ns = 1_000_000_000,
        .wall_ns = 1_700_000_000_000_000_000,
        .boot_id = hs.parseUuid(hello_boot_id_str) catch unreachable,
        .mem_total_kb = 516_096,
    };
}

fn canonicalSample() hs.SampleFrame {
    return .{
        .seq = 42,
        .flags = 0,
        .mono_ns = 1_700_000_000,
        .wall_ns = 1_700_000_000_700_000_000,
        .cpu_user_ticks = 123_456,
        .cpu_system_ticks = 78_901,
        .cpu_idle_ticks = 9_876_543,
        .load1_centis = 150,
        .load5_centis = 120,
        .load15_centis = 80,
        .procs_running = 3,
        .procs_blocked = 0,
        .mem_available_kb = 401_232,
        .io_read_bytes = 1_048_576,
        .io_write_bytes = 524_288,
        .net_rx_bytes = 2_097_152,
        .net_tx_bytes = 1_048_576,
        .psi_cpu_pct100 = 250,
        .psi_mem_pct100 = 100,
        .psi_io_pct100 = 50,
    };
}

fn canonicalSampleMax() hs.SampleFrame {
    return .{
        .seq = std.math.maxInt(u32),
        .flags = std.math.maxInt(u32),
        .mono_ns = std.math.maxInt(u64),
        .wall_ns = std.math.maxInt(u64),
        .cpu_user_ticks = std.math.maxInt(u64),
        .cpu_system_ticks = std.math.maxInt(u64),
        .cpu_idle_ticks = std.math.maxInt(u64),
        .load1_centis = std.math.maxInt(u32),
        .load5_centis = std.math.maxInt(u32),
        .load15_centis = std.math.maxInt(u32),
        .procs_running = std.math.maxInt(u16),
        .procs_blocked = std.math.maxInt(u16),
        .mem_available_kb = std.math.maxInt(u64),
        .io_read_bytes = std.math.maxInt(u64),
        .io_write_bytes = std.math.maxInt(u64),
        .net_rx_bytes = std.math.maxInt(u64),
        .net_tx_bytes = std.math.maxInt(u64),
        .psi_cpu_pct100 = std.math.maxInt(u16),
        .psi_mem_pct100 = std.math.maxInt(u16),
        .psi_io_pct100 = std.math.maxInt(u16),
    };
}

// ---------------------------------------------------------------------------
// JSON generation
// ---------------------------------------------------------------------------

pub fn writeVectors(w: *Writer) !void {
    const hello = canonicalHello();
    const hello_bytes = hs.encodeHelloFrame(hello);

    const sample = canonicalSample();
    const sample_bytes = hs.encodeSampleFrame(sample);

    const sample_max = canonicalSampleMax();
    const sample_max_bytes = hs.encodeSampleFrame(sample_max);

    const request_bytes = hostp.encodeRequest(.{ .kind = .attach });

    const job_id = hs.parseUuid(job_id_str) catch unreachable;

    const packet_hello = hostp.Packet{
        .header = .{
            .kind = .hello,
            .host_seq = 7,
            .observed_wall_ns = 1_700_000_000_100_000_000,
            .job_id = job_id,
            .stream_generation = 3,
            .flags = hostp.packet_flag_snapshot,
        },
        .payload = hello_bytes,
    };
    const packet_hello_bytes = hostp.encodePacket(packet_hello);

    const packet_disconnect = hostp.Packet{
        .header = .{
            .kind = .disconnect,
            .host_seq = 42,
            .observed_wall_ns = 1_700_000_000_200_000_000,
            .job_id = job_id,
            .stream_generation = 3,
            .flags = 0,
        },
        .payload = hostp.encodeDisconnectPayload(.decode_failed),
    };
    const packet_disconnect_bytes = hostp.encodePacket(packet_disconnect);

    // -- file header --

    try w.writeAll(
        \\{
        \\  "schema_version": 1,
        \\  "note": "Generated by: zig build run-generate-vectors. Do not edit.",
        \\  "protocol": {
        \\    "guest_frame_size": 128,
        \\    "host_request_size": 32,
        \\    "host_packet_size": 176,
        \\    "host_payload_offset": 48,
        \\    "byte_order": "little-endian"
        \\  },
        \\  "u64_encoding": "decimal-string",
        \\  "vectors": {
        \\
    );

    // -- guest_hello --

    try w.writeAll("    \"guest_hello\": {\n");
    try w.writeAll("      \"layer\": \"guest\",\n");
    try w.writeAll("      \"type\": \"hello\",\n");
    try w.writeAll("      \"hex\": \"");
    try writeHex(w, &hello_bytes);
    try w.writeAll("\",\n");
    try w.writeAll("      \"fields\": {\n");
    try w.print("        \"seq\": {d},\n", .{hello.seq});
    try w.print("        \"flags\": {d},\n", .{hello.flags});
    try w.print("        \"mono_ns\": \"{d}\",\n", .{hello.mono_ns});
    try w.print("        \"wall_ns\": \"{d}\",\n", .{hello.wall_ns});
    try w.print("        \"boot_id\": \"{s}\",\n", .{hello_boot_id_str});
    try w.print("        \"mem_total_kb\": \"{d}\"\n", .{hello.mem_total_kb});
    try w.writeAll("      }\n");
    try w.writeAll("    },\n");

    // -- guest_sample --

    try w.writeAll("    \"guest_sample\": {\n");
    try w.writeAll("      \"layer\": \"guest\",\n");
    try w.writeAll("      \"type\": \"sample\",\n");
    try w.writeAll("      \"hex\": \"");
    try writeHex(w, &sample_bytes);
    try w.writeAll("\",\n");
    try w.writeAll("      \"fields\": {\n");
    try w.print("        \"seq\": {d},\n", .{sample.seq});
    try w.print("        \"flags\": {d},\n", .{sample.flags});
    try w.print("        \"mono_ns\": \"{d}\",\n", .{sample.mono_ns});
    try w.print("        \"wall_ns\": \"{d}\",\n", .{sample.wall_ns});
    try w.print("        \"cpu_user_ticks\": \"{d}\",\n", .{sample.cpu_user_ticks});
    try w.print("        \"cpu_system_ticks\": \"{d}\",\n", .{sample.cpu_system_ticks});
    try w.print("        \"cpu_idle_ticks\": \"{d}\",\n", .{sample.cpu_idle_ticks});
    try w.print("        \"load1_centis\": {d},\n", .{sample.load1_centis});
    try w.print("        \"load5_centis\": {d},\n", .{sample.load5_centis});
    try w.print("        \"load15_centis\": {d},\n", .{sample.load15_centis});
    try w.print("        \"procs_running\": {d},\n", .{sample.procs_running});
    try w.print("        \"procs_blocked\": {d},\n", .{sample.procs_blocked});
    try w.print("        \"mem_available_kb\": \"{d}\",\n", .{sample.mem_available_kb});
    try w.print("        \"io_read_bytes\": \"{d}\",\n", .{sample.io_read_bytes});
    try w.print("        \"io_write_bytes\": \"{d}\",\n", .{sample.io_write_bytes});
    try w.print("        \"net_rx_bytes\": \"{d}\",\n", .{sample.net_rx_bytes});
    try w.print("        \"net_tx_bytes\": \"{d}\",\n", .{sample.net_tx_bytes});
    try w.print("        \"psi_cpu_pct100\": {d},\n", .{sample.psi_cpu_pct100});
    try w.print("        \"psi_mem_pct100\": {d},\n", .{sample.psi_mem_pct100});
    try w.print("        \"psi_io_pct100\": {d}\n", .{sample.psi_io_pct100});
    try w.writeAll("      }\n");
    try w.writeAll("    },\n");

    // -- guest_sample_max --

    try w.writeAll("    \"guest_sample_max\": {\n");
    try w.writeAll("      \"layer\": \"guest\",\n");
    try w.writeAll("      \"type\": \"sample\",\n");
    try w.writeAll("      \"note\": \"All fields at maximum value. Tests u64/u32/u16 boundary handling.\",\n");
    try w.writeAll("      \"hex\": \"");
    try writeHex(w, &sample_max_bytes);
    try w.writeAll("\",\n");
    try w.writeAll("      \"fields\": {\n");
    try w.print("        \"seq\": {d},\n", .{sample_max.seq});
    try w.print("        \"flags\": {d},\n", .{sample_max.flags});
    try w.print("        \"mono_ns\": \"{d}\",\n", .{sample_max.mono_ns});
    try w.print("        \"wall_ns\": \"{d}\",\n", .{sample_max.wall_ns});
    try w.print("        \"cpu_user_ticks\": \"{d}\",\n", .{sample_max.cpu_user_ticks});
    try w.print("        \"cpu_system_ticks\": \"{d}\",\n", .{sample_max.cpu_system_ticks});
    try w.print("        \"cpu_idle_ticks\": \"{d}\",\n", .{sample_max.cpu_idle_ticks});
    try w.print("        \"load1_centis\": {d},\n", .{sample_max.load1_centis});
    try w.print("        \"load5_centis\": {d},\n", .{sample_max.load5_centis});
    try w.print("        \"load15_centis\": {d},\n", .{sample_max.load15_centis});
    try w.print("        \"procs_running\": {d},\n", .{sample_max.procs_running});
    try w.print("        \"procs_blocked\": {d},\n", .{sample_max.procs_blocked});
    try w.print("        \"mem_available_kb\": \"{d}\",\n", .{sample_max.mem_available_kb});
    try w.print("        \"io_read_bytes\": \"{d}\",\n", .{sample_max.io_read_bytes});
    try w.print("        \"io_write_bytes\": \"{d}\",\n", .{sample_max.io_write_bytes});
    try w.print("        \"net_rx_bytes\": \"{d}\",\n", .{sample_max.net_rx_bytes});
    try w.print("        \"net_tx_bytes\": \"{d}\",\n", .{sample_max.net_tx_bytes});
    try w.print("        \"psi_cpu_pct100\": {d},\n", .{sample_max.psi_cpu_pct100});
    try w.print("        \"psi_mem_pct100\": {d},\n", .{sample_max.psi_mem_pct100});
    try w.print("        \"psi_io_pct100\": {d}\n", .{sample_max.psi_io_pct100});
    try w.writeAll("      }\n");
    try w.writeAll("    },\n");

    // -- host_request_attach --

    try w.writeAll("    \"host_request_attach\": {\n");
    try w.writeAll("      \"layer\": \"host\",\n");
    try w.writeAll("      \"type\": \"request\",\n");
    try w.writeAll("      \"hex\": \"");
    try writeHex(w, &request_bytes);
    try w.writeAll("\",\n");
    try w.writeAll("      \"fields\": {\n");
    try w.writeAll("        \"kind\": 1\n");
    try w.writeAll("      }\n");
    try w.writeAll("    },\n");

    // -- host_packet_hello --

    try w.writeAll("    \"host_packet_hello\": {\n");
    try w.writeAll("      \"layer\": \"host\",\n");
    try w.writeAll("      \"type\": \"packet\",\n");
    try w.writeAll("      \"hex\": \"");
    try writeHex(w, &packet_hello_bytes);
    try w.writeAll("\",\n");
    try w.writeAll("      \"fields\": {\n");
    try w.print("        \"kind\": {d},\n", .{@intFromEnum(packet_hello.header.kind)});
    try w.print("        \"host_seq\": \"{d}\",\n", .{packet_hello.header.host_seq});
    try w.print("        \"observed_wall_ns\": \"{d}\",\n", .{packet_hello.header.observed_wall_ns});
    try w.print("        \"job_id\": \"{s}\",\n", .{job_id_str});
    try w.print("        \"stream_generation\": {d},\n", .{packet_hello.header.stream_generation});
    try w.print("        \"flags\": {d}\n", .{packet_hello.header.flags});
    try w.writeAll("      },\n");
    try w.writeAll("      \"payload_type\": \"guest_hello\",\n");
    try w.writeAll("      \"payload_fields\": {\n");
    try w.print("        \"seq\": {d},\n", .{hello.seq});
    try w.print("        \"flags\": {d},\n", .{hello.flags});
    try w.print("        \"mono_ns\": \"{d}\",\n", .{hello.mono_ns});
    try w.print("        \"wall_ns\": \"{d}\",\n", .{hello.wall_ns});
    try w.print("        \"boot_id\": \"{s}\",\n", .{hello_boot_id_str});
    try w.print("        \"mem_total_kb\": \"{d}\"\n", .{hello.mem_total_kb});
    try w.writeAll("      }\n");
    try w.writeAll("    },\n");

    // -- host_packet_disconnect --

    try w.writeAll("    \"host_packet_disconnect\": {\n");
    try w.writeAll("      \"layer\": \"host\",\n");
    try w.writeAll("      \"type\": \"packet\",\n");
    try w.writeAll("      \"hex\": \"");
    try writeHex(w, &packet_disconnect_bytes);
    try w.writeAll("\",\n");
    try w.writeAll("      \"fields\": {\n");
    try w.print("        \"kind\": {d},\n", .{@intFromEnum(packet_disconnect.header.kind)});
    try w.print("        \"host_seq\": \"{d}\",\n", .{packet_disconnect.header.host_seq});
    try w.print("        \"observed_wall_ns\": \"{d}\",\n", .{packet_disconnect.header.observed_wall_ns});
    try w.print("        \"job_id\": \"{s}\",\n", .{job_id_str});
    try w.print("        \"stream_generation\": {d},\n", .{packet_disconnect.header.stream_generation});
    try w.print("        \"flags\": {d}\n", .{packet_disconnect.header.flags});
    try w.writeAll("      },\n");
    try w.writeAll("      \"payload_type\": \"disconnect\",\n");
    try w.writeAll("      \"payload_fields\": {\n");
    try w.writeAll("        \"reason\": 2\n");
    try w.writeAll("      }\n");
    try w.writeAll("    }\n");

    // -- close --

    try w.writeAll("  }\n");
    try w.writeAll("}\n");
}

fn writeHex(w: *Writer, bytes: []const u8) !void {
    const hex_chars = "0123456789abcdef";
    for (bytes) |byte| {
        try w.writeByte(hex_chars[byte >> 4]);
        try w.writeByte(hex_chars[byte & 0xf]);
    }
}

// ---------------------------------------------------------------------------
// Entry point (zig build run-generate-vectors)
// ---------------------------------------------------------------------------

pub fn main() !void {
    var buf: [16384]u8 = undefined;
    var fw = std.fs.File.stdout().writer(&buf);
    try writeVectors(&fw.interface);
    try fw.interface.flush();
}

// ---------------------------------------------------------------------------
// Staleness test (zig build test)
// ---------------------------------------------------------------------------

test "vectors.json matches canonical encoder output" {
    const file = try std.fs.cwd().openFile("protocol/vectors.json", .{});
    defer file.close();
    const checked_in = try file.readToEndAlloc(std.testing.allocator, 64 * 1024);
    defer std.testing.allocator.free(checked_in);

    var buf: [32768]u8 = undefined;
    var w = Writer.fixed(&buf);
    try writeVectors(&w);
    try std.testing.expectEqualStrings(checked_in, w.buffered());
}
