# gazelle:prefix github.com/verself/governance-service

load("//src/tools/deployment/nomad:component.bzl", "nomad_component")

exports_files(
    [
        "nftables/governance-service.nft",
    ],
    visibility = ["//src/configuration:__pkg__"],
)

nomad_component(
    name = "nomad_component",
    artifacts = {
        "//src/services/governance-service/cmd/governance-service:governance-service_nomad_artifact": "governance-service",
    },
    component = "governance_service",
    job_id = "governance-service",
    job_spec = "nomad.hcl",
    requires = [
        "clickhouse:migrations",
        "postgres:server",
    ],
    visibility = ["//src/tools/deployment/nomad:__pkg__"],
)
