load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "clickhouse-host-apply_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/infrastructure-components/clickhouse/cmd/clickhouse-host-apply",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "clickhouse-host-apply",
    embed = [":clickhouse-host-apply_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "clickhouse-host-apply_test",
    srcs = ["main_test.go"],
    embed = [":clickhouse-host-apply_lib"],
)
