[workers]
vs-dev-w0 ansible_host=access.verself.sh verself_recovery_ssh_host=10.66.66.1 verself_recovery_ssh_port=2222 verself_recovery_ssh_user=ubuntu

[infra]
vs-dev-w0 ansible_host=access.verself.sh verself_recovery_ssh_host=10.66.66.1 verself_recovery_ssh_port=2222 verself_recovery_ssh_user=ubuntu

[all:vars]
ansible_user=ubuntu@prod
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args=-o IdentitiesOnly=yes
