[workers]
vs-dev-w0 verself_ssh_host=access.verself.sh verself_recovery_ssh_host=10.66.66.1 verself_recovery_ssh_port=2222 verself_recovery_ssh_user=ubuntu

[infra]
vs-dev-w0 verself_ssh_host=access.verself.sh verself_recovery_ssh_host=10.66.66.1 verself_recovery_ssh_port=2222 verself_recovery_ssh_user=ubuntu

[all:vars]
verself_ssh_user=ubuntu@prod
