---
base_bootstrap_artifact_root: /var/lib/verself/bootstrap-artifacts
base_bootstrap_artifact_server_listen: 127.0.0.1:7380

base_nomad_runtime_users:
  - name: company
    home: /var/lib/company
  - name: spicedb
    home: /var/lib/spicedb
  - name: stalwart
    home: /var/lib/stalwart
  - name: verself-web
    home: /var/lib/verself-web
