load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "humaapi",
    srcs = ["humaapi.go"],
    importpath = "github.com/verself/service-runtime/humaapi",
    visibility = ["//visibility:public"],
    deps = ["@com_github_danielgtaylor_huma_v2//:huma"],
)

alias(
    name = "go_default_library",
    actual = ":humaapi",
    visibility = ["//visibility:public"],
)
