load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "deployment-recovery-deploy_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/deployment-tools/cmd/deployment-recovery-deploy",
    visibility = ["//visibility:private"],
    deps = [
        "//src/services/deployment-service/deployengine",
        "//src/services/deployment-service/deployengine/artifactpublish",
        "//src/services/object-storage-service/client",
        "//src/services/service-runtime/go/envconfig",
        "//src/services/service-runtime/go/workload",
    ],
)

go_binary(
    name = "deployment-recovery-deploy",
    embed = [":deployment-recovery-deploy_lib"],
    visibility = ["//visibility:public"],
)
