// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vErrorDetail = v.strictObject({
    location: v.optional(v.string()),
    message: v.optional(v.string()),
    value: v.optional(v.unknown())
});

export const vErrorModel = v.strictObject({
    $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
    detail: v.optional(v.string()),
    errors: v.nullish(v.array(vErrorDetail)),
    instance: v.optional(v.pipe(v.string(), v.url())),
    status: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    title: v.optional(v.string()),
    type: v.optional(v.pipe(v.string(), v.url()), 'about:blank')
});

export const vMailAccountOutputBody = v.strictObject({
    $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
    account_id: v.string(),
    default_mailbox_id: v.optional(v.string()),
    display_name: v.string(),
    email_address: v.string()
});

export const vMailBodyOutputBody = v.strictObject({
    $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
    account_id: v.string(),
    email_id: v.string(),
    fetched_at: v.string(),
    html_body: v.string(),
    text_body: v.string()
});

export const vMailMoveInputBody = v.strictObject({
    $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
    mailbox_id: v.string()
});

export const vMailMutationOutputBody = v.strictObject({
    $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
    email_id: v.string(),
    status: v.string()
});

export const vMailSyncStatusOutputBody = v.strictObject({
    $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
    status: v.unknown()
});

export const vOperatorAccount = v.strictObject({
    account_id: v.string(),
    display_name: v.string(),
    email_address: v.string(),
    jmap_account_id: v.string(),
    principal_type: v.string(),
    synced_at: v.string()
});

export const vOperatorAccountsOutputBody = v.strictObject({
    $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
    accounts: v.nullable(v.array(vOperatorAccount))
});

export const vOperatorAddress = v.strictObject({
    email: v.string(),
    name: v.string()
});

export const vOperatorEmail = v.strictObject({
    account_id: v.string(),
    cc: v.nullable(v.array(vOperatorAddress)),
    email_id: v.string(),
    from_email: v.string(),
    from_name: v.string(),
    has_attachment: v.boolean(),
    is_answered: v.boolean(),
    is_draft: v.boolean(),
    is_flagged: v.boolean(),
    is_seen: v.boolean(),
    keywords: v.record(v.string(), v.boolean()),
    mailbox_ids: v.nullable(v.array(v.string())),
    preview: v.string(),
    received_at: v.string(),
    reply_to: v.nullable(v.array(vOperatorAddress)),
    sent_at: v.string(),
    size: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    subject: v.string(),
    synced_at: v.string(),
    thread_id: v.string(),
    to: v.nullable(v.array(vOperatorAddress))
});

export const vOperatorEmailDetail = v.strictObject({
    $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
    account_id: v.string(),
    cc: v.nullable(v.array(vOperatorAddress)),
    email_id: v.string(),
    fetched_at: v.string(),
    from_email: v.string(),
    from_name: v.string(),
    has_attachment: v.boolean(),
    html_body: v.string(),
    is_answered: v.boolean(),
    is_draft: v.boolean(),
    is_flagged: v.boolean(),
    is_seen: v.boolean(),
    keywords: v.record(v.string(), v.boolean()),
    mailbox_ids: v.nullable(v.array(v.string())),
    preview: v.string(),
    received_at: v.string(),
    reply_to: v.nullable(v.array(vOperatorAddress)),
    sent_at: v.string(),
    size: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    subject: v.string(),
    synced_at: v.string(),
    text_body: v.string(),
    thread_id: v.string(),
    to: v.nullable(v.array(vOperatorAddress))
});

export const vOperatorEmailsOutputBody = v.strictObject({
    $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
    emails: v.nullable(v.array(vOperatorEmail))
});

export const vOperatorMailbox = v.strictObject({
    account_id: v.string(),
    id: v.string(),
    name: v.string(),
    parent_id: v.string(),
    role: v.string(),
    sort_order: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    synced_at: v.string(),
    total_emails: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    total_threads: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    unread_emails: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    unread_threads: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

export const vOperatorMailboxesOutputBody = v.strictObject({
    $schema: v.optional(v.pipe(v.pipe(v.string(), v.url()), v.readonly())),
    mailboxes: v.nullable(v.array(vOperatorMailbox))
});

export const vErrorModelWritable = v.strictObject({
    detail: v.optional(v.string()),
    errors: v.nullish(v.array(vErrorDetail)),
    instance: v.optional(v.pipe(v.string(), v.url())),
    status: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    title: v.optional(v.string()),
    type: v.optional(v.pipe(v.string(), v.url()), 'about:blank')
});

export const vMailAccountOutputBodyWritable = v.strictObject({
    account_id: v.string(),
    default_mailbox_id: v.optional(v.string()),
    display_name: v.string(),
    email_address: v.string()
});

export const vMailBodyOutputBodyWritable = v.strictObject({
    account_id: v.string(),
    email_id: v.string(),
    fetched_at: v.string(),
    html_body: v.string(),
    text_body: v.string()
});

export const vMailMoveInputBodyWritable = v.strictObject({
    mailbox_id: v.string()
});

export const vMailMutationOutputBodyWritable = v.strictObject({
    email_id: v.string(),
    status: v.string()
});

export const vMailSyncStatusOutputBodyWritable = v.strictObject({
    status: v.unknown()
});

export const vOperatorAccountsOutputBodyWritable = v.strictObject({
    accounts: v.nullable(v.array(vOperatorAccount))
});

export const vOperatorEmailDetailWritable = v.strictObject({
    account_id: v.string(),
    cc: v.nullable(v.array(vOperatorAddress)),
    email_id: v.string(),
    fetched_at: v.string(),
    from_email: v.string(),
    from_name: v.string(),
    has_attachment: v.boolean(),
    html_body: v.string(),
    is_answered: v.boolean(),
    is_draft: v.boolean(),
    is_flagged: v.boolean(),
    is_seen: v.boolean(),
    keywords: v.record(v.string(), v.boolean()),
    mailbox_ids: v.nullable(v.array(v.string())),
    preview: v.string(),
    received_at: v.string(),
    reply_to: v.nullable(v.array(vOperatorAddress)),
    sent_at: v.string(),
    size: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')),
    subject: v.string(),
    synced_at: v.string(),
    text_body: v.string(),
    thread_id: v.string(),
    to: v.nullable(v.array(vOperatorAddress))
});

export const vOperatorEmailsOutputBodyWritable = v.strictObject({
    emails: v.nullable(v.array(vOperatorEmail))
});

export const vOperatorMailboxesOutputBodyWritable = v.strictObject({
    mailboxes: v.nullable(v.array(vOperatorMailbox))
});

/**
 * OK
 */
export const vMailAccountResponse = vMailAccountOutputBody;

export const vMailBodyPath = v.object({
    email_id: v.string()
});

/**
 * OK
 */
export const vMailBodyResponse = vMailBodyOutputBody;

export const vMailFlagPath = v.object({
    email_id: v.string()
});

/**
 * OK
 */
export const vMailFlagResponse = vMailMutationOutputBody;

export const vMailMoveBody = vMailMoveInputBodyWritable;

export const vMailMovePath = v.object({
    email_id: v.string()
});

/**
 * OK
 */
export const vMailMoveResponse = vMailMutationOutputBody;

export const vMailMarkReadPath = v.object({
    email_id: v.string()
});

/**
 * OK
 */
export const vMailMarkReadResponse = vMailMutationOutputBody;

export const vMailTrashPath = v.object({
    email_id: v.string()
});

/**
 * OK
 */
export const vMailTrashResponse = vMailMutationOutputBody;

export const vMailUnflagPath = v.object({
    email_id: v.string()
});

/**
 * OK
 */
export const vMailUnflagResponse = vMailMutationOutputBody;

export const vMailMarkUnreadPath = v.object({
    email_id: v.string()
});

/**
 * OK
 */
export const vMailMarkUnreadResponse = vMailMutationOutputBody;

/**
 * OK
 */
export const vMailSyncStatusResponse = vMailSyncStatusOutputBody;

/**
 * OK
 */
export const vOperatorListAccountsResponse = vOperatorAccountsOutputBody;

export const vOperatorListEmailsPath = v.object({
    account_id: v.string()
});

export const vOperatorListEmailsQuery = v.object({
    limit: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    mailbox_id: v.optional(v.string())
});

/**
 * OK
 */
export const vOperatorListEmailsResponse = vOperatorEmailsOutputBody;

export const vOperatorGetEmailPath = v.object({
    account_id: v.string(),
    email_id: v.string()
});

/**
 * OK
 */
export const vOperatorGetEmailResponse = vOperatorEmailDetail;

export const vOperatorListMailboxesPath = v.object({
    account_id: v.string()
});

/**
 * OK
 */
export const vOperatorListMailboxesResponse = vOperatorMailboxesOutputBody;
