---
- name: Restart OpenBao
  listen: restart openbao
  ansible.builtin.systemd:
    daemon_reload: true
    name: openbao
    state: restarted

- name: Reload nftables for OpenBao
  listen: reload nftables
  ansible.builtin.systemd:
    name: nftables
    state: reloaded
