---
- name: Restart OTel Collector Nomad tasks
  listen: restart otelcol
  ansible.builtin.command:
    argv:
      - "{{ verself_bin }}/nomad"
      - job
      - restart
      - -yes
      - -all-tasks
      - otelcol
  environment:
    NOMAD_ADDR: "http://{{ nomad_http_address }}"
  changed_when: true
