---
- name: Restart HAProxy
  listen: restart haproxy
  ansible.builtin.systemd:
    daemon_reload: true
    name: haproxy
    state: restarted

- name: Reload HAProxy
  listen: reload haproxy
  ansible.builtin.systemd:
    daemon_reload: true
    name: haproxy
    state: reloaded
