load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "bootstrap-artifact-server_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/deployment-tools/cmd/bootstrap-artifact-server",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "bootstrap-artifact-server",
    embed = [":bootstrap-artifact-server_lib"],
    visibility = ["//visibility:public"],
)
