load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "clickhouse_host_install_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/infrastructure-components/clickhouse/cmd/clickhouse-host-install",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "clickhouse-host-install",
    embed = [":clickhouse_host_install_lib"],
    visibility = ["//visibility:public"],
)
