haproxy_public_routes:
  - host: '{{ deployment_service_domain }}'
    backend: be_route_product_deployments_api_deployment_service_public_api
haproxy_public_apis:
  - key: deployments
    host: '{{ deployment_service_domain }}'
    path_prefix: /api/v1
