---
profile: production
use_default_rules: true
rulesdir:
  - rules/

exclude_paths:
  - .cache/

enable_list:
  - no-default-ports
  - no-masterkey-cli

warn_list:
  - experimental
  - jinja[spacing]
  - fqcn[deep]

offline: true
