# gazelle:prefix github.com/verself/distribution-service

load("//src/tools/build:go_module_checks.bzl", "go_module_checks")
load("//src/tools/deployment:declarations.bzl", "deploy_declarations")
load("//src/tools/deployment/nomad:component.bzl", "nomad_component")
load("//src/tools/deployment/spire:identity.bzl", "spire_identity")

deploy_declarations(visibility = ["//visibility:public"])

go_module_checks()

spire_identity(
    name = "spiffe_identity",
    component = "distribution_service",
    entry_id = "verself-distribution-service",
    key = "distribution_service.default",
    path = "/svc/distribution-service",
    user = "distribution_service",
    visibility = ["//src/infrastructure-components/spire:__pkg__"],
)

nomad_component(
    name = "nomad_component",
    artifacts = {
        "//src/services/distribution-service/cmd/distribution-service:distribution-service_nomad_artifact": "distribution-service",
    },
    component = "distribution_service",
    digest_inputs = [":deploy_declarations"],
    job_id = "distribution-service",
    job_spec = "nomad.hcl",
    visibility = ["//src/tools/deployment/nomad:__pkg__"],
)
