load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "deploy-contract-validate_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/deployment-tools/cmd/deploy-contract-validate",
    visibility = ["//visibility:private"],
    deps = ["//src/services/deployment-service/deploycontract"],
)

go_binary(
    name = "deploy-contract-validate",
    embed = [":deploy-contract-validate_lib"],
    visibility = ["//visibility:public"],
)
