load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "contractapi",
    srcs = ["billing_contract.gen.go"],
    importpath = "github.com/verself/billing-service/internal/contractapi",
    visibility = ["//src/services/billing-service:__subpackages__"],
)

alias(
    name = "go_default_library",
    actual = ":contractapi",
    visibility = ["//src/services/billing-service:__subpackages__"],
)
