load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")
load("//src/tools/deployment/nomad:artifact.bzl", "nomad_binary_artifact")

go_library(
    name = "otelcol-setup_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/infrastructure-components/otelcol/cmd/otelcol-setup",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "otelcol-setup",
    embed = [":lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "otelcol-setup_test",
    srcs = ["main_test.go"],
    embed = [":otelcol-setup_lib"],
)

nomad_binary_artifact(
    name = "otelcol-setup_nomad_artifact",
    binary = ":otelcol-setup",
    output = "otelcol-setup",
)

go_library(
    name = "lib",
    srcs = ["main.go"],
    importpath = "",
    visibility = ["//visibility:private"],
)

go_test(
    name = "lib_test",
    srcs = ["main_test.go"],
    embed = [":lib"],
)
