# gazelle:prefix github.com/verself/analytics-service

load("//src/infrastructure-components/spire:identity.bzl", "spire_identity")
load("//src/services/deployment-service:declarations.bzl", "deploy_declarations")
load("//src/tools/build:go_module_checks.bzl", "go_module_checks")

deploy_declarations(visibility = ["//visibility:public"])

go_module_checks()

spire_identity(
    name = "spiffe_identity",
    component = "analytics_service",
    entry_id = "verself-analytics-service",
    key = "analytics_service.default",
    path = "/svc/analytics-service",
    user = "analytics_service",
    visibility = ["//src/infrastructure-components/spire:__pkg__"],
)
