load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "billing-internal-openapi_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/billing-service/cmd/billing-internal-openapi",
    visibility = ["//visibility:private"],
    deps = ["//src/services/billing-service/internal/billingapi"],
)

go_binary(
    name = "billing-internal-openapi",
    embed = [":billing-internal-openapi_lib"],
    visibility = ["//visibility:public"],
)
