---
letters_subdomain: letters
letters_domain: "{{ letters_subdomain }}.{{ forge_metal_domain }}"
letters_install_dir: /opt/letters
letters_app_dir: "{{ letters_install_dir }}/apps/letters"
letters_dependencies_fingerprint_path: "{{ letters_install_dir }}/.pnpm-install-fingerprint"
