# gazelle:prefix github.com/verself/object-storage-service

load("//src/tools/deployment/nomad:component.bzl", "nomad_component")

exports_files(
    [
        "ansible/bootstrap/object_storage_garage_proxy.yml",
        "ansible/bootstrap/object_storage_tls.yml",
        "nftables/object-storage-admin.nft",
        "nftables/object-storage-service.nft",
    ],
    visibility = ["//src/configuration:__pkg__"],
)

nomad_component(
    name = "nomad_component",
    artifacts = {
        "//src/services/object-storage-service/cmd/object-storage-service:object-storage-service_nomad_artifact": "object-storage-service",
    },
    component = "object_storage_service",
    depends_on = ["governance-service"],
    job_id = "object-storage-service",
    job_spec = "nomad.hcl",
    requires = [
        "clickhouse:migrations",
        "garage:admin",
        "garage:s3",
        "postgres:server",
    ],
    visibility = ["//src/tools/deployment/nomad:__pkg__"],
)
