http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "spire_tool_spire",
    downloaded_file_path = "spire-1.15.0-linux-amd64-musl.tar.gz",
    sha256 = "98345cd14e1e0fac1698669209127f0f870d46f6a1add81fed46a042059994ce",
    url = "https://github.com/spiffe/spire/releases/download/v1.15.0/spire-1.15.0-linux-amd64-musl.tar.gz",
)
