# gazelle:prefix github.com/verself/projects-service

load("//src/tools/deployment/nomad:component.bzl", "nomad_component")

exports_files(
    [
        "nftables/projects-service.nft",
    ],
    visibility = ["//src/configuration:__pkg__"],
)

nomad_component(
    name = "nomad_component",
    artifacts = {
        "//src/services/projects-service/cmd/projects-service:projects-service_nomad_artifact": "projects-service",
    },
    component = "projects_service",
    job_id = "projects-service",
    job_spec = "nomad.hcl",
    requires = ["postgres:server"],
    visibility = ["//src/tools/deployment/nomad:__pkg__"],
)
