load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "mksk-release_lib",
    srcs = [
        "main.go",
        "release_intent.go",
    ],
    importpath = "github.com/verself/make-skill/release/cmd/mksk-release",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "mksk-release",
    embed = [":mksk-release_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "mksk-release_test",
    srcs = ["main_test.go"],
    embed = [":mksk-release_lib"],
)
