http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_file(
    name = "forgejo_tool_sqlite3_deb",
    downloaded_file_path = "sqlite3_3.45.1-1ubuntu2.5_amd64.deb",
    sha256 = "9f4085a3c0c64087b8ee4fb82cf634e02778258c348221492d0fe5cfd7ee9dc7",
    url = "http://archive.ubuntu.com/ubuntu/pool/main/s/sqlite3/sqlite3_3.45.1-1ubuntu2.5_amd64.deb",
)
