// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entitlements.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCreditGrantForEntitlement = `-- name: InsertCreditGrantForEntitlement :execrows
INSERT INTO credit_grants (
    grant_id, org_id, scope_type, scope_product_id, scope_bucket_id, scope_sku_id, amount, source,
    source_reference_id, entitlement_period_id, policy_version, starts_at, period_start, period_end, expires_at,
    account_id, deposit_transfer_id, ledger_posting_state
) VALUES (
    $1,
    $2,
    $3,
    NULLIF($4, ''),
    NULLIF($5, ''),
    NULLIF($6, ''),
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $14,
    $15::bytea,
    $16::bytea,
    'pending'
)
ON CONFLICT (org_id, source, scope_type, scope_product_id, scope_bucket_id, scope_sku_id, source_reference_id) DO NOTHING
`

type InsertCreditGrantForEntitlementParams struct {
	GrantID             string
	OrgID               string
	ScopeType           string
	ScopeProductID      interface{}
	ScopeBucketID       interface{}
	ScopeSkuID          interface{}
	Amount              int64
	Source              string
	SourceReferenceID   string
	EntitlementPeriodID pgtype.Text
	PolicyVersion       string
	StartsAt            pgtype.Timestamptz
	PeriodStart         pgtype.Timestamptz
	PeriodEnd           pgtype.Timestamptz
	AccountID           []byte
	DepositTransferID   []byte
}

func (q *Queries) InsertCreditGrantForEntitlement(ctx context.Context, arg InsertCreditGrantForEntitlementParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCreditGrantForEntitlement,
		arg.GrantID,
		arg.OrgID,
		arg.ScopeType,
		arg.ScopeProductID,
		arg.ScopeBucketID,
		arg.ScopeSkuID,
		arg.Amount,
		arg.Source,
		arg.SourceReferenceID,
		arg.EntitlementPeriodID,
		arg.PolicyVersion,
		arg.StartsAt,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.AccountID,
		arg.DepositTransferID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertEntitlementPeriod = `-- name: InsertEntitlementPeriod :exec
INSERT INTO entitlement_periods (
    period_id, org_id, product_id, cycle_id, source, policy_id, contract_id, phase_id, line_id,
    scope_type, scope_product_id, scope_bucket_id, scope_sku_id, amount_units, period_start, period_end,
    policy_version, payment_state, entitlement_state, calculation_kind, source_reference_id, created_reason
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NULLIF($6, ''),
    NULLIF($7, ''),
    NULLIF($8, ''),
    NULLIF($9, ''),
    $10,
    NULLIF($11, ''),
    NULLIF($12, ''),
    NULLIF($13, ''),
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    'materialized'
)
ON CONFLICT (org_id, source, source_reference_id) DO NOTHING
`

type InsertEntitlementPeriodParams struct {
	PeriodID          string
	OrgID             string
	ProductID         string
	CycleID           pgtype.Text
	Source            string
	PolicyID          interface{}
	ContractID        interface{}
	PhaseID           interface{}
	LineID            interface{}
	ScopeType         string
	ScopeProductID    interface{}
	ScopeBucketID     interface{}
	ScopeSkuID        interface{}
	AmountUnits       int64
	PeriodStart       pgtype.Timestamptz
	PeriodEnd         pgtype.Timestamptz
	PolicyVersion     string
	PaymentState      string
	EntitlementState  string
	CalculationKind   string
	SourceReferenceID string
}

func (q *Queries) InsertEntitlementPeriod(ctx context.Context, arg InsertEntitlementPeriodParams) error {
	_, err := q.db.Exec(ctx, insertEntitlementPeriod,
		arg.PeriodID,
		arg.OrgID,
		arg.ProductID,
		arg.CycleID,
		arg.Source,
		arg.PolicyID,
		arg.ContractID,
		arg.PhaseID,
		arg.LineID,
		arg.ScopeType,
		arg.ScopeProductID,
		arg.ScopeBucketID,
		arg.ScopeSkuID,
		arg.AmountUnits,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.PolicyVersion,
		arg.PaymentState,
		arg.EntitlementState,
		arg.CalculationKind,
		arg.SourceReferenceID,
	)
	return err
}

const insertManualCreditGrant = `-- name: InsertManualCreditGrant :exec
INSERT INTO credit_grants (
    grant_id, org_id, scope_type, scope_product_id, scope_bucket_id, scope_sku_id, amount, source,
    source_reference_id, entitlement_period_id, policy_version, starts_at, expires_at,
    account_id, deposit_transfer_id, ledger_posting_state
)
VALUES (
    $1,
    $2,
    $3,
    NULLIF($4, ''),
    NULLIF($5, ''),
    NULLIF($6, ''),
    $7,
    $8,
    $9,
    NULLIF($10, ''),
    $11,
    $12,
    $13,
    $14::bytea,
    $15::bytea,
    'pending'
)
ON CONFLICT (org_id, source, scope_type, scope_product_id, scope_bucket_id, scope_sku_id, source_reference_id) DO NOTHING
`

type InsertManualCreditGrantParams struct {
	GrantID             string
	OrgID               string
	ScopeType           string
	ScopeProductID      interface{}
	ScopeBucketID       interface{}
	ScopeSkuID          interface{}
	Amount              int64
	Source              string
	SourceReferenceID   string
	EntitlementPeriodID interface{}
	PolicyVersion       string
	StartsAt            pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
	AccountID           []byte
	DepositTransferID   []byte
}

func (q *Queries) InsertManualCreditGrant(ctx context.Context, arg InsertManualCreditGrantParams) error {
	_, err := q.db.Exec(ctx, insertManualCreditGrant,
		arg.GrantID,
		arg.OrgID,
		arg.ScopeType,
		arg.ScopeProductID,
		arg.ScopeBucketID,
		arg.ScopeSkuID,
		arg.Amount,
		arg.Source,
		arg.SourceReferenceID,
		arg.EntitlementPeriodID,
		arg.PolicyVersion,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.AccountID,
		arg.DepositTransferID,
	)
	return err
}

const listActiveContractEntitlementLines = `-- name: ListActiveContractEntitlementLines :many
SELECT l.line_id,
       l.phase_id,
       l.contract_id,
       l.policy_id,
       l.scope_type,
       COALESCE(l.scope_product_id, '') AS scope_product_id,
       COALESCE(l.scope_bucket_id, '') AS scope_bucket_id,
       COALESCE(l.scope_sku_id, '') AS scope_sku_id,
       l.amount_units,
       l.policy_version,
       COALESCE(p.plan_id, '') AS plan_id
FROM contract_entitlement_lines l
JOIN contract_phases p ON p.phase_id = l.phase_id
JOIN contracts c ON c.contract_id = l.contract_id
WHERE l.org_id = $1
  AND l.product_id = $2
  AND p.state IN ('active', 'grace')
  AND p.effective_start <= $3
  AND (p.effective_end IS NULL OR p.effective_end > $3)
  AND l.active_from <= $3
  AND (l.active_until IS NULL OR l.active_until > $3)
  AND c.state IN ('active', 'past_due', 'cancel_scheduled')
ORDER BY l.line_id
`

type ListActiveContractEntitlementLinesParams struct {
	OrgID     string
	ProductID string
	Now       pgtype.Timestamptz
}

type ListActiveContractEntitlementLinesRow struct {
	LineID         string
	PhaseID        string
	ContractID     string
	PolicyID       pgtype.Text
	ScopeType      string
	ScopeProductID string
	ScopeBucketID  string
	ScopeSkuID     string
	AmountUnits    int64
	PolicyVersion  string
	PlanID         string
}

func (q *Queries) ListActiveContractEntitlementLines(ctx context.Context, arg ListActiveContractEntitlementLinesParams) ([]ListActiveContractEntitlementLinesRow, error) {
	rows, err := q.db.Query(ctx, listActiveContractEntitlementLines, arg.OrgID, arg.ProductID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveContractEntitlementLinesRow{}
	for rows.Next() {
		var i ListActiveContractEntitlementLinesRow
		if err := rows.Scan(
			&i.LineID,
			&i.PhaseID,
			&i.ContractID,
			&i.PolicyID,
			&i.ScopeType,
			&i.ScopeProductID,
			&i.ScopeBucketID,
			&i.ScopeSkuID,
			&i.AmountUnits,
			&i.PolicyVersion,
			&i.PlanID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveFreeTierPolicies = `-- name: ListActiveFreeTierPolicies :many
SELECT policy_id,
       scope_type,
       COALESCE(scope_product_id, '') AS scope_product_id,
       COALESCE(scope_bucket_id, '') AS scope_bucket_id,
       COALESCE(scope_sku_id, '') AS scope_sku_id,
       amount_units,
       policy_version
FROM entitlement_policies
WHERE source = 'free_tier'
  AND product_id = $1
  AND active_from <= $2
  AND (active_until IS NULL OR active_until > $2)
ORDER BY policy_id
`

type ListActiveFreeTierPoliciesParams struct {
	ProductID string
	Now       pgtype.Timestamptz
}

type ListActiveFreeTierPoliciesRow struct {
	PolicyID       string
	ScopeType      string
	ScopeProductID string
	ScopeBucketID  string
	ScopeSkuID     string
	AmountUnits    int64
	PolicyVersion  string
}

func (q *Queries) ListActiveFreeTierPolicies(ctx context.Context, arg ListActiveFreeTierPoliciesParams) ([]ListActiveFreeTierPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listActiveFreeTierPolicies, arg.ProductID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveFreeTierPoliciesRow{}
	for rows.Next() {
		var i ListActiveFreeTierPoliciesRow
		if err := rows.Scan(
			&i.PolicyID,
			&i.ScopeType,
			&i.ScopeProductID,
			&i.ScopeBucketID,
			&i.ScopeSkuID,
			&i.AmountUnits,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenMaterializedCreditGrant = `-- name: ReopenMaterializedCreditGrant :exec
UPDATE credit_grants
SET entitlement_period_id = $1,
    policy_version = $2,
    starts_at = $3,
    period_start = $3,
    period_end = $4,
    expires_at = $4,
    closed_at = NULL,
    closed_reason = '',
    metadata = (metadata - 'closed_by') || jsonb_build_object('reopened_by', 'entitlement-materializer'),
    updated_at = now()
WHERE org_id = $5
  AND source = $6
  AND scope_type = $7
  AND COALESCE(scope_product_id, '') = $8
  AND COALESCE(scope_bucket_id, '') = $9
  AND COALESCE(scope_sku_id, '') = $10
  AND source_reference_id = $11
  AND closed_at IS NOT NULL
`

type ReopenMaterializedCreditGrantParams struct {
	EntitlementPeriodID pgtype.Text
	PolicyVersion       string
	PeriodStart         pgtype.Timestamptz
	PeriodEnd           pgtype.Timestamptz
	OrgID               string
	Source              string
	ScopeType           string
	ScopeProductID      pgtype.Text
	ScopeBucketID       pgtype.Text
	ScopeSkuID          pgtype.Text
	SourceReferenceID   string
}

func (q *Queries) ReopenMaterializedCreditGrant(ctx context.Context, arg ReopenMaterializedCreditGrantParams) error {
	_, err := q.db.Exec(ctx, reopenMaterializedCreditGrant,
		arg.EntitlementPeriodID,
		arg.PolicyVersion,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.OrgID,
		arg.Source,
		arg.ScopeType,
		arg.ScopeProductID,
		arg.ScopeBucketID,
		arg.ScopeSkuID,
		arg.SourceReferenceID,
	)
	return err
}

const reopenMaterializedEntitlementPeriod = `-- name: ReopenMaterializedEntitlementPeriod :exec
UPDATE entitlement_periods
SET cycle_id = $1,
    amount_units = $2,
    period_start = $3,
    period_end = $4,
    policy_version = $5,
    payment_state = $6,
    entitlement_state = $7,
    calculation_kind = $8,
    metadata = (metadata - 'voided_by') || jsonb_build_object('reopened_by', 'entitlement-materializer'),
    updated_at = now()
WHERE org_id = $9
  AND source = $10
  AND source_reference_id = $11
  AND entitlement_state = 'voided'
`

type ReopenMaterializedEntitlementPeriodParams struct {
	CycleID           pgtype.Text
	AmountUnits       int64
	PeriodStart       pgtype.Timestamptz
	PeriodEnd         pgtype.Timestamptz
	PolicyVersion     string
	PaymentState      string
	EntitlementState  string
	CalculationKind   string
	OrgID             string
	Source            string
	SourceReferenceID string
}

func (q *Queries) ReopenMaterializedEntitlementPeriod(ctx context.Context, arg ReopenMaterializedEntitlementPeriodParams) error {
	_, err := q.db.Exec(ctx, reopenMaterializedEntitlementPeriod,
		arg.CycleID,
		arg.AmountUnits,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.PolicyVersion,
		arg.PaymentState,
		arg.EntitlementState,
		arg.CalculationKind,
		arg.OrgID,
		arg.Source,
		arg.SourceReferenceID,
	)
	return err
}
