load("//src/tools/deployment/nomad:component.bzl", "nomad_component")

exports_files(
    [
        "nftables/stalwart.nft",
    ],
    visibility = ["//src/configuration:__pkg__"],
)

filegroup(
    name = "role_sources",
    srcs = glob(
        [
            "defaults/**",
            "files/**",
            "handlers/**",
            "meta/**",
            "migrations/**",
            "tasks/**",
            "templates/**",
            "vars/**",
        ],
        allow_empty = True,
    ),
    visibility = ["//src/components:__pkg__"],
)

nomad_component(
    name = "nomad_component",
    component = "stalwart",
    job_id = "stalwart",
    job_spec = "nomad.hcl",
    provides = [
        "stalwart:http",
        "stalwart:smtp",
    ],
    requires = ["postgres:server"],
    visibility = ["//src/tools/deployment/nomad:__pkg__"],
)
