load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "pgtest",
    srcs = ["pgtest.go"],
    data = ["//src/host/binaries:postgresql_runtime"],
    importpath = "github.com/verself/service-runtime/pgtest",
    visibility = ["//src/services:__subpackages__"],
    deps = [
        "@com_github_lib_pq//:pq",
    ],
)
