package contractapi

import (
	"context"
)

// Code generated by //src/smithy/cmd/ir-go from governance-public. DO NOT EDIT.

type OperationDescriptor struct {
	ShapeID             string
	OperationID         string
	Method              string
	Path                string
	DefaultStatus       int
	Readonly            bool
	Paginated           bool
	Identity            IdentityDescriptor
	Authorization       AuthorizationDescriptor
	Audit               AuditDescriptor
	RateLimitBucket     string
	RequestBodyMaxBytes int64
	RequestPayload      PayloadDescriptor
	ResponsePayload     PayloadDescriptor
	ResponseHeaders     []HeaderDescriptor
	Idempotency         IdempotencyDescriptor
	SDK                 SDKDescriptor
	Problems            []ProblemDescriptor
}

type IdentityDescriptor struct {
	Mode       string
	Audience   string
	Principals []string
}

type AuthorizationDescriptor struct {
	Permission         string
	OrganizationSource string
	OrganizationMember string
}

type AuditDescriptor struct {
	Event    string
	Resource string
	Action   string
}

type IdempotencyDescriptor struct {
	Policy string
	Header string
	Member string
}

type PayloadDescriptor struct {
	Member    string
	Target    string
	Kind      string
	MediaType string
	Streaming bool
	Sensitive bool
	Required  bool
}

type HeaderDescriptor struct {
	Member string
	Name   string
}

type SDKDescriptor struct {
	Module    string
	Method    string
	Paginated bool
	Retryable bool
}

type ProblemDescriptor struct {
	ShapeID string
	Type    string
	Code    string
	Status  int
}

type Operation[Input any, Output any] struct {
	Descriptor OperationDescriptor
}

type Handler[Input any, Output any] func(context.Context, *Input) (*Output, error)

type IdempotencyKey string

type ProblemCode string

type ProblemDetail string

type ProblemType string

type RequestID string

type ResourceName string

type TraceParent string

type AuditActorID string

type AuditActorType string

type AuditCredentialID string

type AuditCursor string

type AuditErrorCode string

type AuditEventID string

type AuditEventOperationName string

type AuditEventSource string

type AuditEventsLimit int

type AuditHMACKeyID string

type AuditTargetID string

type AuditTargetType string

type ContentDisposition string

type DataExportArchive []byte

type DataExportID string

type DecimalUint64 string

type ExportArtifactPath string

type ExportDownloadURL string

type ExportErrorCode string

type ExportErrorMessage string

type ExportFormat string

type ExportScope string

type ExportState string

type GovernanceAuditEventName string

type GovernanceOrgID string

type GovernancePermissionName string

type HMACHex string

type MediaType string

type SHA256Hex string

type TraceID string

type AuditListOrder string

const (
	AuditListOrderAsc  AuditListOrder = "asc"
	AuditListOrderDesc AuditListOrder = "desc"
)

type AuditOutcome string

const (
	AuditOutcomeAllowed AuditOutcome = "allowed"
	AuditOutcomeDenied  AuditOutcome = "denied"
	AuditOutcomeError   AuditOutcome = "error"
)

type AuditEvents []AuditEvent

type DataExportFiles []DataExportFile

type DataExportJobs []DataExportJob

type ExportScopes []ExportScope

type ConflictError struct {
	Type        ProblemType    `json:"type" required:"true" pattern:"^(https://.+|urn:verself:problem:.+)$"`
	Title       string         `json:"title" required:"true"`
	Status      int            `json:"status" required:"true"`
	Detail      *ProblemDetail `json:"detail,omitempty" maxLength:"2048"`
	Instance    *string        `json:"instance,omitempty"`
	Code        ProblemCode    `json:"code" required:"true" pattern:"^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$"`
	RequestID   *RequestID     `json:"requestId,omitempty" minLength:"8" maxLength:"128"`
	Traceparent *TraceParent   `json:"traceparent,omitempty" minLength:"55" maxLength:"255"`
}

type IdempotencyPayloadMismatchError struct {
	Type        ProblemType    `json:"type" required:"true" pattern:"^(https://.+|urn:verself:problem:.+)$"`
	Title       string         `json:"title" required:"true"`
	Status      int            `json:"status" required:"true"`
	Detail      *ProblemDetail `json:"detail,omitempty" maxLength:"2048"`
	Instance    *string        `json:"instance,omitempty"`
	Code        ProblemCode    `json:"code" required:"true" pattern:"^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$"`
	RequestID   *RequestID     `json:"requestId,omitempty" minLength:"8" maxLength:"128"`
	Traceparent *TraceParent   `json:"traceparent,omitempty" minLength:"55" maxLength:"255"`
}

type PermissionDeniedError struct {
	Type        ProblemType    `json:"type" required:"true" pattern:"^(https://.+|urn:verself:problem:.+)$"`
	Title       string         `json:"title" required:"true"`
	Status      int            `json:"status" required:"true"`
	Detail      *ProblemDetail `json:"detail,omitempty" maxLength:"2048"`
	Instance    *string        `json:"instance,omitempty"`
	Code        ProblemCode    `json:"code" required:"true" pattern:"^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$"`
	RequestID   *RequestID     `json:"requestId,omitempty" minLength:"8" maxLength:"128"`
	Traceparent *TraceParent   `json:"traceparent,omitempty" minLength:"55" maxLength:"255"`
}

type RateLimitedError struct {
	Type        ProblemType    `json:"type" required:"true" pattern:"^(https://.+|urn:verself:problem:.+)$"`
	Title       string         `json:"title" required:"true"`
	Status      int            `json:"status" required:"true"`
	Detail      *ProblemDetail `json:"detail,omitempty" maxLength:"2048"`
	Instance    *string        `json:"instance,omitempty"`
	Code        ProblemCode    `json:"code" required:"true" pattern:"^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$"`
	RequestID   *RequestID     `json:"requestId,omitempty" minLength:"8" maxLength:"128"`
	Traceparent *TraceParent   `json:"traceparent,omitempty" minLength:"55" maxLength:"255"`
}

type ResourceNotFoundError struct {
	Type        ProblemType    `json:"type" required:"true" pattern:"^(https://.+|urn:verself:problem:.+)$"`
	Title       string         `json:"title" required:"true"`
	Status      int            `json:"status" required:"true"`
	Detail      *ProblemDetail `json:"detail,omitempty" maxLength:"2048"`
	Instance    *string        `json:"instance,omitempty"`
	Code        ProblemCode    `json:"code" required:"true" pattern:"^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$"`
	RequestID   *RequestID     `json:"requestId,omitempty" minLength:"8" maxLength:"128"`
	Traceparent *TraceParent   `json:"traceparent,omitempty" minLength:"55" maxLength:"255"`
}

type ServiceUnavailableError struct {
	Type        ProblemType    `json:"type" required:"true" pattern:"^(https://.+|urn:verself:problem:.+)$"`
	Title       string         `json:"title" required:"true"`
	Status      int            `json:"status" required:"true"`
	Detail      *ProblemDetail `json:"detail,omitempty" maxLength:"2048"`
	Instance    *string        `json:"instance,omitempty"`
	Code        ProblemCode    `json:"code" required:"true" pattern:"^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$"`
	RequestID   *RequestID     `json:"requestId,omitempty" minLength:"8" maxLength:"128"`
	Traceparent *TraceParent   `json:"traceparent,omitempty" minLength:"55" maxLength:"255"`
}

type UnauthenticatedError struct {
	Type        ProblemType    `json:"type" required:"true" pattern:"^(https://.+|urn:verself:problem:.+)$"`
	Title       string         `json:"title" required:"true"`
	Status      int            `json:"status" required:"true"`
	Detail      *ProblemDetail `json:"detail,omitempty" maxLength:"2048"`
	Instance    *string        `json:"instance,omitempty"`
	Code        ProblemCode    `json:"code" required:"true" pattern:"^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$"`
	RequestID   *RequestID     `json:"requestId,omitempty" minLength:"8" maxLength:"128"`
	Traceparent *TraceParent   `json:"traceparent,omitempty" minLength:"55" maxLength:"255"`
}

type ValidationFailedError struct {
	Type        ProblemType    `json:"type" required:"true" pattern:"^(https://.+|urn:verself:problem:.+)$"`
	Title       string         `json:"title" required:"true"`
	Status      int            `json:"status" required:"true"`
	Detail      *ProblemDetail `json:"detail,omitempty" maxLength:"2048"`
	Instance    *string        `json:"instance,omitempty"`
	Code        ProblemCode    `json:"code" required:"true" pattern:"^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$"`
	RequestID   *RequestID     `json:"requestId,omitempty" minLength:"8" maxLength:"128"`
	Traceparent *TraceParent   `json:"traceparent,omitempty" minLength:"55" maxLength:"255"`
}

type AuditEvent struct {
	EventID            AuditEventID             `json:"event_id" required:"true" pattern:"^[0-9a-fA-F-]{36}$"`
	RecordedAt         string                   `json:"recorded_at" required:"true"`
	OrgID              GovernanceOrgID          `json:"org_id" required:"true" minLength:"1" maxLength:"128"`
	Sequence           DecimalUint64            `json:"sequence" required:"true" pattern:"^[0-9]+$"`
	EventSource        AuditEventSource         `json:"event_source" required:"true" minLength:"1" maxLength:"128"`
	EventName          AuditEventOperationName  `json:"event_name" required:"true" minLength:"1" maxLength:"128"`
	AuditEvent         GovernanceAuditEventName `json:"audit_event" required:"true" minLength:"1" maxLength:"255"`
	ActorType          AuditActorType           `json:"actor_type" required:"true" minLength:"1" maxLength:"128" pattern:"^[a-z][a-z0-9_.-]*$"`
	ActorID            AuditActorID             `json:"actor_id" required:"true" minLength:"1" maxLength:"512"`
	CredentialID       *AuditCredentialID       `json:"credential_id,omitempty" maxLength:"512"`
	TargetType         AuditTargetType          `json:"target_type" required:"true" minLength:"1" maxLength:"128" pattern:"^[a-z][a-z0-9_]*$"`
	TargetID           *AuditTargetID           `json:"target_id,omitempty" maxLength:"512"`
	TargetResourceName *ResourceName            `json:"targetResourceName,omitempty" minLength:"1" maxLength:"1024" pattern:"^urn:verself:.+$"`
	Permission         GovernancePermissionName `json:"permission" required:"true" minLength:"1" maxLength:"255"`
	Outcome            AuditOutcome             `json:"outcome" required:"true"`
	ErrorCode          *AuditErrorCode          `json:"error_code,omitempty" maxLength:"128"`
	TraceID            *TraceID                 `json:"trace_id,omitempty" pattern:"^[0-9a-f]{32}$"`
	DetailSha256       SHA256Hex                `json:"detail_sha256" required:"true" pattern:"^[0-9a-f]{64}$"`
	PrevHmac           HMACHex                  `json:"prev_hmac" required:"true" pattern:"^[0-9a-f]{64}$"`
	RowHmac            HMACHex                  `json:"row_hmac" required:"true" pattern:"^[0-9a-f]{64}$"`
	HmacKeyID          *AuditHMACKeyID          `json:"hmac_key_id,omitempty" maxLength:"128"`
}

type AuditFilters struct {
	ActorID            *AuditActorID             `json:"actor_id,omitempty" minLength:"1" maxLength:"512"`
	AuditEvent         *GovernanceAuditEventName `json:"audit_event,omitempty" minLength:"1" maxLength:"255"`
	CredentialID       *AuditCredentialID        `json:"credential_id,omitempty" maxLength:"512"`
	EventName          *AuditEventOperationName  `json:"event_name,omitempty" minLength:"1" maxLength:"128"`
	EventSource        *AuditEventSource         `json:"event_source,omitempty" minLength:"1" maxLength:"128"`
	Outcome            *AuditOutcome             `json:"outcome,omitempty"`
	TargetID           *AuditTargetID            `json:"target_id,omitempty" maxLength:"512"`
	TargetType         *AuditTargetType          `json:"target_type,omitempty" minLength:"1" maxLength:"128" pattern:"^[a-z][a-z0-9_]*$"`
	TargetResourceName *ResourceName             `json:"targetResourceName,omitempty" minLength:"1" maxLength:"1024" pattern:"^urn:verself:.+$"`
}

type CreateDataExportInputBody struct {
	Scopes      *ExportScopes `json:"scopes,omitempty"`
	IncludeLogs *bool         `json:"include_logs,omitempty"`
}

type CreateDataExportInput struct {
	IdempotencyKey IdempotencyKey `header:"Idempotency-Key" required:"true" minLength:"8" maxLength:"128"`
	Body           CreateDataExportInputBody
}

type DataExportFile struct {
	Path        ExportArtifactPath `json:"path" required:"true" minLength:"1" maxLength:"512"`
	ContentType MediaType          `json:"content_type" required:"true" minLength:"1" maxLength:"255"`
	Rows        DecimalUint64      `json:"rows" required:"true" pattern:"^[0-9]+$"`
	Bytes       DecimalUint64      `json:"bytes" required:"true" pattern:"^[0-9]+$"`
	Sha256      SHA256Hex          `json:"sha256" required:"true" pattern:"^[0-9a-f]{64}$"`
}

type DataExportJob struct {
	ExportID       DataExportID        `json:"export_id" required:"true" pattern:"^[0-9a-fA-F-]{36}$"`
	ResourceName   ResourceName        `json:"resourceName" required:"true" minLength:"1" maxLength:"1024" pattern:"^urn:verself:.+$"`
	OrgID          GovernanceOrgID     `json:"org_id" required:"true" minLength:"1" maxLength:"128"`
	RequestedBy    AuditActorID        `json:"requested_by" required:"true" minLength:"1" maxLength:"512"`
	Scopes         ExportScopes        `json:"scopes" required:"true"`
	IncludeLogs    bool                `json:"include_logs" required:"true"`
	Format         ExportFormat        `json:"format" required:"true" minLength:"1" maxLength:"128"`
	State          ExportState         `json:"state" required:"true" minLength:"1" maxLength:"128"`
	ArtifactSha256 *SHA256Hex          `json:"artifact_sha256,omitempty" pattern:"^[0-9a-f]{64}$"`
	ArtifactBytes  DecimalUint64       `json:"artifact_bytes" required:"true" pattern:"^[0-9]+$"`
	DownloadURL    *ExportDownloadURL  `json:"download_url,omitempty" maxLength:"4096"`
	Files          DataExportFiles     `json:"files" required:"true"`
	CreatedAt      string              `json:"created_at" required:"true"`
	UpdatedAt      string              `json:"updated_at" required:"true"`
	CompletedAt    *string             `json:"completed_at,omitempty"`
	ExpiresAt      string              `json:"expires_at" required:"true"`
	ErrorCode      *ExportErrorCode    `json:"error_code,omitempty" maxLength:"128"`
	ErrorMessage   *ExportErrorMessage `json:"error_message,omitempty" maxLength:"2048"`
}

type DownloadDataExportInput struct {
	ExportID DataExportID `path:"export_id" required:"true" pattern:"^[0-9a-fA-F-]{36}$"`
}

type GetDataExportInput struct {
	ExportID DataExportID `path:"export_id" required:"true" pattern:"^[0-9a-fA-F-]{36}$"`
}

type ListAuditEventsInput struct {
	Limit              AuditEventsLimit         `query:"limit" minimum:"1" maximum:"200"`
	Cursor             AuditCursor              `query:"cursor" minLength:"1" maxLength:"4096"`
	Order              AuditListOrder           `query:"order"`
	ActorID            AuditActorID             `query:"actor_id" minLength:"1" maxLength:"512"`
	AuditEvent         GovernanceAuditEventName `query:"audit_event" minLength:"1" maxLength:"255"`
	CredentialID       AuditCredentialID        `query:"credential_id" maxLength:"512"`
	EventName          AuditEventOperationName  `query:"event_name" minLength:"1" maxLength:"128"`
	EventSource        AuditEventSource         `query:"event_source" minLength:"1" maxLength:"128"`
	Outcome            AuditOutcome             `query:"outcome"`
	TargetID           AuditTargetID            `query:"target_id" maxLength:"512"`
	TargetType         AuditTargetType          `query:"target_type" minLength:"1" maxLength:"128" pattern:"^[a-z][a-z0-9_]*$"`
	TargetResourceName ResourceName             `query:"targetResourceName" minLength:"1" maxLength:"1024" pattern:"^urn:verself:.+$"`
}

type ListDataExportsInput struct{}

type ListAuditEventsOutputBody struct {
	Events     AuditEvents      `json:"events" required:"true"`
	NextCursor *AuditCursor     `json:"next_cursor,omitempty" minLength:"1" maxLength:"4096"`
	Limit      AuditEventsLimit `json:"limit" required:"true" minimum:"1" maximum:"200"`
	Filters    AuditFilters     `json:"filters" required:"true"`
}

type ListAuditEventsOutput struct {
	Body ListAuditEventsOutputBody
}

type ListDataExportsOutputBody struct {
	Exports DataExportJobs `json:"exports" required:"true"`
}

type ListDataExportsOutput struct {
	Body ListDataExportsOutputBody
}

type CreateDataExportOutputBody struct {
	Export DataExportJob `json:"export" required:"true"`
}

type CreateDataExportOutput struct {
	Body CreateDataExportOutputBody
}

type GetDataExportOutputBody struct {
	Export DataExportJob `json:"export" required:"true"`
}

type GetDataExportOutput struct {
	Body GetDataExportOutputBody
}

type DownloadDataExportOutput struct {
	ContentType        MediaType          `header:"Content-Type" required:"true" minLength:"1" maxLength:"255"`
	ContentDisposition ContentDisposition `header:"Content-Disposition" required:"true" minLength:"1" maxLength:"255"`
	Body               []byte
}

var Operations = []OperationDescriptor{
	ListAuditEvents.Descriptor,
	ListDataExports.Descriptor,
	CreateDataExport.Descriptor,
	GetDataExport.Descriptor,
	DownloadDataExport.Descriptor,
}

var ListAuditEvents = Operation[ListAuditEventsInput, ListAuditEventsOutput]{
	Descriptor: OperationDescriptor{
		ShapeID:             "verself.governance.v1#ListAuditEvents",
		OperationID:         "list-audit-events",
		Method:              "GET",
		Path:                "/api/v1/governance/audit/events",
		DefaultStatus:       200,
		Readonly:            true,
		Paginated:           true,
		Identity:            IdentityDescriptor{Mode: "bearer", Audience: "governance-service", Principals: []string{"browser", "cli", "workload"}},
		Authorization:       AuthorizationDescriptor{Permission: "governance:audit_log:read", OrganizationSource: "token_org_id", OrganizationMember: ""},
		Audit:               AuditDescriptor{Event: "governance.audit_log.list", Resource: "audit_log", Action: "list"},
		RateLimitBucket:     "read",
		RequestBodyMaxBytes: 0,
		RequestPayload:      PayloadDescriptor{},
		ResponsePayload:     PayloadDescriptor{},
		ResponseHeaders:     []HeaderDescriptor{},
		Idempotency:         IdempotencyDescriptor{Policy: "", Header: "", Member: ""},
		SDK:                 SDKDescriptor{Module: "governance.audit", Method: "listEvents", Paginated: true, Retryable: true},
		Problems: []ProblemDescriptor{
			{ShapeID: "verself.common.v1#PermissionDeniedError", Type: "urn:verself:problem:auth:permission_denied", Code: "auth.permission_denied", Status: 403},
			{ShapeID: "verself.common.v1#RateLimitedError", Type: "urn:verself:problem:quota:rate_limited", Code: "quota.rate_limited", Status: 429},
			{ShapeID: "verself.common.v1#ServiceUnavailableError", Type: "urn:verself:problem:service:unavailable", Code: "service.unavailable", Status: 503},
			{ShapeID: "verself.common.v1#UnauthenticatedError", Type: "urn:verself:problem:auth:unauthenticated", Code: "auth.unauthenticated", Status: 401},
		},
	},
}

var ListDataExports = Operation[ListDataExportsInput, ListDataExportsOutput]{
	Descriptor: OperationDescriptor{
		ShapeID:             "verself.governance.v1#ListDataExports",
		OperationID:         "list-data-exports",
		Method:              "GET",
		Path:                "/api/v1/governance/exports",
		DefaultStatus:       200,
		Readonly:            true,
		Paginated:           false,
		Identity:            IdentityDescriptor{Mode: "bearer", Audience: "governance-service", Principals: []string{"browser", "cli", "workload"}},
		Authorization:       AuthorizationDescriptor{Permission: "governance:audit_log:export", OrganizationSource: "token_org_id", OrganizationMember: ""},
		Audit:               AuditDescriptor{Event: "governance.audit_log.export.list", Resource: "data_export", Action: "list"},
		RateLimitBucket:     "read",
		RequestBodyMaxBytes: 0,
		RequestPayload:      PayloadDescriptor{},
		ResponsePayload:     PayloadDescriptor{},
		ResponseHeaders:     []HeaderDescriptor{},
		Idempotency:         IdempotencyDescriptor{Policy: "", Header: "", Member: ""},
		SDK:                 SDKDescriptor{Module: "governance.exports", Method: "list", Paginated: false, Retryable: true},
		Problems: []ProblemDescriptor{
			{ShapeID: "verself.common.v1#PermissionDeniedError", Type: "urn:verself:problem:auth:permission_denied", Code: "auth.permission_denied", Status: 403},
			{ShapeID: "verself.common.v1#RateLimitedError", Type: "urn:verself:problem:quota:rate_limited", Code: "quota.rate_limited", Status: 429},
			{ShapeID: "verself.common.v1#ServiceUnavailableError", Type: "urn:verself:problem:service:unavailable", Code: "service.unavailable", Status: 503},
			{ShapeID: "verself.common.v1#UnauthenticatedError", Type: "urn:verself:problem:auth:unauthenticated", Code: "auth.unauthenticated", Status: 401},
		},
	},
}

var CreateDataExport = Operation[CreateDataExportInput, CreateDataExportOutput]{
	Descriptor: OperationDescriptor{
		ShapeID:             "verself.governance.v1#CreateDataExport",
		OperationID:         "create-data-export",
		Method:              "POST",
		Path:                "/api/v1/governance/exports",
		DefaultStatus:       201,
		Readonly:            false,
		Paginated:           false,
		Identity:            IdentityDescriptor{Mode: "bearer", Audience: "governance-service", Principals: []string{"browser", "cli"}},
		Authorization:       AuthorizationDescriptor{Permission: "governance:audit_log:export", OrganizationSource: "token_org_id", OrganizationMember: ""},
		Audit:               AuditDescriptor{Event: "governance.audit_log.export.create", Resource: "data_export", Action: "create"},
		RateLimitBucket:     "export_create",
		RequestBodyMaxBytes: 16384,
		RequestPayload:      PayloadDescriptor{},
		ResponsePayload:     PayloadDescriptor{},
		ResponseHeaders:     []HeaderDescriptor{},
		Idempotency:         IdempotencyDescriptor{Policy: "idempotency_key_header", Header: "Idempotency-Key", Member: "idempotencyKey"},
		SDK:                 SDKDescriptor{Module: "governance.exports", Method: "create", Paginated: false, Retryable: false},
		Problems: []ProblemDescriptor{
			{ShapeID: "verself.common.v1#ConflictError", Type: "urn:verself:problem:conflict:state", Code: "conflict.state", Status: 409},
			{ShapeID: "verself.common.v1#IdempotencyPayloadMismatchError", Type: "urn:verself:problem:conflict:idempotency_payload_mismatch", Code: "conflict.idempotency_payload_mismatch", Status: 409},
			{ShapeID: "verself.common.v1#PermissionDeniedError", Type: "urn:verself:problem:auth:permission_denied", Code: "auth.permission_denied", Status: 403},
			{ShapeID: "verself.common.v1#RateLimitedError", Type: "urn:verself:problem:quota:rate_limited", Code: "quota.rate_limited", Status: 429},
			{ShapeID: "verself.common.v1#ServiceUnavailableError", Type: "urn:verself:problem:service:unavailable", Code: "service.unavailable", Status: 503},
			{ShapeID: "verself.common.v1#UnauthenticatedError", Type: "urn:verself:problem:auth:unauthenticated", Code: "auth.unauthenticated", Status: 401},
			{ShapeID: "verself.common.v1#ValidationFailedError", Type: "urn:verself:problem:request:validation_failed", Code: "request.validation_failed", Status: 400},
		},
	},
}

var GetDataExport = Operation[GetDataExportInput, GetDataExportOutput]{
	Descriptor: OperationDescriptor{
		ShapeID:             "verself.governance.v1#GetDataExport",
		OperationID:         "get-data-export",
		Method:              "GET",
		Path:                "/api/v1/governance/exports/{export_id}",
		DefaultStatus:       200,
		Readonly:            true,
		Paginated:           false,
		Identity:            IdentityDescriptor{Mode: "bearer", Audience: "governance-service", Principals: []string{"browser", "cli", "workload"}},
		Authorization:       AuthorizationDescriptor{Permission: "governance:audit_log:export", OrganizationSource: "token_org_id", OrganizationMember: ""},
		Audit:               AuditDescriptor{Event: "governance.audit_log.export.read", Resource: "data_export", Action: "read"},
		RateLimitBucket:     "read",
		RequestBodyMaxBytes: 0,
		RequestPayload:      PayloadDescriptor{},
		ResponsePayload:     PayloadDescriptor{},
		ResponseHeaders:     []HeaderDescriptor{},
		Idempotency:         IdempotencyDescriptor{Policy: "", Header: "", Member: ""},
		SDK:                 SDKDescriptor{Module: "governance.exports", Method: "get", Paginated: false, Retryable: true},
		Problems: []ProblemDescriptor{
			{ShapeID: "verself.common.v1#PermissionDeniedError", Type: "urn:verself:problem:auth:permission_denied", Code: "auth.permission_denied", Status: 403},
			{ShapeID: "verself.common.v1#RateLimitedError", Type: "urn:verself:problem:quota:rate_limited", Code: "quota.rate_limited", Status: 429},
			{ShapeID: "verself.common.v1#ResourceNotFoundError", Type: "urn:verself:problem:resource:not_found", Code: "resource.not_found", Status: 404},
			{ShapeID: "verself.common.v1#ServiceUnavailableError", Type: "urn:verself:problem:service:unavailable", Code: "service.unavailable", Status: 503},
			{ShapeID: "verself.common.v1#UnauthenticatedError", Type: "urn:verself:problem:auth:unauthenticated", Code: "auth.unauthenticated", Status: 401},
		},
	},
}

var DownloadDataExport = Operation[DownloadDataExportInput, DownloadDataExportOutput]{
	Descriptor: OperationDescriptor{
		ShapeID:             "verself.governance.v1#DownloadDataExport",
		OperationID:         "download-data-export",
		Method:              "GET",
		Path:                "/api/v1/governance/exports/{export_id}/download",
		DefaultStatus:       200,
		Readonly:            true,
		Paginated:           false,
		Identity:            IdentityDescriptor{Mode: "bearer", Audience: "governance-service", Principals: []string{"browser", "cli"}},
		Authorization:       AuthorizationDescriptor{Permission: "governance:audit_log:export", OrganizationSource: "token_org_id", OrganizationMember: ""},
		Audit:               AuditDescriptor{Event: "governance.audit_log.export.download", Resource: "data_export", Action: "download"},
		RateLimitBucket:     "export_download",
		RequestBodyMaxBytes: 0,
		RequestPayload:      PayloadDescriptor{},
		ResponsePayload:     PayloadDescriptor{Member: "body", Target: "verself.governance.v1#DataExportArchive", Kind: "blob", MediaType: "application/gzip", Streaming: false, Sensitive: false, Required: true},
		ResponseHeaders: []HeaderDescriptor{
			{Member: "contentDisposition", Name: "Content-Disposition"},
			{Member: "contentType", Name: "Content-Type"},
		},
		Idempotency: IdempotencyDescriptor{Policy: "", Header: "", Member: ""},
		SDK:         SDKDescriptor{Module: "governance.exports", Method: "download", Paginated: false, Retryable: true},
		Problems: []ProblemDescriptor{
			{ShapeID: "verself.common.v1#PermissionDeniedError", Type: "urn:verself:problem:auth:permission_denied", Code: "auth.permission_denied", Status: 403},
			{ShapeID: "verself.common.v1#RateLimitedError", Type: "urn:verself:problem:quota:rate_limited", Code: "quota.rate_limited", Status: 429},
			{ShapeID: "verself.common.v1#ResourceNotFoundError", Type: "urn:verself:problem:resource:not_found", Code: "resource.not_found", Status: 404},
			{ShapeID: "verself.common.v1#ServiceUnavailableError", Type: "urn:verself:problem:service:unavailable", Code: "service.unavailable", Status: 503},
			{ShapeID: "verself.common.v1#UnauthenticatedError", Type: "urn:verself:problem:auth:unauthenticated", Code: "auth.unauthenticated", Status: 401},
		},
	},
}

type Handlers = PublicHandlers

type PublicHandlers interface {
	ListAuditEvents(context.Context, *ListAuditEventsInput) (*ListAuditEventsOutput, error)
	ListDataExports(context.Context, *ListDataExportsInput) (*ListDataExportsOutput, error)
	CreateDataExport(context.Context, *CreateDataExportInput) (*CreateDataExportOutput, error)
	GetDataExport(context.Context, *GetDataExportInput) (*GetDataExportOutput, error)
	DownloadDataExport(context.Context, *DownloadDataExportInput) (*DownloadDataExportOutput, error)
}

type ListAuditEventsHandler = Handler[ListAuditEventsInput, ListAuditEventsOutput]

type ListDataExportsHandler = Handler[ListDataExportsInput, ListDataExportsOutput]

type CreateDataExportHandler = Handler[CreateDataExportInput, CreateDataExportOutput]

type GetDataExportHandler = Handler[GetDataExportInput, GetDataExportOutput]

type DownloadDataExportHandler = Handler[DownloadDataExportInput, DownloadDataExportOutput]
