load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "clickhouse-spiffe-bundle-reload_lib",
    srcs = ["main.go"],
    importpath = "github.com/verself/infrastructure-components/clickhouse/cmd/clickhouse-spiffe-bundle-reload",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "clickhouse-spiffe-bundle-reload",
    embed = [":clickhouse-spiffe-bundle-reload_lib"],
    visibility = ["//visibility:public"],
)
