load("@rules_java//java:defs.bzl", "java_library")
load("//src/tools/build:check_tests.bzl", "stamp_test")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "java_sources",
    srcs = glob(["java/**/*.java"]),
)

java_library(
    name = "verself_smithy_validators",
    srcs = [":java_sources"],
    resource_strip_prefix = "src/smithy/plugins/validators/resources",
    resources = glob(["resources/**"]),
    deps = [
        "@maven//:software_amazon_smithy_smithy_model",
    ],
)

genrule(
    name = "java_format_check",
    srcs = [":java_sources"],
    outs = ["java_format_check.stamp"],
    cmd = "$(execpath //src/smithy/tools:google_java_format) --dry-run --set-exit-if-changed $(SRCS) && touch $@",
    tags = ["repo_check"],
    tools = ["//src/smithy/tools:google_java_format"],
)

stamp_test(
    name = "java_format_test",
    tags = [
        "java_format_check",
        "repo_check",
    ],
    target = ":java_format_check",
)
