# gazelle:prefix github.com/verself/notifications-service

load("//src/infrastructure-components/spire:identity.bzl", "spire_identity")
load("//src/tools/build:go_module_checks.bzl", "go_module_checks")

go_module_checks()

spire_identity(
    name = "spiffe_identity",
    component = "notifications_service",
    entry_id = "verself-notifications-service",
    key = "notifications_service.default",
    path = "/svc/notifications-service",
    user = "notifications_service",
    visibility = ["//src/infrastructure-components/spire:__pkg__"],
)
