# gazelle:prefix github.com/verself/notifications-service

load("//src/tools/build:go_module_checks.bzl", "go_module_checks")
load("//src/tools/deployment:declarations.bzl", "deploy_declarations")
load("//src/tools/deployment/nomad:component.bzl", "nomad_component")
load("//src/tools/deployment/spire:identity.bzl", "spire_identity")

deploy_declarations(visibility = ["//visibility:public"])

go_module_checks()

spire_identity(
    name = "spiffe_identity",
    component = "notifications_service",
    entry_id = "verself-notifications-service",
    key = "notifications_service.default",
    path = "/svc/notifications-service",
    user = "notifications_service",
    visibility = ["//src/host:__pkg__"],
)

nomad_component(
    name = "nomad_component",
    artifacts = {
        "//src/services/notifications-service/cmd/notifications-service:notifications-service_nomad_artifact": "notifications-service",
    },
    component = "notifications_service",
    digest_inputs = [":deploy_declarations"],
    job_id = "notifications-service",
    job_spec = "nomad.hcl",
    visibility = ["//src/tools/deployment/nomad:__pkg__"],
)
