# gazelle:prefix github.com/verself/notifications-service

load("//src/tools/build:go_module_checks.bzl", "go_module_checks")
load("//src/tools/deployment:declarations.bzl", "deploy_declarations")
load("//src/tools/deployment/spire:identity.bzl", "spire_identity")

deploy_declarations(visibility = ["//visibility:public"])

go_module_checks()

spire_identity(
    name = "spiffe_identity",
    component = "notifications_service",
    entry_id = "verself-notifications-service",
    key = "notifications_service.default",
    path = "/svc/notifications-service",
    user = "notifications_service",
    visibility = ["//src/infrastructure-components/spire:__pkg__"],
)
