# gazelle:prefix github.com/verself/source-code-hosting-service

load("//src/infrastructure-components/spire:identity.bzl", "spire_identity")
load("//src/tools/build:go_module_checks.bzl", "go_module_checks")

go_module_checks()

filegroup(
    name = "guardian_crd",
    srcs = ["guardian/v1alpha1/schema.cue"],
    visibility = ["//src/guardian-specification:__pkg__"],
)

spire_identity(
    name = "spiffe_identity",
    component = "source_code_hosting_service",
    entry_id = "verself-source-code-hosting-service",
    key = "source_code_hosting_service.default",
    path = "/svc/source-code-hosting-service",
    user = "source_code_hosting_service",
    visibility = ["//src/infrastructure-components/spire:__pkg__"],
)
