# gazelle:prefix github.com/verself/source-code-hosting-service

load("//src/tools/build:go_module_checks.bzl", "go_module_checks")
load("//src/tools/deployment:declarations.bzl", "deploy_declarations")
load("//src/tools/deployment/nomad:component.bzl", "nomad_component")
load("//src/tools/deployment/spire:identity.bzl", "spire_identity")

deploy_declarations(visibility = ["//visibility:public"])

go_module_checks()

spire_identity(
    name = "spiffe_identity",
    component = "source_code_hosting_service",
    entry_id = "verself-source-code-hosting-service",
    key = "source_code_hosting_service.default",
    path = "/svc/source-code-hosting-service",
    user = "source_code_hosting_service",
    visibility = ["//src/host:__pkg__"],
)

nomad_component(
    name = "nomad_component",
    artifacts = {
        "//src/services/source-code-hosting-service/cmd/source-code-hosting-service:source-code-hosting-service_nomad_artifact": "source-code-hosting-service",
    },
    component = "source_code_hosting_service",
    digest_inputs = [":deploy_declarations"],
    job_id = "source-code-hosting-service",
    job_spec = "nomad.hcl",
    requires = [
        "forgejo:http",
        "nomad:job:secrets-service",
        "postgres:server",
    ],
    visibility = ["//src/tools/deployment/nomad:__pkg__"],
)
