// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cycles.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeCycleForUsage = `-- name: CloseCycleForUsage :execrows
UPDATE billing_cycles
SET status = 'closed_for_usage',
    closed_for_usage_at = $1
WHERE cycle_id = $2
  AND status IN ('open', 'closing')
`

type CloseCycleForUsageParams struct {
	ClosedAt pgtype.Timestamptz
	CycleID  string
}

func (q *Queries) CloseCycleForUsage(ctx context.Context, arg CloseCycleForUsageParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeCycleForUsage, arg.ClosedAt, arg.CycleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeFreeCycleAtActivation = `-- name: CloseFreeCycleAtActivation :exec
UPDATE billing_cycles
SET status = 'closed_for_usage',
    ends_at = $1,
    finalization_due_at = $1,
    closed_for_usage_at = $1,
    closed_reason = 'free_to_paid_activation'
WHERE cycle_id = $2
  AND status IN ('open', 'closing')
`

type CloseFreeCycleAtActivationParams struct {
	EffectiveAt pgtype.Timestamptz
	CycleID     string
}

func (q *Queries) CloseFreeCycleAtActivation(ctx context.Context, arg CloseFreeCycleAtActivationParams) error {
	_, err := q.db.Exec(ctx, closeFreeCycleAtActivation, arg.EffectiveAt, arg.CycleID)
	return err
}

const getAnyOpenBillingCycle = `-- name: GetAnyOpenBillingCycle :one
SELECT cycle_id,
       currency,
       COALESCE(predecessor_cycle_id, '') AS predecessor_cycle_id,
       anchor_at,
       cycle_seq,
       cadence_kind,
       starts_at,
       ends_at
FROM billing_cycles
WHERE org_id = $1
  AND product_id = $2
  AND status IN ('open', 'closing')
ORDER BY starts_at DESC, cycle_id DESC
LIMIT 1
`

type GetAnyOpenBillingCycleParams struct {
	OrgID     string
	ProductID string
}

type GetAnyOpenBillingCycleRow struct {
	CycleID            string
	Currency           string
	PredecessorCycleID string
	AnchorAt           pgtype.Timestamptz
	CycleSeq           int64
	CadenceKind        string
	StartsAt           pgtype.Timestamptz
	EndsAt             pgtype.Timestamptz
}

func (q *Queries) GetAnyOpenBillingCycle(ctx context.Context, arg GetAnyOpenBillingCycleParams) (GetAnyOpenBillingCycleRow, error) {
	row := q.db.QueryRow(ctx, getAnyOpenBillingCycle, arg.OrgID, arg.ProductID)
	var i GetAnyOpenBillingCycleRow
	err := row.Scan(
		&i.CycleID,
		&i.Currency,
		&i.PredecessorCycleID,
		&i.AnchorAt,
		&i.CycleSeq,
		&i.CadenceKind,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const getNextDueOpenCycleForUpdate = `-- name: GetNextDueOpenCycleForUpdate :one
SELECT cycle_id,
       currency,
       COALESCE(predecessor_cycle_id, '') AS predecessor_cycle_id,
       anchor_at,
       cycle_seq,
       cadence_kind,
       starts_at,
       ends_at
FROM billing_cycles
WHERE org_id = $1
  AND product_id = $2
  AND status IN ('open', 'closing')
  AND ends_at <= $3
ORDER BY ends_at, cycle_id
LIMIT 1
FOR UPDATE
`

type GetNextDueOpenCycleForUpdateParams struct {
	OrgID     string
	ProductID string
	Now       pgtype.Timestamptz
}

type GetNextDueOpenCycleForUpdateRow struct {
	CycleID            string
	Currency           string
	PredecessorCycleID string
	AnchorAt           pgtype.Timestamptz
	CycleSeq           int64
	CadenceKind        string
	StartsAt           pgtype.Timestamptz
	EndsAt             pgtype.Timestamptz
}

func (q *Queries) GetNextDueOpenCycleForUpdate(ctx context.Context, arg GetNextDueOpenCycleForUpdateParams) (GetNextDueOpenCycleForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getNextDueOpenCycleForUpdate, arg.OrgID, arg.ProductID, arg.Now)
	var i GetNextDueOpenCycleForUpdateRow
	err := row.Scan(
		&i.CycleID,
		&i.Currency,
		&i.PredecessorCycleID,
		&i.AnchorAt,
		&i.CycleSeq,
		&i.CadenceKind,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const getOpenBillingCycleContaining = `-- name: GetOpenBillingCycleContaining :one
SELECT cycle_id,
       currency,
       COALESCE(predecessor_cycle_id, '') AS predecessor_cycle_id,
       anchor_at,
       cycle_seq,
       cadence_kind,
       starts_at,
       ends_at
FROM billing_cycles
WHERE org_id = $1
  AND product_id = $2
  AND status IN ('open', 'closing')
  AND starts_at <= $3
  AND ends_at > $3
ORDER BY starts_at DESC, cycle_id DESC
LIMIT 1
`

type GetOpenBillingCycleContainingParams struct {
	OrgID     string
	ProductID string
	Now       pgtype.Timestamptz
}

type GetOpenBillingCycleContainingRow struct {
	CycleID            string
	Currency           string
	PredecessorCycleID string
	AnchorAt           pgtype.Timestamptz
	CycleSeq           int64
	CadenceKind        string
	StartsAt           pgtype.Timestamptz
	EndsAt             pgtype.Timestamptz
}

func (q *Queries) GetOpenBillingCycleContaining(ctx context.Context, arg GetOpenBillingCycleContainingParams) (GetOpenBillingCycleContainingRow, error) {
	row := q.db.QueryRow(ctx, getOpenBillingCycleContaining, arg.OrgID, arg.ProductID, arg.Now)
	var i GetOpenBillingCycleContainingRow
	err := row.Scan(
		&i.CycleID,
		&i.Currency,
		&i.PredecessorCycleID,
		&i.AnchorAt,
		&i.CycleSeq,
		&i.CadenceKind,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const linkSuccessorBillingCycle = `-- name: LinkSuccessorBillingCycle :exec
UPDATE billing_cycles
SET successor_cycle_id = $1
WHERE cycle_id = $2
  AND successor_cycle_id IS NULL
`

type LinkSuccessorBillingCycleParams struct {
	SuccessorCycleID pgtype.Text
	CycleID          string
}

func (q *Queries) LinkSuccessorBillingCycle(ctx context.Context, arg LinkSuccessorBillingCycleParams) error {
	_, err := q.db.Exec(ctx, linkSuccessorBillingCycle, arg.SuccessorCycleID, arg.CycleID)
	return err
}

const listPendingDueBillingWorkTargets = `-- name: ListPendingDueBillingWorkTargets :many
SELECT DISTINCT org_id, product_id
FROM billing_cycles
WHERE status IN ('open', 'closing')
  AND ends_at <= transaction_timestamp()
ORDER BY org_id, product_id
LIMIT $1
`

type ListPendingDueBillingWorkTargetsParams struct {
	LimitCount int32
}

type ListPendingDueBillingWorkTargetsRow struct {
	OrgID     string
	ProductID string
}

func (q *Queries) ListPendingDueBillingWorkTargets(ctx context.Context, arg ListPendingDueBillingWorkTargetsParams) ([]ListPendingDueBillingWorkTargetsRow, error) {
	rows, err := q.db.Query(ctx, listPendingDueBillingWorkTargets, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingDueBillingWorkTargetsRow{}
	for rows.Next() {
		var i ListPendingDueBillingWorkTargetsRow
		if err := rows.Scan(&i.OrgID, &i.ProductID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertActivationBillingCycle = `-- name: UpsertActivationBillingCycle :execrows
INSERT INTO billing_cycles (cycle_id, org_id, product_id, currency, predecessor_cycle_id, anchor_at, cycle_seq, cadence_kind, starts_at, ends_at, status, finalization_due_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NULLIF($5, ''),
    $6,
    0,
    $7,
    $8,
    $9,
    'open',
    $9
)
ON CONFLICT (cycle_id) DO UPDATE
SET currency = EXCLUDED.currency,
    predecessor_cycle_id = EXCLUDED.predecessor_cycle_id,
    anchor_at = EXCLUDED.anchor_at,
    cycle_seq = EXCLUDED.cycle_seq,
    cadence_kind = EXCLUDED.cadence_kind,
    starts_at = EXCLUDED.starts_at,
    ends_at = EXCLUDED.ends_at,
    status = 'open',
    finalization_due_at = EXCLUDED.finalization_due_at,
    closed_reason = '',
    active_finalization_id = NULL,
    successor_cycle_id = NULL,
    closed_by_event_id = NULL,
    closed_for_usage_at = NULL,
    finalized_at = NULL,
    metadata = billing_cycles.metadata - 'voided_by'
WHERE billing_cycles.status = 'voided'
`

type UpsertActivationBillingCycleParams struct {
	CycleID            string
	OrgID              string
	ProductID          string
	Currency           string
	PredecessorCycleID interface{}
	AnchorAt           pgtype.Timestamptz
	CadenceKind        string
	StartsAt           pgtype.Timestamptz
	EndsAt             pgtype.Timestamptz
}

func (q *Queries) UpsertActivationBillingCycle(ctx context.Context, arg UpsertActivationBillingCycleParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertActivationBillingCycle,
		arg.CycleID,
		arg.OrgID,
		arg.ProductID,
		arg.Currency,
		arg.PredecessorCycleID,
		arg.AnchorAt,
		arg.CadenceKind,
		arg.StartsAt,
		arg.EndsAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertOpenBillingCycle = `-- name: UpsertOpenBillingCycle :execrows
INSERT INTO billing_cycles (cycle_id, org_id, product_id, currency, anchor_at, cycle_seq, cadence_kind, starts_at, ends_at, status, finalization_due_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    'open',
    $9
)
ON CONFLICT (cycle_id) DO UPDATE
SET currency = EXCLUDED.currency,
    anchor_at = EXCLUDED.anchor_at,
    cycle_seq = EXCLUDED.cycle_seq,
    cadence_kind = EXCLUDED.cadence_kind,
    starts_at = EXCLUDED.starts_at,
    ends_at = EXCLUDED.ends_at,
    status = 'open',
    finalization_due_at = EXCLUDED.finalization_due_at,
    closed_reason = '',
    active_finalization_id = NULL,
    successor_cycle_id = NULL,
    closed_by_event_id = NULL,
    closed_for_usage_at = NULL,
    finalized_at = NULL,
    metadata = billing_cycles.metadata - 'voided_by'
WHERE billing_cycles.status = 'voided'
`

type UpsertOpenBillingCycleParams struct {
	CycleID     string
	OrgID       string
	ProductID   string
	Currency    string
	AnchorAt    pgtype.Timestamptz
	CycleSeq    int64
	CadenceKind string
	StartsAt    pgtype.Timestamptz
	EndsAt      pgtype.Timestamptz
}

func (q *Queries) UpsertOpenBillingCycle(ctx context.Context, arg UpsertOpenBillingCycleParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertOpenBillingCycle,
		arg.CycleID,
		arg.OrgID,
		arg.ProductID,
		arg.Currency,
		arg.AnchorAt,
		arg.CycleSeq,
		arg.CadenceKind,
		arg.StartsAt,
		arg.EndsAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSuccessorBillingCycle = `-- name: UpsertSuccessorBillingCycle :execrows
INSERT INTO billing_cycles (cycle_id, org_id, product_id, currency, predecessor_cycle_id, anchor_at, cycle_seq, cadence_kind, starts_at, ends_at, status, finalization_due_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    'open',
    $10
)
ON CONFLICT (cycle_id) DO UPDATE
SET currency = EXCLUDED.currency,
    predecessor_cycle_id = EXCLUDED.predecessor_cycle_id,
    anchor_at = EXCLUDED.anchor_at,
    cycle_seq = EXCLUDED.cycle_seq,
    cadence_kind = EXCLUDED.cadence_kind,
    starts_at = EXCLUDED.starts_at,
    ends_at = EXCLUDED.ends_at,
    status = 'open',
    finalization_due_at = EXCLUDED.finalization_due_at,
    closed_reason = '',
    active_finalization_id = NULL,
    successor_cycle_id = NULL,
    closed_by_event_id = NULL,
    closed_for_usage_at = NULL,
    finalized_at = NULL,
    metadata = billing_cycles.metadata - 'voided_by'
WHERE billing_cycles.status = 'voided'
`

type UpsertSuccessorBillingCycleParams struct {
	CycleID            string
	OrgID              string
	ProductID          string
	Currency           string
	PredecessorCycleID pgtype.Text
	AnchorAt           pgtype.Timestamptz
	CycleSeq           int64
	CadenceKind        string
	StartsAt           pgtype.Timestamptz
	EndsAt             pgtype.Timestamptz
}

func (q *Queries) UpsertSuccessorBillingCycle(ctx context.Context, arg UpsertSuccessorBillingCycleParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertSuccessorBillingCycle,
		arg.CycleID,
		arg.OrgID,
		arg.ProductID,
		arg.Currency,
		arg.PredecessorCycleID,
		arg.AnchorAt,
		arg.CycleSeq,
		arg.CadenceKind,
		arg.StartsAt,
		arg.EndsAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
