// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGrantLedgerRowForUpdate = `-- name: GetGrantLedgerRowForUpdate :one
SELECT g.grant_id,
       g.org_id,
       g.scope_type,
       COALESCE(g.scope_product_id, '') AS scope_product_id,
       COALESCE(g.scope_bucket_id, '') AS scope_bucket_id,
       COALESCE(g.scope_sku_id, '') AS scope_sku_id,
       g.amount,
       g.source,
       g.source_reference_id,
       g.account_id::bytea AS account_id,
       g.deposit_transfer_id::bytea AS deposit_transfer_id,
       g.starts_at,
       COALESCE(g.scope_product_id, '') AS product_id
FROM credit_grants g
WHERE g.grant_id = $1
FOR UPDATE
`

type GetGrantLedgerRowForUpdateParams struct {
	GrantID string
}

type GetGrantLedgerRowForUpdateRow struct {
	GrantID           string
	OrgID             string
	ScopeType         string
	ScopeProductID    string
	ScopeBucketID     string
	ScopeSkuID        string
	Amount            int64
	Source            string
	SourceReferenceID string
	AccountID         []byte
	DepositTransferID []byte
	StartsAt          pgtype.Timestamptz
	ProductID         string
}

func (q *Queries) GetGrantLedgerRowForUpdate(ctx context.Context, arg GetGrantLedgerRowForUpdateParams) (GetGrantLedgerRowForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getGrantLedgerRowForUpdate, arg.GrantID)
	var i GetGrantLedgerRowForUpdateRow
	err := row.Scan(
		&i.GrantID,
		&i.OrgID,
		&i.ScopeType,
		&i.ScopeProductID,
		&i.ScopeBucketID,
		&i.ScopeSkuID,
		&i.Amount,
		&i.Source,
		&i.SourceReferenceID,
		&i.AccountID,
		&i.DepositTransferID,
		&i.StartsAt,
		&i.ProductID,
	)
	return i, err
}

const getLedgerAccount = `-- name: GetLedgerAccount :one
SELECT account_key, account_id::bytea AS account_id, ledger, code, flags
FROM billing_ledger_accounts
WHERE account_key = $1
`

type GetLedgerAccountParams struct {
	AccountKey string
}

type GetLedgerAccountRow struct {
	AccountKey string
	AccountID  []byte
	Ledger     int32
	Code       int32
	Flags      int32
}

func (q *Queries) GetLedgerAccount(ctx context.Context, arg GetLedgerAccountParams) (GetLedgerAccountRow, error) {
	row := q.db.QueryRow(ctx, getLedgerAccount, arg.AccountKey)
	var i GetLedgerAccountRow
	err := row.Scan(
		&i.AccountKey,
		&i.AccountID,
		&i.Ledger,
		&i.Code,
		&i.Flags,
	)
	return i, err
}

const getLedgerCommand = `-- name: GetLedgerCommand :one
SELECT command_id, operation, aggregate_type, aggregate_id, org_id, product_id, payload, attempts
FROM billing_ledger_commands
WHERE command_id = $1
`

type GetLedgerCommandParams struct {
	CommandID string
}

type GetLedgerCommandRow struct {
	CommandID     string
	Operation     string
	AggregateType string
	AggregateID   string
	OrgID         string
	ProductID     string
	Payload       []byte
	Attempts      int32
}

func (q *Queries) GetLedgerCommand(ctx context.Context, arg GetLedgerCommandParams) (GetLedgerCommandRow, error) {
	row := q.db.QueryRow(ctx, getLedgerCommand, arg.CommandID)
	var i GetLedgerCommandRow
	err := row.Scan(
		&i.CommandID,
		&i.Operation,
		&i.AggregateType,
		&i.AggregateID,
		&i.OrgID,
		&i.ProductID,
		&i.Payload,
		&i.Attempts,
	)
	return i, err
}

const getLedgerCommandByIdempotencyKey = `-- name: GetLedgerCommandByIdempotencyKey :one
SELECT command_id, payload
FROM billing_ledger_commands
WHERE idempotency_key = $1
`

type GetLedgerCommandByIdempotencyKeyParams struct {
	IdempotencyKey string
}

type GetLedgerCommandByIdempotencyKeyRow struct {
	CommandID string
	Payload   []byte
}

func (q *Queries) GetLedgerCommandByIdempotencyKey(ctx context.Context, arg GetLedgerCommandByIdempotencyKeyParams) (GetLedgerCommandByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getLedgerCommandByIdempotencyKey, arg.IdempotencyKey)
	var i GetLedgerCommandByIdempotencyKeyRow
	err := row.Scan(&i.CommandID, &i.Payload)
	return i, err
}

const insertLedgerAccount = `-- name: InsertLedgerAccount :exec
INSERT INTO billing_ledger_accounts (account_key, account_id, ledger, code, flags, account_kind, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (account_key) DO NOTHING
`

type InsertLedgerAccountParams struct {
	AccountKey  string
	AccountID   interface{}
	Ledger      int32
	Code        int32
	Flags       int32
	AccountKind string
	Description string
}

func (q *Queries) InsertLedgerAccount(ctx context.Context, arg InsertLedgerAccountParams) error {
	_, err := q.db.Exec(ctx, insertLedgerAccount,
		arg.AccountKey,
		arg.AccountID,
		arg.Ledger,
		arg.Code,
		arg.Flags,
		arg.AccountKind,
		arg.Description,
	)
	return err
}

const insertLedgerCommand = `-- name: InsertLedgerCommand :exec
INSERT INTO billing_ledger_commands (
    command_id, operation, aggregate_type, aggregate_id, org_id, product_id, idempotency_key, payload, state
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending')
ON CONFLICT (idempotency_key) DO NOTHING
`

type InsertLedgerCommandParams struct {
	CommandID      string
	Operation      string
	AggregateType  string
	AggregateID    string
	OrgID          string
	ProductID      string
	IdempotencyKey string
	Payload        []byte
}

func (q *Queries) InsertLedgerCommand(ctx context.Context, arg InsertLedgerCommandParams) error {
	_, err := q.db.Exec(ctx, insertLedgerCommand,
		arg.CommandID,
		arg.Operation,
		arg.AggregateType,
		arg.AggregateID,
		arg.OrgID,
		arg.ProductID,
		arg.IdempotencyKey,
		arg.Payload,
	)
	return err
}

const insertLedgerDriftEvent = `-- name: InsertLedgerDriftEvent :exec
INSERT INTO billing_ledger_drift_events (
    drift_id, drift_kind, severity, aggregate_type, aggregate_id, pg_snapshot, tigerbeetle_snapshot
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (drift_id) DO NOTHING
`

type InsertLedgerDriftEventParams struct {
	DriftID             string
	DriftKind           string
	Severity            string
	AggregateType       string
	AggregateID         string
	PgSnapshot          []byte
	TigerbeetleSnapshot []byte
}

func (q *Queries) InsertLedgerDriftEvent(ctx context.Context, arg InsertLedgerDriftEventParams) error {
	_, err := q.db.Exec(ctx, insertLedgerDriftEvent,
		arg.DriftID,
		arg.DriftKind,
		arg.Severity,
		arg.AggregateType,
		arg.AggregateID,
		arg.PgSnapshot,
		arg.TigerbeetleSnapshot,
	)
	return err
}

const leaseLedgerCommand = `-- name: LeaseLedgerCommand :one
UPDATE billing_ledger_commands
SET state = 'in_progress',
    attempts = attempts + 1,
    last_attempt_at = now(),
    lease_expires_at = now() + interval '30 seconds',
    leased_by = 'billing-service',
    last_attempt_id = $2
WHERE command_id = $1
  AND state IN ('pending', 'retryable_failed', 'in_progress')
  AND (state <> 'in_progress' OR lease_expires_at IS NULL OR lease_expires_at < now())
RETURNING command_id, operation, aggregate_type, aggregate_id, org_id, product_id, payload, attempts
`

type LeaseLedgerCommandParams struct {
	CommandID     string
	LastAttemptID string
}

type LeaseLedgerCommandRow struct {
	CommandID     string
	Operation     string
	AggregateType string
	AggregateID   string
	OrgID         string
	ProductID     string
	Payload       []byte
	Attempts      int32
}

func (q *Queries) LeaseLedgerCommand(ctx context.Context, arg LeaseLedgerCommandParams) (LeaseLedgerCommandRow, error) {
	row := q.db.QueryRow(ctx, leaseLedgerCommand, arg.CommandID, arg.LastAttemptID)
	var i LeaseLedgerCommandRow
	err := row.Scan(
		&i.CommandID,
		&i.Operation,
		&i.AggregateType,
		&i.AggregateID,
		&i.OrgID,
		&i.ProductID,
		&i.Payload,
		&i.Attempts,
	)
	return i, err
}

const listOperatorLedgerAccounts = `-- name: ListOperatorLedgerAccounts :many
SELECT account_key, account_id::bytea AS account_id
FROM billing_ledger_accounts
WHERE account_kind = 'operator'
ORDER BY account_key
`

type ListOperatorLedgerAccountsRow struct {
	AccountKey string
	AccountID  []byte
}

func (q *Queries) ListOperatorLedgerAccounts(ctx context.Context) ([]ListOperatorLedgerAccountsRow, error) {
	rows, err := q.db.Query(ctx, listOperatorLedgerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperatorLedgerAccountsRow{}
	for rows.Next() {
		var i ListOperatorLedgerAccountsRow
		if err := rows.Scan(&i.AccountKey, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingGrantDeposits = `-- name: ListPendingGrantDeposits :many
SELECT grant_id
FROM credit_grants
WHERE org_id = $1
  AND closed_at IS NULL
  AND ledger_posting_state IN ('pending', 'retryable_failed')
  AND ($2 = '' OR COALESCE(scope_product_id, $2) = $2 OR scope_type = 'account')
ORDER BY starts_at, grant_id
`

type ListPendingGrantDepositsParams struct {
	OrgID   string
	Column2 interface{}
}

func (q *Queries) ListPendingGrantDeposits(ctx context.Context, arg ListPendingGrantDepositsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPendingGrantDeposits, arg.OrgID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var grant_id string
		if err := rows.Scan(&grant_id); err != nil {
			return nil, err
		}
		items = append(items, grant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingLedgerCommands = `-- name: ListPendingLedgerCommands :many
SELECT command_id, state
FROM billing_ledger_commands
WHERE (
    state IN ('pending', 'retryable_failed')
    AND next_attempt_at <= now()
  )
  OR (
    state = 'in_progress'
    AND (lease_expires_at IS NULL OR lease_expires_at < now())
  )
  OR (
    state = 'posted'
    AND (
      (operation = 'grant_deposit' AND EXISTS (
        SELECT 1 FROM credit_grants g
        WHERE g.grant_id = aggregate_id AND g.ledger_posting_state <> 'posted'
      ))
      OR (operation = 'settle_window' AND EXISTS (
        SELECT 1 FROM billing_windows w
        WHERE w.window_id = aggregate_id AND w.state = 'settling'
      ))
    )
  )
ORDER BY next_attempt_at, created_at, command_id
LIMIT $1
`

type ListPendingLedgerCommandsParams struct {
	Limit int32
}

type ListPendingLedgerCommandsRow struct {
	CommandID string
	State     string
}

func (q *Queries) ListPendingLedgerCommands(ctx context.Context, arg ListPendingLedgerCommandsParams) ([]ListPendingLedgerCommandsRow, error) {
	rows, err := q.db.Query(ctx, listPendingLedgerCommands, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingLedgerCommandsRow{}
	for rows.Next() {
		var i ListPendingLedgerCommandsRow
		if err := rows.Scan(&i.CommandID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostedGrantSnapshotsForReconcile = `-- name: ListPostedGrantSnapshotsForReconcile :many
SELECT grant_id, org_id, COALESCE(scope_product_id, '') AS product_id, amount, account_id::bytea AS account_id
FROM credit_grants
WHERE closed_at IS NULL
  AND ledger_posting_state = 'posted'
ORDER BY starts_at, grant_id
LIMIT $1
`

type ListPostedGrantSnapshotsForReconcileParams struct {
	Limit int32
}

type ListPostedGrantSnapshotsForReconcileRow struct {
	GrantID   string
	OrgID     string
	ProductID string
	Amount    int64
	AccountID []byte
}

func (q *Queries) ListPostedGrantSnapshotsForReconcile(ctx context.Context, arg ListPostedGrantSnapshotsForReconcileParams) ([]ListPostedGrantSnapshotsForReconcileRow, error) {
	rows, err := q.db.Query(ctx, listPostedGrantSnapshotsForReconcile, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostedGrantSnapshotsForReconcileRow{}
	for rows.Next() {
		var i ListPostedGrantSnapshotsForReconcileRow
		if err := rows.Scan(
			&i.GrantID,
			&i.OrgID,
			&i.ProductID,
			&i.Amount,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettledGrantUsage = `-- name: ListSettledGrantUsage :many
SELECT l.grant_id, SUM(l.amount_posted)::bigint AS amount_posted
FROM billing_window_ledger_legs l
JOIN billing_windows w ON w.window_id = l.window_id
WHERE w.state = 'settled'
  AND l.state = 'posted'
  AND l.grant_id = ANY($1::text[])
GROUP BY l.grant_id
ORDER BY l.grant_id
`

type ListSettledGrantUsageParams struct {
	Column1 []string
}

type ListSettledGrantUsageRow struct {
	GrantID      pgtype.Text
	AmountPosted int64
}

func (q *Queries) ListSettledGrantUsage(ctx context.Context, arg ListSettledGrantUsageParams) ([]ListSettledGrantUsageRow, error) {
	rows, err := q.db.Query(ctx, listSettledGrantUsage, arg.Column1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettledGrantUsageRow{}
	for rows.Next() {
		var i ListSettledGrantUsageRow
		if err := rows.Scan(&i.GrantID, &i.AmountPosted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGrantLedgerPostingFailed = `-- name: MarkGrantLedgerPostingFailed :one
UPDATE credit_grants
SET ledger_posting_state = 'retryable_failed',
    ledger_last_error = $2
WHERE grant_id = $1
RETURNING org_id, COALESCE(scope_product_id, '') AS product_id
`

type MarkGrantLedgerPostingFailedParams struct {
	GrantID         string
	LedgerLastError string
}

type MarkGrantLedgerPostingFailedRow struct {
	OrgID     string
	ProductID string
}

func (q *Queries) MarkGrantLedgerPostingFailed(ctx context.Context, arg MarkGrantLedgerPostingFailedParams) (MarkGrantLedgerPostingFailedRow, error) {
	row := q.db.QueryRow(ctx, markGrantLedgerPostingFailed, arg.GrantID, arg.LedgerLastError)
	var i MarkGrantLedgerPostingFailedRow
	err := row.Scan(&i.OrgID, &i.ProductID)
	return i, err
}

const markGrantLedgerPostingInProgress = `-- name: MarkGrantLedgerPostingInProgress :exec
UPDATE credit_grants
SET ledger_posting_state = 'in_progress',
    ledger_last_error = ''
WHERE grant_id = $1 AND ledger_posting_state IN ('pending', 'retryable_failed', 'in_progress')
`

type MarkGrantLedgerPostingInProgressParams struct {
	GrantID string
}

func (q *Queries) MarkGrantLedgerPostingInProgress(ctx context.Context, arg MarkGrantLedgerPostingInProgressParams) error {
	_, err := q.db.Exec(ctx, markGrantLedgerPostingInProgress, arg.GrantID)
	return err
}

const markGrantLedgerPostingPosted = `-- name: MarkGrantLedgerPostingPosted :one
UPDATE credit_grants
SET ledger_posting_state = 'posted',
    ledger_posted_at = now(),
    ledger_last_error = ''
WHERE grant_id = $1 AND ledger_posting_state <> 'posted'
RETURNING org_id, COALESCE(scope_product_id, '') AS product_id, source, amount
`

type MarkGrantLedgerPostingPostedParams struct {
	GrantID string
}

type MarkGrantLedgerPostingPostedRow struct {
	OrgID     string
	ProductID string
	Source    string
	Amount    int64
}

func (q *Queries) MarkGrantLedgerPostingPosted(ctx context.Context, arg MarkGrantLedgerPostingPostedParams) (MarkGrantLedgerPostingPostedRow, error) {
	row := q.db.QueryRow(ctx, markGrantLedgerPostingPosted, arg.GrantID)
	var i MarkGrantLedgerPostingPostedRow
	err := row.Scan(
		&i.OrgID,
		&i.ProductID,
		&i.Source,
		&i.Amount,
	)
	return i, err
}

const markLedgerCommandFailed = `-- name: MarkLedgerCommandFailed :exec
UPDATE billing_ledger_commands
SET state = $2,
    next_attempt_at = $3::timestamptz,
    last_error = $4,
    lease_expires_at = NULL,
    leased_by = '',
    dead_lettered_at = COALESCE($5::timestamptz, dead_lettered_at),
    dead_letter_reason = COALESCE(NULLIF($6, ''), dead_letter_reason)
WHERE command_id = $1
`

type MarkLedgerCommandFailedParams struct {
	CommandID string
	State     string
	Column3   pgtype.Timestamptz
	LastError string
	Column5   pgtype.Timestamptz
	Column6   interface{}
}

func (q *Queries) MarkLedgerCommandFailed(ctx context.Context, arg MarkLedgerCommandFailedParams) error {
	_, err := q.db.Exec(ctx, markLedgerCommandFailed,
		arg.CommandID,
		arg.State,
		arg.Column3,
		arg.LastError,
		arg.Column5,
		arg.Column6,
	)
	return err
}

const markLedgerCommandPosted = `-- name: MarkLedgerCommandPosted :exec
UPDATE billing_ledger_commands
SET state = 'posted',
    posted_at = now(),
    last_error = '',
    lease_expires_at = NULL,
    leased_by = ''
WHERE command_id = $1
`

type MarkLedgerCommandPostedParams struct {
	CommandID string
}

func (q *Queries) MarkLedgerCommandPosted(ctx context.Context, arg MarkLedgerCommandPostedParams) error {
	_, err := q.db.Exec(ctx, markLedgerCommandPosted, arg.CommandID)
	return err
}
